### ISSUE TITLE
Setting authentication in the app

### ISSUE THREAD

**Issue by GlenIssac** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#110]
Where an earth do i open the "app" im so confused. Is it in the folder or do i need to dowload anything. Kinda new to this stuff

**Comment by Melvin-Abraham** [comment]
@GlenIssac Assuming you installed the application using the installer _(based on your platform)_ from [Releases](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases) and opened it from your system's launcher, you can then open the "app" using the keyboard shortcut **"Windows Key/Super/Command + Shift + A"** (see [Default Keyboard Shortcut](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#default-keyboard-shortcut)).

**Comment by Melvin-Abraham** [comment]
As per latest changes, you will get a notification on start regarding the hotkey to start the app. Additionally, now opening another instance of the app will reveal the app (from the tray).

_Closing as resolved_
