### ISSUE TITLE
Add a simple shortcut to open the assistant with one click.

### ISSUE THREAD

**Issue by csansoon** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#113]
**Is your feature request related to a problem? Please describe.**
When I open the assistant using the icon in my taskbar I get a **Preventing launch** error because there is an instance already running.
![image](https://user-images.githubusercontent.com/57395395/107848499-1b283600-6df4-11eb-8e79-149bd76dd0d7.png)

**Describe the solution you'd like**
 Opening the app this way should call the aleady running instance to open, like when I use the key shortcut.

**Additional context**
I could open the assistant from the Windows Menu or the taskbar itself
![image](https://user-images.githubusercontent.com/57395395/107848525-5cb8e100-6df4-11eb-8512-5f31ee4965e7.png)
![image](https://user-images.githubusercontent.com/57395395/107848512-4448c680-6df4-11eb-8b76-de7668d70dca.png)

**Comment by GlenIssac** [comment]
How do you even open the app. In the folder

**Comment by KimJudge** [comment]
I am getting the same problem and cannot continue with installation beyond this point. HELP!

**Comment by KimJudge** [comment]
Additionally, I would like to add that the GA was not appearing on my taskbar despite the action stating that the app was already running.

**Comment by Melvin-Abraham** [comment]
@csansoon @KimJudge By default the assistant will be hidden and minimized to tray when launched. You will need to follow either steps to launch the assistant after running the application:

- Try launching the assistant with the keyboard shortcut `Super + Shift + A`
- Right-click on the Google Assistant tray icon and click on **"Launch Assistant"**

**PS:** The assistant will take some time to initialize _(indicated by grayscale Google Assistant icon)_. Executing any of the above steps during this time will not launch the assistant. You will have to wait until you see the colorful Google Assistant Icon in the tray and then try to launch the assistant.

**Comment by KimJudge** [comment]
Thanks Melvin, I've managed to sort it out and have been enjoying the GA so far. I would like to share some further feedback with you, if you are accepting any at this time.

**Comment by Melvin-Abraham** [comment]
Implemented in PR #101.
_Closing this issue as resolved_
