### ISSUE TITLE
Cant click the submit button!?

### ISSUE THREAD

**Issue by Molto06** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#115]
I followed all of the authentication steps and I got to the part where you have to paste the authentication code into the box and press submit. I pasted it in but I can't press submit, nothing happens!
Can you help me?

**Comment by Melvin-Abraham** [comment]
@Molto06 This is a duplicate of issue #39.

This should help:

> Fixed in dd67747. Since, this fix will not be readily available until next release ... you can _temporarily_ disable **Settings** > **Conversation** > **Enable microphone on application startup**

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/39#issuecomment-734111970

PS: Please do close the issue if this helps
