### ISSUE TITLE
Running refresh from inside g-assist fails due to missing pkexec command

### ISSUE THREAD

**Issue by castrojo** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#12]
_Thank you_ for this tool, this is really great! I got a notification in the window about it being out of date so I followed the instructions and got this error:

![Selection_010](https://user-images.githubusercontent.com/1264109/94823043-6146a500-03d1-11eb-9a1e-70412bdd5687.png)
<!-- 

Ubuntu 20.04
I can confirm that `/usr/bin/pkexec` exists on my system.

**Comment by castrojo** [comment]
Hit enter too soon: OS is Ubuntu 20.04, and I can confirm that `/usr/bin/pkexec` exists on my system.

**Comment by Melvin-Abraham** [comment]
This seems like an issue exclusive to "strictly" confined snap as this used to work in "classic" snap. This restriction may be due to security reasons.

**Comment by Melvin-Abraham** [comment]
_Addressed in 1582872188_: The `snap refresh` command is no longer called as it mostly updates by itself automatically.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
