### ISSUE TITLE
French does work bad and mic access is automaticly off

### ISSUE THREAD

**Issue by 15locraft** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#122]
Hello,

I've just installed and g-assist does not work on mic and french with the mic does not completly worked. OS : Pop!_OS with KDE plasma desktop environment

**Comment by SRThibaultP** [comment]
Surprising, 
I don't have any problem with gassist or mic with french using W10 insider.

**Comment by Melvin-Abraham** [comment]
@15locraft Transcription is done by the Google Assistant SDK and it entirely depends on the microphone of the device. Make sure that the sensitivity of the mic is not low or the environment is not noisy. It could also depend on the internet connection...

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
