### ISSUE TITLE
🐛Bug: "Close on blur" not working well when open the inspector

### ISSUE THREAD

**Issue by esau-morais** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#124]
**Describe the bug**

Basically, when I open the inspector and try to inspect anything or use any tools from the DevTools with the "Close on blur" option set, it doesn't work well and closes the Assistant window.

**To Reproduce**
1. Go to Settings
2. Scroll down till find the Window Float Behavior option
3. Click the "Close on blur" option
4. Save the changes
5. Try to use the inspector (`Ctrl+Shift+I` or just `F12`)
6. See that the Assistant window will close "automatically"

**Expected behavior**
Just close when the loses the focus.

**Screenshots**
I can't take screenshots, once the window closes too fast.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Version: 1909

**Comment by Melvin-Abraham** [comment]
@esau-morais Thank you for reporting the issue. This will be fixed very soon...

**Comment by esau-morais** [comment]
> @esau-morais Thank you for reporting the issue. This will be fixed very soon...

If there's any help needed, I can give it try
