### ISSUE TITLE
Final Authentication not working

### ISSUE THREAD

**Issue by EthanMac1915** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#126]
During the install process, the final step is for a tab to open up and give you a token code, this works, however when i paste and submit, nothing happens. no matter if i try closing or relaunching the assistant, the submit button does not seem to work. Im Running Windows 10 Pro, Build 21301-1645

**Comment by eoliveau** [comment]
Had the same problem a few minutes ago, i started the app as admin and it worked fine after that.

**Comment by Molto06** [comment]
Try going to settings and turning the 'Enable microphone on application startup' setting off. That seemed to work for me.

**Comment by Juka117** [comment]
is this still occurring for you @EthanMac1915 please?

**Comment by EthanMac1915** [comment]
This has been fixed thanks!! Following @Molto06's instructions and then restarting the app and it worked fine!
