### ISSUE TITLE
Failed to get tokens

### ISSUE THREAD

**Issue by Molto06** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#127]
Hello
I followed the authentication process and pasted the code into the box. It then loaded for 10 seconds and displayed the message below

**Failed to get Tokens
Assistant failed to fetch the tokens from the server. Either the auth code is invalid or the rate limit might have exceeded.
Try selecting a different Google Account.**

I have tried waiting until the next day like you have said but it still gives me this message

can you help?

**Comment by esau-morais** [comment]
Duplicated issue. See #88

**Comment by Molto06** [comment]
I have already tried waiting until the next day and uninstalling and reinstalling the app. It still brings up this message though.

**Comment by Melvin-Abraham** [comment]
@Molto06 Can you try authenticating with another Google Account?
**PS:** You will have to add that particular Google account under "Test Users".

**Comment by Molto06** [comment]
Thanks so much for your help so far! Where could I save a file in a place that doesn't have admin rights?

**Comment by Melvin-Abraham** [comment]
@Molto06 You can save these files in other drives like "D:", "E:" or other drives if you are on Windows

**Comment by Molto06** [comment]
Thanks for your help. I have encountered a whole load of other problems now and I guess that is because of the security system our device uses. I am just not going to bother with this anymore but I do think this is a great piece of software and I wish I was one of the people that could get it to work.

**Comment by Juka117** [comment]
@Molto06 it's a pity to hear this. if you want I can assist you in every step using this thread. don't worry about the amount of steps you are stuck in, let's flatten them together one by one

**Comment by Molto06** [comment]
Thank you for offering but don't worry! I might try it all again in a few months after the app has been updated again 🙂
