### ISSUE TITLE
Fails to open on macOS

### ISSUE THREAD

**Issue by ev-dev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#128]
**Describe the bug**
App fails to load UI when launching via `npm start`, running from dist build, or trying to open via downloaded/installed release build. Also unable to open dev tools in Electron to inspect runtime errors. 

**To Reproduce**
1. Open .app or run `npm start`
2. No window being launched from the process

**Expected behavior**
A visible UI window should be initialized from App 

**Desktop (please complete the following information):**
 - OS: macOS 11.2 (Intel) testing/built with Node.js v15.8.0
 - Version 1.0.0-rc.2

**Additional context** 
The Electron process does clearly launch and is visible in the dock but no app shell or any window is opened and no error info is visible either.

Not at all sure if this is relevant, but when running via `npm start` or launching the dist from terminal, the logs show repeated messages for `Electron Helper (Plugin)[31133:3009778] OBSDAL: ...`

The repeated logs for this are: 
- `Device unhandled setPropertyDataWithAddress for kCMIOObjectPropertyListenerAdded`
- `HardwarePlugIn_ObjectSetPropertyData Device(40) kCMIOObjectPropertyListenerAdded self=0x10df66e00 data(int)= ...`
- `Device unhandled hasPropertyWithAddress for kCMIOObjectPropertyOwnedObjects`

**Comment by ev-dev** [comment]
^ This appears to have been a conflict with Electron and a third-party virtual camera/mic app I had installed which had some outdated/unsupported install/loading method related to newer policies for kexts in mac. 

The conflict likely would have broken other Electron apps which tried to request the system's media I/O devices and so it seems as if my issue had no relation to this project, closing... 😇

**Comment by levyitay** [comment]
@ev-dev how did you fix it or found which mic / camera third party app was it?

**Comment by ev-dev** [comment]
TBH I was less systematic about it than I should've been but my first searches citing similar Electron log messages (posted above) all seemed to involve some problems with virtual cam/mic drivers [like this issue involving an OBS project](https://github.com/johnboiles/obs-mac-virtualcam/issues/206).

I had several of these apps (including [Iriun](https://iriun.com) & [Camtwist](http://camtwiststudio.com/)) installed leftover from an early pandemic rush to improve my cam quality, and seeing as I have since stopped using them, I opted to just remove all traces of them from my system, after which I was able to launch the dist release of the assistant desktop client. 

Apologies for the less-than-ideal process, if any related issues come up I'd be happy to chime in with more

**Comment by levyitay** [comment]
Thanks, I'll do some more digging

**Comment by milosmns** [comment]
I am now experiencing the same issue, while other Electron apps do work (Slack)
