### ISSUE TITLE
Very difficult to set up

### ISSUE THREAD

**Issue by davman808** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#129]
i think it is amazing that a small group of individuals can adjust an entire ai designed for phones by an enormous company to work on a pc/mac, but JEEBUS CHRIST it is difficult to set up. i sat on my ass for legit half an hour just to get this thing to work. if it's not possible to make easier, then oh well better than nothing. with that said though, keep going, you're doing an amazing job!

**Comment by Juka117** [comment]
@davman808 kindly close the issue if you are happy with the progress. I think we are in the middle of something epic so being a bit difficult to set up initially is more than reasonable. Let's reduce the issues and focus on introducing new features ;) If it makes you feel better, everyone spent at least 30 minutes setting it up :)

**Comment by davman808** [comment]
Alright then
