### ISSUE TITLE
The assistant can use its own style

### ISSUE THREAD

**Issue by EnderAdel** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#13]
This project is amazing. But maybe you have to change the style of the project to fit Desktops.

**Comment by Melvin-Abraham** [comment]
@EnderAdel Can you elaborate more on that and give a clear idea about what's exactly on your mind?

**Comment by EnderAdel** [comment]
One of the things to do is to make it so the window would look more like a normal system window. The style of the current window doesn't fit in at all.

**Comment by Melvin-Abraham** [comment]
This doesn't seem like a huge concern as this does not necessarily improve the user's experience. So, I'm not sure if this will be worked upon. Anyway, I will label this issue as a low priority.

**Comment by micahlt** [comment]
@Melvin-Abraham I disagree with this user - this project is awesome, and the UI is consistent with other platforms.  There are plenty of apps that don't blend with their OS interfaces!  This one looks fine.  😊

**Comment by adel-sbeh** [comment]
The UI does look awesome, indeed. But it's not that efficient when it comes to PCs. I could use some tweaks here and there.

**Comment by Melvin-Abraham** [comment]
> But it's not that efficient when it comes to PCs. It could use some tweaks here and there.

@adel-sbeh What kind of tweaks are you planning to apply? Also, please describe, if any, the benefits of doing so...

**Comment by niksingh710** [comment]
The UI is amazing no need change that but what we can do is set custom shortcuts for accessing voice and 

for e.g, if we use the shortcut to access the voice command it should not appear as a new window, a small pop up in the right bottom corner with voice waving motion showing that the assistant is listening to our question and give result as voice. kinda minimal implementation 


Not a thing to be forced implemented as this is amazing as it is but my idea could be considered if a UI overhaul is going to be done in the future.

**Comment by adel-sbeh** [comment]
At least add a thin border and a shadow, so it would not look strange on Windows.

**Comment by regisandre** [comment]
This is a feature that is difficult to add, but we should leave the possibility of creating themes by the community that can be integrated by an option in the settings. And since it's web development, it could be pretty straightforward for the community.

**Comment by adel-sbeh** [comment]
How come? It's CSS. It's as easy as giving an element a border. The window is frameless...

**Comment by Melvin-Abraham** [comment]
@adel-sbeh Window border has been added as per the commit 72b8932. This should be enough to create distinction between the application and the background. I hope this resolves your issue to some extent.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved..._
