### ISSUE TITLE
FAQ in Wiki

### ISSUE THREAD

**Issue by Juka117** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#134]
Is is possible to have an FAQs in the Wiki tab so that people could revert to it when in difficulty? This will reduce the number of duplicate issues and issues related to inability to finish the initial wizard (especially).

It would be great if we could contribute to it too!

Keep up the great work guys!

**Comment by Melvin-Abraham** [comment]
@Juka117 That seems to be a great suggestion... 👍

**Comment by Melvin-Abraham** [comment]
The FAQ wiki is now available in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ).
