### ISSUE TITLE
Unable to change hotkey (Alt. Req to add changeable hotkey)

### ISSUE THREAD

**Issue by AVHaCkErr** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#138]
No option in settings to change the hotkey, I have browsed through the in-app settings and was not able to find said option, help would be appreciated. Thanks a lot.

I am not sure as to if that is a feature or not. but what I could make from 

> _"Note: Keyboard shortcut is configurable in the settings"_

It seemed as if it's a pre-existing feature. 

[](https://www.youtube.com/watch?v=Z-kBrUujoP8)

(https://www.youtube.com/watch?v=Z-kBrUujoP8)

**Comment by rbrouwer** [comment]
If you build from source, you will have it. It is not present yet in the latest release build.

**Comment by AVHaCkErr** [comment]
Thanks. Resolved.
