### ISSUE TITLE
Electron window is not launching

### ISSUE THREAD

**Issue by sayoojsamuel** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#14]
**Describe the bug**
On running `npm start`, the electron window is not launching.  The following error is logged in the terminal, 

>(node:5462) Electron: Loading non-context-aware native module in renderer: '/home/v4d3r/Downloads/packages/Google-Assistant-Unofficial-Desktop-Client/node_modules/grpc/src/node/extension_binary/electron-v9.0-linux-x64-glibc/grpc_node.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

**To Reproduce**
1. Go to the project directory
2. run `npm install`
3. run `npm start`
4. The task-bar tray icon is started,  however the app does not launch.  

**Expected behavior**
The landing window should pop up. 

**Screenshots**
#### Tray Icon
![image](https://user-images.githubusercontent.com/31436104/95137642-27d1b900-0786-11eb-9767-7bcc84960f4e.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux 5.8.13-arch1-1 with deepin20-wm
 - GAUDC Version 1.0.0-rc.1
 - Electron: v9.2.1

**Additional context**
The same behaviour is noticed after building and running `g-assist`

**Comment by Melvin-Abraham** [comment]
The warning in the terminal is expected considering the native module **grpc** is not context aware as of now. Also, the app has to be launched by `Super + Shift + A` keyboard shortcut ([refer to this](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#keyboard-shortcut)). You can also launch the assistant by right-clicking the tray icon and selecting **"Launch Assistant"** option.

**Comment by sayoojsamuel** [comment]
@Melvin-Abraham so I had already tried both the methods.  However, the same error is logged in the terminal.  

![GAUDC](https://user-images.githubusercontent.com/31436104/95159846-b4976980-07bc-11eb-86c9-1369863316f4.gif)

**Comment by Melvin-Abraham** [comment]
I have added a new commit which includes addition of "Open DevTools" option in tray icon context menu. Launch the assistant as usual (via any of the two methods) and then click "Open DevTools". If there are any errors logged in the DevTools console, do specify in here...

**Comment by sayoojsamuel** [comment]
@Melvin-Abraham `DevTools` option gave a great head start.  The issue was due to having dual screens with different orientation.  The app defaults to open in the center of the screenspace, hence was hidden in the non visible area.   

![image](https://user-images.githubusercontent.com/31436104/95241416-581f6300-082b-11eb-9cfe-7bae15f3fddd.png)

Would it be possible to align the app within one screen?

**Comment by Melvin-Abraham** [comment]
Just to get some idea about the display, can you execute `electron.remote.screen.getAllDisplay()` and `electron.remote.screen.getPrimaryDisplay()` in the DevTools and share the log?

**Comment by sayoojsamuel** [comment]
Running `electron.remote.screen.getPrimaryDisplay()` yields 

```js
electron.remote.screen.getPrimaryDisplay()
{id: 1881264395124802, bounds: {…}, workArea: {…}, accelerometerSupport: "unknown", monochrome: false, …}
accelerometerSupport: "unknown"
bounds: {x: 0, y: 598, width: 1366, height: 768}
colorDepth: 24
colorSpace: "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}"
depthPerComponent: 8
id: 1881264395124802
internal: false
monochrome: false
rotation: 0
scaleFactor: 1
size: {width: 1366, height: 768}
touchSupport: "unknown"
workArea: {x: 0, y: 598, width: 1366, height: 768}
workAreaSize: {width: 1366, height: 768}
__proto__: Object
```

---

Running `electron.remote.screen.getAllDisplays()` return the following
```js
(2) [{…}, {…}]
0:
accelerometerSupport: "unknown"
bounds: {x: 0, y: 598, width: 1366, height: 768}
colorDepth: 24
colorSpace: "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}"
depthPerComponent: 8
id: 1881264395124802
internal: false
monochrome: false
rotation: 0
scaleFactor: 1
size: {width: 1366, height: 768}
touchSupport: "unknown"
workArea: {x: 0, y: 598, width: 1366, height: 768}
workAreaSize: {width: 1366, height: 768}
__proto__: Object
1:
accelerometerSupport: "unknown"
bounds: {x: 1366, y: 0, width: 768, height: 1366}
colorDepth: 24
colorSpace: "{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}"
depthPerComponent: 8
id: 4692798670932035
internal: false
monochrome: false
rotation: 90
scaleFactor: 1
size: {width: 768, height: 1366}
touchSupport: "unknown"
workArea: {x: 1366, y: 0, width: 768, height: 1366}
workAreaSize: {width: 768, height: 1366}```

**Comment by Melvin-Abraham** [comment]
Thank you @sayoojsamuel, I'll look into that...

**Comment by Melvin-Abraham** [comment]
@sayoojsamuel Can you check if this commit helps?

**Comment by sayoojsamuel** [comment]
I suppose this issue is now resolved.  The Display Preferences option is working perfectectly.  
![image](https://user-images.githubusercontent.com/31436104/97413412-c5a14980-1928-11eb-9f31-3d8427b8324c.png)
