### ISSUE TITLE
Chained responses

### ISSUE THREAD

**Issue by donno2048** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#141]
**Describe the bug**

Sometimes Google assistant would respond with chained responses but the client would show only the first result.

**To Reproduce**

If you type:

 > Tell me about GitHub

Everything works fine because there is only one response, but if you try:

 > Show me results about GitHub

The only output is: "Here's a result from the web" with no additional information because chained responses won't pass.

**Expected behavior**

Obviously, we would like to see all the responses one by one.

**Comment by rbrouwer** [comment]
I think this is a duplicate of #41

**Comment by donno2048** [comment]
Oops...
