### ISSUE TITLE
Change shortcut Win + SHIFT + A to something else

### ISSUE THREAD

**Issue by H0nzik1** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#147]
Please, add feature for different keyboard shortcut, thank you!

**Comment by esau-morais** [comment]
@H0nzik1, to set your own shortcut, you just need to open the settings and scroll down till find an option called "Assistant Hotkey" and it'll listen to your keyboard

Note: Of course, it'll not work just typing the F5, once almost every single computer has this hotkey already "busy", so try Alt + F5 or another alternative

**Comment by esau-morais** [comment]
Duplicated of #142

**Comment by H0nzik1** [comment]
I dont have option called "Assistant Hotkey". I have installed Google_Assistant-Setup-1.0.0-rc.2.exe which is lates I found on github and options I see in settings are following:
Key File Path
Saved Tokens Path
Language
Force New Conversation
Enable Audio Output
Enable microphone on Continous Conversation
Enable microphone on application startup
Start as Maximized
Enable Auto Scaling
Windows Float Behavior
Enable ping feedback sound for microphone
Launch At Startup
Always Close to Tray
Theme
Configure Hotkey Behavior
Relaunch Assistant
Quit from Tray
Show Developer Tools
Application Data Directory
Show Command Line Arguments
About Assistant

**No option called "Assistant Hotkey" between them**

**Comment by esau-morais** [comment]
> I dont have option called "Assistant Hotkey". I have installed Google_Assistant-Setup-1.0.0-rc.2.exe which is lates I found on github and options I see in settings are following:
> Key File Path
> Saved Tokens Path
> Language
> Force New Conversation
> Enable Audio Output
> Enable microphone on Continous Conversation
> Enable microphone on application startup
> Start as Maximized
> Enable Auto Scaling
> Windows Float Behavior
> Enable ping feedback sound for microphone
> Launch At Startup
> Always Close to Tray
> Theme
> Configure Hotkey Behavior
> Relaunch Assistant
> Quit from Tray
> Show Developer Tools
> Application Data Directory
> Show Command Line Arguments
> About Assistant
> 
> **No option called "Assistant Hotkey" between them**

> This feature has already been implemented in the source just not available yet. Till then you can clone this repo and build this project on your own if you want to test...

**Comment by Juka117** [comment]
@H0nzik1 kindly close issue and wait for next release to find the feature in the settings like @esau-morais mentioned.

**Comment by BothSamuel** [comment]
While waiting for deployment an option is to use the Microsoft Power Toys keyboard manager to assign a custom shortcut.
![image](https://user-images.githubusercontent.com/47579807/108630706-c7d56980-742b-11eb-90f8-c00e129a9c90.png)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
