### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by ludvigng** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#148]
After closing the app to tray (just pressing X on the assistant window), looking at the cpu usage, the app seems to pretty high, while also keeping pulseaudio running. This almost halves my battery life, which is unfortunate.

**To Reproduce**
Just starting the app to tray and checking top or htop will show the usage. It'll peak higher around start and then settle around these numbers after a minute.

**Expected behavior**
Given that the app currently doesn't do hotword recognition, I dunno why it's keeping pulseaudio that high.

**Screenshots**
![Skärmbild från 2021-02-18 13-15-45](https://user-images.githubusercontent.com/50339757/108355690-72127e80-71eb-11eb-9523-e175d1c34e28.png)

**Desktop:**
 - OS: Ubuntu 20.10
 - Version: 1.0.0-rc.2, installed from snap

**Additional context**
I dunno if it might be linked to #79 and if so it might already be fixed.

**Comment by Melvin-Abraham** [comment]
@ludvigng This issue is indeed linked to #79.

> One of the main issues which is currently fixed (but not released yet) was the constant use of microphone even when application is idle (see #30). This was in turn caused since old instances of microphone object were not reused/disposed and new instances were created instead

**Comment by ludvigng** [comment]
> @ludvigng This issue is indeed linked to #79.
> 
> > One of the main issues which is currently fixed (but not released yet) was the constant use of microphone even when application is idle (see #30). This was in turn caused since old instances of microphone object were not reused/disposed and new instances were created instead

Glad to hear it, thanks for the quick reply! I'll close this then. :)
