### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by saadasoccer** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#151]
i'm obviously very new at this.
Downloaded unzipped and tried to run the app. 

Script:

Line: 1
Char:1
Error syntax error
Code 8A03EA
Source: Microsoft Jscript compilation error

**Comment by Melvin-Abraham** [comment]
@saadasoccer You are running Nodejs code on Microsoft Jscript. You must instead download node and run the script via `npm start`.

_Closing this issue_

**Comment by saadasoccer** [comment]
Thank you
