### ISSUE TITLE
'No Suggestions' text is not translated

### ISSUE THREAD

**Issue by LuanRoger** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#155]
The phrase 'No Suggestions' was not translated into the language I am using (Portuguese - Brazil) and I think it was not translated into other languages either.

![NoSuggestions](https://user-images.githubusercontent.com/46284513/108546933-985a1c00-72c8-11eb-9a16-261b4635a117.png)

To reproduce, just do random searches. 😄 

 - OS: Windows 10 20H2
 - Version: 1.0.0-rc.2

**Comment by kbdharun** [comment]
I think this might be a bug in the Client, When I search for something using the client, I too get  **No suggestions** as Marked in your Issue, I hope @Melvin-Abraham Could Fix this No suggestions through an Update to the Client. 

> The phrase 'No Suggestions' was not translated into the language I am using (Portuguese - Brazil) and I think it was not translated into other languages either.
> 
> ![NoSuggestions](https://user-images.githubusercontent.com/46284513/108546933-985a1c00-72c8-11eb-9a16-261b4635a117.png)
> 
> To reproduce, just do random searches. 😄
> 
> * OS: Windows 10 20H2
> * Version: 1.0.0-rc.2

**Comment by LinqLover** [comment]
Same issue here. Settings page is not translated either. I even restarted the assistant ...

**Comment by esau-morais** [comment]
@Melvin-Abraham, I was looking at the `main.js` file, and just got to see that [this line](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/app/src/main.js#L3146) doesn't have its own translation to the supported languages at the `lang.js` file.

If there's any help needed, I'll be glad 🤗

**Comment by esau-morais** [comment]
> Same issue here. Settings page is not translated either. I even restarted the assistant ...

Do you still face this issue? If yes, I'd recommend you to give more information, creating a new issue as a bug report?

**Comment by Melvin-Abraham** [comment]
> @Melvin-Abraham, I was looking at the `main.js` file, and just got to see that [this line](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/app/src/main.js#L3146) doesn't have its own translation to the supported languages at the `lang.js` file.
> 
> If there's any help needed, I'll be glad 🤗

You are welcome to contribute 😊. A `noSuggestionText` key could be added for each language in the "lang.js" file. That should do the job...

**Comment by esau-morais** [comment]
I already finish this one 😄

**Comment by esau-morais** [comment]
Just got to see that it isn't missing just the `No suggestions.`, but also the entire settings. So, if you allow me to fix it, I'll be glad to 🤗

**Comment by Melvin-Abraham** [comment]
@esau-morais The current way of handling i18n for the entire app would be messy as all the translations will be stuffed in a single file making it difficult to work with. I am planning to clean that up first and then work on extended internationalization...

**Comment by esau-morais** [comment]
Got it. I'll send the changes, making a pull request, so the issue can be closed

**Comment by itamar-mizrahi** [comment]
why do i get key:'card_hide' in the console, while searching for photos. It give me no suggestions m. Also can i change premmisionsto show my own photos, and if so where i suppose to do it
