### ISSUE TITLE
Big Sur can't shutdown with Google Assistant open.

### ISSUE THREAD

**Issue by jaydengamble6** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#158]
**Describe the bug**
When I go to shutdown or restart my MacBook it just wont shut down until I quit Google Assistant.

**To Reproduce**
1. Attempt to shutdown.
2. See that it wont shut down.

**Expected behavior**
To shutdown and Google Assistant quits.

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur 11.3 Beta]
 - Version [1.0.0-rc.2]

**Comment by Melvin-Abraham** [comment]
@jaydengamble6 Thank you for reporting this issue 👋. This will be fixed soon...
