### ISSUE TITLE
No Mic Input, nor output via text input

### ISSUE THREAD

**Issue by elokea** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#159]
Hi !

I tried to use GAssistant (v1.0 rc2), but the mic button just does nothing but the ping sound. And when I use the textbox, there is no output.
![%pn_20-02-21_16-52-49](https://user-images.githubusercontent.com/55319385/108601348-6d40fc80-739c-11eb-9d01-f513998f9c4f.gif)

I verified everything, app settings, confidentiality settings on W10, default mic, but everything is fine.
![Google_Assistant_20-02-21_16-56-03](https://user-images.githubusercontent.com/55319385/108601378-8e095200-739c-11eb-9e05-6e03aaade520.png)

Could someone help me please ?

**Comment by tinbolw** [comment]
I had the same issue as you, what I did to fix this was I opened the console and typed in a command. In my case it gave me an error saying that I had not enabled the google assistant API. If that's the case for you as well, it should also provide a link that you can go to to enable the API and hopefully get it working for you.
