### ISSUE TITLE
does not open the browser for the verification 

### ISSUE THREAD

**Issue by Aryan123-de** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#163]
after installing it and doing google cloud stufs .At the pointing of pasting the code it  not opening the browser.MY VERFICATION IS INCOMPLETE

**Comment by esau-morais** [comment]
Did you provide in the settings the token?

**Comment by allysa08** [comment]
not yet 😭 i think. dis is type of syntax error u think

**Comment by Melvin-Abraham** [comment]
@allysa08 Can you open the DevTools (via `Ctrl + Shift + I`), switch to "Console" tab and share the error logs if there are any?

**Comment by Zarvis12** [comment]
Restart or Signout the PC. It worked for me

**Comment by diskreet90** [comment]
Hey there, I'm getting the same issue, here's the log from console:

`main.js:3460 THEME: dark dark-theme
main.js:3860 RELEASES: Array(3)
main.js:3868 No updates avaiable
C:\Program Files\Google Assistant\resources\app.asar\node_modules\google-assistant\components\auth.js:48 Opening OAuth URL. Return here with your code.
events.js:200 Uncaught Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:81)
errnoException @ internal/errors.js:474
ChildProcess._handle.onexit @ internal/child_process.js:264
onErrorNT @ internal/child_process.js:456
processTicksAndRejections @ internal/process/task_queues.js:81
main.js:3564 Getting Changelog for "v1.0.0-rc.2"
main.js:3460 THEME: dark dark-theme
main.js:918 Updated Config
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Google%20Assistant/resources/app.asar/app/src/uri.all.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/Google%20Assistant/resources/app.asar/app/src/performance-now.js.map: 
`

**Comment by NoobCDguy** [comment]
I'm still getting this problem and I've restarted 3 times and still no browser opens up
![Screenshot 2021-04-05 155849](https://user-images.githubusercontent.com/81960487/113564993-e84a3380-9627-11eb-83e2-a4b360904cfa.jpg)

**Comment by Melvin-Abraham** [comment]
This issue will be tracked in #267.
_Closing the issue_
