### ISSUE TITLE
Google assistant windows failed to initiate after processing.

### ISSUE THREAD

**Issue by dacot9** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#164]
everything went well just when i was processing microphone it shutdown.

**Comment by esau-morais** [comment]
Could you please give more information and a screenshot, if it is possible?

**Comment by kbdharun** [comment]
> Everything went well just when I was processing the microphone it shutdown.

I think it might be minimized to your system tray in the taskbar if you are using Windows, can you please give further information regarding the issue, like @esau-morais told can you enclose a Screenshot @dacot9.

Hope this helps,
**Regards 
K.B.Dharun Krishna** 
`Windows Geek`

Please Provide Further Information regarding your Operating System.

**Comment by dacot9** [comment]
yea. Its not the matter of enabling speech recognition i was in the  process of toggling microphone ON it close down.  
![Screenshot 2021-02-22 003321](https://user-images.githubusercontent.com/79419083/108730241-568fd680-7551-11eb-8a25-8b08c53584ef.jpg)

**Comment by dacot9** [comment]
> Could you please give more information and a screenshot, if it is possible?



> Could you please give more information and a screenshot, if it is possible?

![Screenshot 2021-02-22 003321](https://user-images.githubusercontent.com/79419083/108730475-948cfa80-7551-11eb-9c76-ad5b187fcc3d.jpg)

**Comment by dacot9** [comment]
> > Everything went well just when I was processing the microphone it shutdown.
> 
> I think it might be minimized to your system tray in the taskbar if you are using Windows, Can you please give further information regarding the issue, like @esau-morais told can you enclose a Screenshot @dacot9.
> 
> Hope this helps,
> **Regards K.B.Dharun Krishna**
> `Windows Geek`
> 
> Please Provide Further Information regarding your Operating System(Version, Build Number)
 

sometimes these issues occurs due to windows virus & threat protections . I already updated the files to whitelist

**Comment by kbdharun** [comment]
> > > Everything went well just when I was processing the microphone it shutdown.
> > 
> > 
> > I think it might be minimized to your system tray in the taskbar if you are using Windows, Can you please give further information regarding the issue, like @esau-morais told can you enclose a Screenshot @dacot9.
> > Hope this helps,
> > **Regards K.B.Dharun Krishna**
> > `Windows Geek`
> > Please Provide Further Information regarding your Operating System(Version, Build Number)
> 
> sometimes these issues occur due to windows virus & threat protection. I already updated the files to whitelist

I would suggest You clean Uninstall the App and delete the Program Files and Reinstall the Program.
If you mention your Windows Version and Build Number I could help you troubleshoot the issue.

Regards,
K.B.Dharun Krishna

**Comment by dacot9** [comment]
> > > > Everything went well just when I was processing the microphone it shutdown.
> > > 
> > > 
> > > I think it might be minimized to your system tray in the taskbar if you are using Windows, Can you please give further information regarding the issue, like @esau-morais told can you enclose a Screenshot @dacot9.
> > > Hope this helps,
> > > **Regards K.B.Dharun Krishna**
> > > `Windows Geek`
> > > Please Provide Further Information regarding your Operating System(Version, Build Number)
> > 
> > 
> > sometimes these issues occur due to windows virus & threat protection. I already updated the files to whitelist
> 
> **I would suggest You clean Install the Client Again**
> _First, Uninstall it and delete the Program Files and then Reinstall the Client and reconfigure it._
> 
> Mostly, This might Fix the Issue, If you are still facing this issue due to Windows Virus & Threat Protection then I suggest you to
> Troubleshoot the Program Compatibility with your version or Build of Windows.
> 
> _**Suggestion 1:**_ _Locating the ShortcutFile Manually and then fixing the Compatibility Issue_
> 
> **Step 1:** Locate the Main Shortcut File of Program usually in this location `C:\Users\YOURUSERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs` but you might have saved it in a Different Location anyways locate the main shortcut.
> 
> **Step 2:** Now Right-click and click on Troubleshoot Compatibility Follow the Steps.
> 
> This should fix the issue if you couldn't find the Main Shortcut file of the client then Follow the Next Suggestion
> 
> **_Suggestion 2:_** _Running Windows Program Compatibility Troubleshooter_
> 
> **Step 1:** Go to Settings
> 
> **Step 2:** Go to Update and Security
> 
> **Step 3:** Now click on 🔧Troubleshoot
> 
> **Step 4:** Click on Additional Troubleshooters
> 
> **Step 5:** Click on Program Compatibility Troubleshooter
> 
> **Step 6:** Now Move through the List and Click on Google Assistant, Now run the Troubleshooter.
> 
> If the Above Suggestions fix your issue then you are good to go if not then feel free to comment back on the issue here, If you still have the problem then please mention your Version of Windows and Build Number of Windows.It would help me to assist you in troubleshooting the issue.
> 
> Regards,
> K.B.Dharun Krishna
> `Windows Geek`

![Screenshot 2021-02-23 140720](https://user-images.githubusercontent.com/79419083/108819211-918d1b00-75e0-11eb-8094-ba5cabb47c61.jpg)

**Comment by Melvin-Abraham** [comment]
@dacot9 Can you also open the DevTools (via `Ctrl + Shift + I`) and send the error logs here so that we can investigate the issue...

**Comment by dacot9** [comment]
> @dacot9 Can you also open the DevTools (via `Ctrl + Shift + I`) and send the error logs here so that we can investigate the issue if you didn't uninstall...

i was re installing with previous token given. solved!
![Screenshot 2021-02-23 141236](https://user-images.githubusercontent.com/79419083/108820279-f85f0400-75e1-11eb-8583-1ead0d6a0703.jpg)

**Comment by kbdharun** [comment]
> > @dacot9 Can you also open the DevTools (via `Ctrl + Shift + I`) and send the error logs here so that we can investigate the issue if you didn't uninstall...
> 
> I was reinstalling with the previous token given. solved!
> ![Screenshot 2021-02-23 141236](https://user-images.githubusercontent.com/79419083/108820279-f85f0400-75e1-11eb-8583-1ead0d6a0703.jpg)

_I am Glad The Issue Was Solved_, **If you could Find the Reason why this Issue was there please share it with @Melvin-Abraham.** 

**Regards, 
K.B.Dharun Krishna**
`Windows Geek`
