### ISSUE TITLE
stuck here

### ISSUE THREAD

**Issue by fahimsadik** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#165]
[

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by esau-morais** [comment]
Could you please give more information and also how to reproduce the issue?

**Comment by Melvin-Abraham** [comment]
This is a duplicate of issue #39.

This should help:

> Fixed in dd67747. Since, this fix will not be readily available until next release ... you can _temporarily_ disable **Settings** > **Conversation** > **Enable microphone on application startup**

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/39#issuecomment-734111970

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
