### ISSUE TITLE
Slow/No results

### ISSUE THREAD

**Issue by Luan-Snyman** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#168]
Firstly, this is a great tool, and I love it.

However, there are moments when the assistant seems to stop working completely and does not show or result in any response.

![Screenshot 2021-02-22 100009](https://user-images.githubusercontent.com/64130185/108679158-c9b72f80-74f4-11eb-9316-33c94375e375.png)
![Screenshot 2021-02-22 095749](https://user-images.githubusercontent.com/64130185/108679160-cae85c80-74f4-11eb-9de7-d1049cced5ee.png)

My download speeds and network don't seem ot be the issue, but I nonetheless checked them:
Upload: ~15Mbps
Download: ~20Mbps

I was wondering if the location of the Saved Tokens and Key File might slow down the reponses?

 - OS: Windows 10 64bit
 - Version 20H2 (OS build 19042.804)

Thanks a mil!

**Comment by konnahemant** [comment]
Have same issue need a resolution!

**Comment by Melvin-Abraham** [comment]
@Luan-Snyman @konnahemant The fix of this issue is similar to #58. Let me know if the following works:

> You can fix this by deleting the tokens file that was fetched by the application (as per the "Saved Tokens Path") and relaunch the assistant. You will again be presented with "Get Token!" screen. Authenticate your Gmail account again and let it fetch the tokens. This should possibly fix the issue...

**Ref:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/58#issuecomment-753742483

**Comment by esau-morais** [comment]
@Melvin-Abraham, I tested it and it still not working. Actually, the assistant gives the number of the notes but doesn't show it

**Comment by Melvin-Abraham** [comment]
@esau-morais That is related to rendering issues _(causing to show up a blank screen without any content)_ which will be addressed sometime later on. However, I am not sure if @Luan-Snyman is referring to that or a blank screen with Google Assistant logo _(which could be fixed as per the comment I previously mentioned)_.

**PS:** The notes do not seem to show up on the screen but is rendered off-screen (disable **Settings** > **Window** > **Enable Auto Scaling** and check it out)

**Comment by Luan-Snyman** [comment]
@Melvin-Abraham I have managed to fix it, but only briefly.
I disabled the 'start miscrophone on startup' and reenabled it afterwards, to get the error code to go away, and to bring up the 'enter key/auth code' screen.

Once I did that, the slow responses was fixed for some time, but now again it's relatively slow.

I'll try again in a little while and will feed back on the progress.

Thanks again

**Comment by esau-morais** [comment]
> @esau-morais That is related to rendering issues _(causing to show up a blank screen without any content)_ which will be addressed sometime later on. However, I am not sure if @Luan-Snyman is referring to that or a blank screen with Google Assistant logo _(which could be fixed as per the comment I previously mentioned)_.
> 
> **PS:** The notes do not seem to show up on the screen but is rendered off-screen (disable **Settings** > **Window** > **Enable Auto Scaling** and check it out)

Got it. After seeing that the option "Enable Auto Scaling" was enabled, I turned it off and the notes started were shown, but with a position error (related to #167)

**Comment by Luan-Snyman** [comment]
@Melvin-Abraham would it be fair to close this thread for 'slow/no results'?
@esau-morais @konnahemant

**Comment by Luan-Snyman** [comment]
As a note:
Deleting the tokens file and re-authorising the app was a proper solution - responses are proper fast now.
Thanks

**Comment by esau-morais** [comment]
> @Melvin-Abraham would it be fair to close this thread for 'slow/no results'?
> @esau-morais @konnahemant

Probably yes. The new issue now is related to the #167

**Comment by Luan-Snyman** [comment]
Final note again:

**As a note:
Deleting the tokens file and re-authorising the app was a proper solution - responses are proper fast now.
Thanks**

Thanks again @Melvin-Abraham , I really love your work one this!

Will be watching this space :D
