### ISSUE TITLE
🐛[BUG](Styling): Button padding stop working when loading the token

### ISSUE THREAD

**Issue by esau-morais** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#169]
**Describe the bug**
Basically, when I try to reset the tokens (#58), the left-bottom buttons padding stop working.

![left-bottom buttons](https://user-images.githubusercontent.com/55207584/108699249-c36c8780-74e3-11eb-8f02-6a82cc2b2d3b.png)

**To Reproduce**
1. Remove the `tokens` file 
2. Relaunch the Google Assistant
3. Copy the new token
4. Wait to load
5. See that the buttons at the left-bottom padding are not working

**Expected behavior**
Persist the padding of the button.

**Screenshots**
![left-bottom buttons](https://user-images.githubusercontent.com/55207584/108699249-c36c8780-74e3-11eb-8f02-6a82cc2b2d3b.png)

**Desktop (please complete the following information):**
 - Windows 10 Build 1909
 - Version 1909

**Comment by esau-morais** [comment]
### 💡 Possible solutions

This can be happening because of the new element at the DOM that was created (progress bar). What I could recommend is to define a fixed width.

**Comment by Melvin-Abraham** [comment]
@esau-morais This is because the "disable" class applied to the button (while fetching tokens) force a fixed padding. This would be fixed soon

**Comment by esau-morais** [comment]
Thank you! If there's any help needed, I'll be glad to 🤗

**Comment by esau-morais** [comment]
As the issue is related to design, it'd be great to improve the accessibility, once the `tab` shortcut is fired, it doesn't have a specific styling to the elements that are, specifically, actionable.

**Comment by Melvin-Abraham** [comment]
> As the issue is related to design, it'd be great to improve the accessibility, once the `tab` shortcut is fired, it doesn't have a specific styling to the elements that are, specifically, actionable (such as buttons, select, and suggestion elements)

That is definitely in the roadmap 👍
