### ISSUE TITLE
Don't speak answer when question was typed instead of spoken

### ISSUE THREAD

**Issue by LinqLover** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#174]
It's cool to use GA as some kind of terminal input. This flow should not be interrupted by a voice saying something when I typed the question.

**Comment by noahjsmyth** [comment]
easily solved by just muting the audio for the app?

**Comment by LinqLover** [comment]
@noahjsmyth That's not an option, when I speak to the assistant it actually should answer. But only then :-)

**Comment by luximus-hunter** [comment]
That should be fixable by checking for typing instead of speaking, and responding accordingly

**Comment by LinqLover** [comment]
Exactly. It might become a bit more complicated when keyboard + voice input are mixed, for instance, when the user responds to a further request of the assistant, but for the beginning, this should be the right strategy.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
