### ISSUE TITLE
'You are offline' when I am not

### ISSUE THREAD

**Issue by Hood-Legend** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#176]
**Describe the bug**
'You are offline'
'Error: Getting metadata from plugin failed with error: invalid_grant'
It says that I am offline while I am having a steady net connection

**To Reproduce**
1. Win+Shift+A
2. Ask any query 
3. See error

**Expected behavior**
I expected it to answer my query, now it is giving the same error every time
 
**Desktop (please complete the following information):**
 - Windows 10 Home Build 20H2
- Latest release(of Assisstant) being used
**Additional context**
![image](https://user-images.githubusercontent.com/78639881/108816533-58eb4280-75dc-11eb-884d-125a3a436f34.png)
![image](https://user-images.githubusercontent.com/78639881/108816968-25f57e80-75dd-11eb-9f2c-51bd20da0507.png)

**Comment by jed84** [comment]
Same issue here.

**Comment by Melvin-Abraham** [comment]
Please refer [this](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error) FAQ section for help.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
