### ISSUE TITLE
[Suggestion](Docs): Improve open-source guidelines

### ISSUE THREAD

**Issue by esau-morais** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#177]
### Context

Once Google Assistant Unofficial Desktop Client is an open-source project, it is essential to enforce that **anybody** (considering a minimum of knowledge about programming) is free to use, study and modify this project, helping it to improve more and more.

### 💡 Suggestion

So, I think it'd be great to adopt not just a contributing file, but also start to engage the community and show that this project follows some guidelines and rules with and code of conduct. Also, a place to discuss more features requests would work with the new GitHub discussions

### Resources

* A project with the [most important docs](https://github.com/Edite-App/.github) to an open-source project.

* An example of [GitHub Discussions](https://github.com/Edite-App/Edite/discussions) usage on real-world project

**Comment by esau-morais** [comment]
If there's any way I can help to improve the documentation, helping developers and users, I'd be pleased to 🤗

**Comment by Melvin-Abraham** [comment]
@esau-morais That would be great 👍. If there's any ideas about the content or implementation, please share it here... 😊

**Comment by esau-morais** [comment]
So, I shared some resources above and I'd like to know what you think about adopting as a template and/or making some necessary changes. Also, I'm thinking in some way to take the users' attention and incentive to read the docs, once there are a lot of duplicated issues and it is kinda disturbing.

**Comment by esau-morais** [comment]
I forgot to mention that would be heavily recommended to have code/linting and commit patterns to be followed by the developers/contributors. Some of my favorites are Prettier, ESLint, and sometimes GitHub Actions can help too.

**Comment by Melvin-Abraham** [comment]
> I shared some resources above and I'd like to know what you think about adopting as a template and/or making some necessary changes.

The `CODE_OF_CONDUCT` template could be directly ported without much changes unless you want to add more content. The `CONTRIBUTING` template also seems pretty good. We could add "How to build" and "Coding Styles" section into that. Later on when we refactor the codebase and divide them into multiple components, we could explain what each of the directories contain.

> Also, I'm thinking in some way to take the users' attention and incentive to read the docs or create a workflow using the [GitHub Actions](https://github.com/sdras/awesome-actions) to identify and verify issues, once there are a lot of duplicated issues and it is kinda disturbing.

I think that would be of great help. I am kinda new to GitHub Actions but I'll give it a try...

**Comment by esau-morais** [comment]
Thank you for taking a look at the resources 🙏 

About the GitHub Actions: They are just a YML file that needs to be created inside a `.github/workflows/` folder on your project. As you can see from the link above, they are in the GitHub Marketplace, ready to be added into the repository, but we can also create by our own

**Comment by esau-morais** [comment]
*Closing as solved*
