### ISSUE TITLE
Signing in as a user

### ISSUE THREAD

**Issue by vestimir** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#18]
**Is your feature request related to a problem? Please describe.**
For certain uses Google Assistant requires a signed-in user. Setting the default temperature unit to Celsius is one such example. 

**Describe the solution you'd like**
Provide an interface to connect your Google Account. 

**Describe alternatives you've considered**
- 

**Additional context**
<img width="802" alt="Screenshot 2020-10-14 at 12 23 27" src="https://user-images.githubusercontent.com/356117/95969959-1177cd00-0e18-11eb-9200-f42ce76bbbe6.png">

**Comment by Melvin-Abraham** [comment]
@vestimir I don't think Google Assistant SDK provides any feature for signing in as a Google User like in the official Google Assistant app as it is not intended for that purpose. Also, I tried running the same command and it seems to be working fine for me without any need to do that from my phone.

![image](https://user-images.githubusercontent.com/26056183/96085567-9cbb9600-0ede-11eb-8b5d-9b24c90c3c2c.png)

Can you try again?

**Comment by Melvin-Abraham** [comment]
Closing as stale...
