### ISSUE TITLE
Linux: not getting the assistant to run properly

### ISSUE THREAD

**Issue by neo774** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#181]
Hey,
first of all: great project!

I wanted to run the assistant under a Linuxmint 20.1 environment but couldn't get it to work.
I installed g-assist via snap (https://snapcraft.io/install/g-assist/mint) and followed the setup for the Google authentication
(https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client).
The Problem: When I launch the client and click on the settings button on the top left corner nothing happens. Therefore I can't complete authentification. When I first started g-assist from the console I got the following warnings:
```
:~$ g-assist
Gtk-Message: 11:34:26.502: Failed to load module "xapp-gtk3-module"
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
(node:19253) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.g-assist/.org.chromium.Chromium.ayD9Dj'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:19342) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.g-assist/.org.chromium.Chromium.ajUel1'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:19514) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.g-assist/.org.chromium.Chromium.9iQ81h'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:20099) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.g-assist/.org.chromium.Chromium.3Z1Z8b'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```
Does anyone know how to solve this?

**Comment by esau-morais** [comment]
Did you click the "Get started" button first?

**Comment by neo774** [comment]
No, thank you for your hint! This totally solved the problem!

**Comment by esau-morais** [comment]
@neo774, just got to see that you reopened the issue. Is there anything else not working?

**Comment by Melvin-Abraham** [comment]
@neo774 Did that solve your issue?

**Comment by esau-morais** [comment]
> @neo774 Did that solve your issue?

> This totally solved the problem!

I think it did

**Comment by Melvin-Abraham** [comment]
Ok. I'll close this issue as resolved then...

**Comment by neo774** [comment]
Hey, this was exactly the problem. In the wiki for authentication it wasn't describe as there is probably assumed you already got beyond this point.
(Also I didn't restart my system after installation, so I had to start the client from the console - maybe there could be left hint for either restarting or accessing from terminal)
