### ISSUE TITLE
Was working fine until this morning 

### ISSUE THREAD

**Issue by Lordgoderic** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#182]
**Describe the bug**

Trying to perform any assistant request with microphone or typing will produce
"Error: Getting metadata from plugin failed with error:invalid_grant"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Widows 10 Home
 - Version 20H2
 - OS build: 19042.804
 - Experience: Windows Feature Experience Pack 120.2212.551.0

**Comment by esau-morais** [comment]
Please, see this section at the [Frequently Asked Questions (FAQ)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error)

**Comment by esau-morais** [comment]
Duplicate of #58, plus another 6 issues similar to this

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
