### ISSUE TITLE
Google Assistant does not return any results

### ISSUE THREAD

**Issue by tinbolw** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#183]
Google Assistant does not return any results, no matter what you request. Trying to use the mic for input does not work either.

**To Reproduce**
1. Type a request in the "Ask me anything..." field
2. Press enter

**Expected behavior**
Google Assistant answering correctly.

**Screenshots**

https://user-images.githubusercontent.com/36116384/109087089-a7264180-76c1-11eb-84cf-183373627eee.mov

**Desktop:**
 - OS: macOS Big Sur 11.2.1
 - Version: 1.0.0-rc.2

**Extra Information**

I've tried both building from source and the release and both have this problem.

**Comment by esau-morais** [comment]
It seems like you are not using the correct version of the Google Assistant Unofficial Version, once the actual one is 1.0.0-rc.2

I'd recommend you to see I'm the About section at the Settings and try to check if there's an update button (it should be there)

**Comment by tinbolw** [comment]
My mistake- The version that I am using currently _is_ 1.0.0-rc.2, I just assumed it was 1.0.0-rc.1 since that was the one in the example.

**Comment by esau-morais** [comment]
It looks like this issue is slightly related to the #159, but still without any suggestions of what could be.

Could you open the inspector, using `Ctrl+Shit+I` or `F12`, and see if there's any error in the console when you try to click the button or type something?

**Comment by tinbolw** [comment]
I opened the console and typed in a command to test it and apparently I had not enabled the Google Assistant API so I did that and its working now. Thanks!
