### ISSUE TITLE
Not accepting auth success code

### ISSUE THREAD

**Issue by code-lokesh2008** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#185]
So, this month(February)I found out about this app and was ready to get it up and running. It worked perfectly, until last week, when I was going to ask for the weather. It just said, that it was not getting internet, when I clearly checked my WiFi and my PC for this problem. I tried doing the steps again, the Actions Console and the Google Cloud, but it just does not accept the WiFi. Just 10 mins before, I tried again, and it was going up till auth level, but it was not accepting the code. It showed a popup to restart the app or ignore it. Can you check this bug?

**Comment by rbrouwer** [comment]
If you're getting: "Error: Getting metadata from plugin failed with error: invalid_grant" then duplicate of
#58, #71, #154, #156, #160, #162, #166, #176 and #179.

**Comment by esau-morais** [comment]
It'd be great to provide a screenshot

**Comment by code-lokesh2008** [comment]
But, the problem here is that I started a new project, the exact way I started my first one on 13 Jan, I think, but it does NOT accept my code. I will give a pic of the problem later

**Comment by code-lokesh2008** [comment]
> If you're getting: "Error: Getting metadata from plugin failed with error: invalid_grant" then duplicate of
> #58, #71, #154, #156, #160, #162, #166, #176 and #179.

I am getting that if I use my old client secret.json

**Comment by code-lokesh2008** [comment]
I would like @Melvin-Abraham or the developer of the app to check this problem, coz I want Google Assistant to work on my PC

**Comment by code-lokesh2008** [comment]
It shows this
![image](https://user-images.githubusercontent.com/76845820/109420191-1f10a680-79f7-11eb-81a4-c8a0be5cf20e.png)
It does nothing, just shows the same error if I hit restart
But, if I hit ignore, it does show the code screen but doesn't accept it.
I will try to add a video clip.

**Comment by code-lokesh2008** [comment]
https://user-images.githubusercontent.com/76845820/109420946-318cdf00-79fb-11eb-84c9-6cc536f22bb9.mp4

This is the greatest bug problem.

**Comment by code-lokesh2008** [comment]
That was with the new project.
The old one only responded like this:
Error: Getting metadata from plugin failed with error: invalid_grant
And the second project, aka the solver, I thought, just failed.

**Comment by Melvin-Abraham** [comment]
@code-lokesh2008 Refer to [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) of the FAQ to resolve your issue

**Comment by code-lokesh2008** [comment]
Thanks, @Melvin-Abraham! I will try it and say if it worked!
:)

**Comment by code-lokesh2008** [comment]
Nope :(
I changed it from my system folder(C:\) to my being-used drive(D:\) and it cancelled there too!

**Comment by code-lokesh2008** [comment]
should I clear the tokens.json file?

**Comment by code-lokesh2008** [comment]
Sorry, @Melvin-Abraham, I did a mistake.
A few weeks ago, I enabled the enable mic on startup and this was the cause of the problem.


> @code-lokesh2008 Refer to [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) of the FAQ to resolve your issue

Thanks a lot for that message, I didn't read it properly!
