### ISSUE TITLE
[Question] Does doing this break Google's ToS?

### ISSUE THREAD

**Issue by NovaViper** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#186]
Hi, I want to really try and set this up on my laptop. However, I found this method from [this article](https://9to5google.com/2021/02/16/hands-on-with-the-unofficial-google-assistant-desktop-client-video/).. but it states that you could lose your Google Account by doing this. Is this true? And why would it break ToS?

**Comment by HBoardman** [comment]
Would also like to know this.

**Comment by esau-morais** [comment]
I think it could be a great question to be discussed in the new Google-Assistant-Unofficial-Desktop-Client repository Discussions. To get started, go to the Discussions tab:

![Discussions](https://user-images.githubusercontent.com/55207584/109345817-7a079980-784f-11eb-91a9-6f36c3ec5113.png)

**Comment by esau-morais** [comment]
As you've added this to the repository Discussions, I think it's better to close this
