### ISSUE TITLE
[Requests] Being able to change used microphone, allow hey google / ok google, to detect your voice.

### ISSUE THREAD

**Issue by The-Red-Eye-Studio** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#188]

**Comment by rbrouwer** [comment]
Being able to change used microphone is available in source code. Just not in latest release-build.
#61 already requests "hey google"/"ok google".

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
