### ISSUE TITLE
JavaScript error at launch

### ISSUE THREAD

**Issue by BootVirtual** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#189]
I just did a fresh install of the assistant version 1.0.0-rc2 on Windows 10 build 20H2 and I'm getting this JavaScript error at launch.

![image](https://user-images.githubusercontent.com/64020530/109292025-6dc11380-7832-11eb-83db-297ec3a0aae9.png)

I tried launching with administrator permission and also reinstalling to the default directory but it still doesn't work. Could you please see what's going on? Thanks!

**Comment by esau-morais** [comment]
Please take a look at the [Frequently Asked Questions (FAQ)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0)

**Comment by esau-morais** [comment]
Duplicate

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
