### ISSUE TITLE
Typo in empty saved tokens path dialog

### ISSUE THREAD

**Issue by OrangeTurtle197** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#193]
**Describe the bug**
A typo in the 'saved tokens path is empty' dialog (loaction)

**To Reproduce**
1. Create a key file and insert it into the app's settings
2. Make sure the saved tokens path field is empty
3. Click Save
4. See the typo

**Screenshots**
https://i.imgur.com/Ad9lDwb.png

**Desktop (please complete the following information):**
 - OS: Windows 10 version 21H1 (19043.844)
 - Version: 1.0.0-rc.2 (from installer)

**Comment by esau-morais** [comment]
Thank you for reporting this typo! See [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/app/src/main.js#L2529) line of the code that this typo is located.

**Comment by esau-morais** [comment]
Also, there's a typo in the settings option called Enable microphone on **Continous** Conversation. It should be "Continuous"

![Enable microphone on Continous Conversation](https://user-images.githubusercontent.com/55207584/109371095-029f2d80-7882-11eb-92fe-04b0e081f7e4.png)

**Comment by esau-morais** [comment]
Just got to remember that the options group ACCESSIBILITY is written wrong:

![ACCESSIBILTY ](https://user-images.githubusercontent.com/55207584/110328390-107b4e00-7ffa-11eb-88cb-8196c53c3981.png)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
