### ISSUE TITLE
Enhancement: Option to disable notification on boot

### ISSUE THREAD

**Issue by VarunS2002** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#195]
- When start at boot is enabled, the app gives a toast notification on Windows saying "Google Assistant is running in background!" with the registered hotkey
- I suggest adding a setting toggle to disable this notification
- Add the condition on Line 208 in app.js

**Comment by esau-morais** [comment]
I think this is actually a great idea. Sometimes notifications can be annoying, mainly on Windows 😅

I'll give it a try and work on this.
