### ISSUE TITLE
'Close when not in focus' causes loop when trying to enter token

### ISSUE THREAD

**Issue by SpoiledSoul** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#199]
**Describe the bug**
When the token file is deleted and G.A. asks for a new token, the window closes after opening the browser if the user had previously enabled 'close when not in focus' (or similar phrasing).

**To Reproduce**
1. Set up G.A.
2. In settings, toggle 'close when not in focus' **on**
3. Delete tokens file
4. Attempt to reopen G.A.

**Expected behavior**
When asking for token, G.A. should remain on top until the token has been entered or user manually closes.

**Screenshots**
![Screenshot 2021-02-22 123258](https://user-images.githubusercontent.com/15527752/109427617-26b55880-79c1-11eb-9492-8bd9ad11a76f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19042
 - Version 1.0.0-rc.2

**Additional context**
Uninstalling and reinstalling does not fix this issue.

**Comment by Melvin-Abraham** [comment]
@SpoiledSoul This issue has been fixed within the source but just not released yet (see 16a578b; pardon the incorrect commit message). For the time being you can navigate to `%appdata%\Google Assistant` in your file explorer and open `config.json` file. Find the keyname `"windowFloatBehavior"` and set it's value to `"always-on-top"` or `"normal"` for the time being. Then, reload the app and you are good to go. Let me know if that fixed your issue...

**Comment by SpoiledSoul** [comment]
Well, it sort of works, but then I encounter what might be another error...

After changing the `windowFloatBehavior` to `"always-on-top"` or `"normal"`, I am greeted with an "Unexpected Exception Occurred" error:
![Screenshot 2021-02-28 142301](https://user-images.githubusercontent.com/15527752/109430653-7bac9b00-79d0-11eb-8bee-1feef866efde.png)

Relaunching causes the same screen to appear and ignoring doesn't let me 'submit' the token.

**Comment by Melvin-Abraham** [comment]
@SpoiledSoul Refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) of the FAQ

**Comment by ArySlayer** [comment]
![Skjermbilde 2021-03-02 134442](https://user-images.githubusercontent.com/77483512/109650418-7cbf0300-7b5d-11eb-8727-460c64d826ee.png)
When i paste the code and try to click "submit" nothing happens.

**Comment by esau-morais** [comment]
> ![Skjermbilde 2021-03-02 134442](https://user-images.githubusercontent.com/77483512/109650418-7cbf0300-7b5d-11eb-8727-460c64d826ee.png)
> When i paste the code and try to click "submit" nothing happens.

Please, if this issue is not related to the actual in discussion, create a new one [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/new?assignees=&labels=&template=bug_report.md&title=)  giving more information.

**Comment by ArySlayer** [comment]
This issue is related, i went through the same things

**Comment by Melvin-Abraham** [comment]
> Refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) of the FAQ

@ArySlayer Did you check this out?

**Comment by SpoiledSoul** [comment]
> @SpoiledSoul Refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) of the FAQ

Thanks! This fixed the issue.
