### ISSUE TITLE
TTS Bug?

### ISSUE THREAD

**Issue by ItzBrunoToma** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#2]
**Describe the bug**
The Assistant randomly says "Sorry, there was a problem, please try again later."
Everything goes ok, it responds and a minute after it just says that for no reason.

**To Reproduce**
It happens time-to-time

**Expected behavior**
It shouldn't do anything because it successfully completed the task.

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: [Windows 8.1 Build 9600]
 - Version [1.0.0-rc.1]

**Additional context**
/

**Comment by Melvin-Abraham** [comment]
@ItzBrunoToma Can you send a sequence of queries to reproduce this issue. Because in my case, I don't have any such issues...

**Comment by ItzBrunoToma** [comment]
Hi! I've played around with the assistant a bit and it seems like it happens after you try and "play a game".
Here's a list of queries:
`2+2
4!
pi=
cafes nearby
what can you do?
avocado fat
avocado calories
cat
dog
lifespan
what about pug?
terrier lifespan
10/15
power of 100000000
go to google.com
sing me a song
can you dance?
can you beatbox?
how do i look?
drumroll please
compliment me
play a game
akinator
yes
akinator
yes
akinator
yes
akinator
yes
what can you do?
> wait for a minute and keep it open`

**Comment by Melvin-Abraham** [comment]
Well, still can't reproduce the issue _(even after following the sequence of queries)_. But I think that the problem might be that the microphone starts in between accidentally. Will have a look after it. 

Anyway, you can **clone** the project and **run** it with **devtools** open and state what **_"errors or logs"_** come up, so that I can figure out something...

**Comment by ItzBrunoToma** [comment]
Here's what it spits out in the console
![image](https://user-images.githubusercontent.com/42813323/78873482-3e9f8900-7a4b-11ea-8d1d-45c2b1adc143.png)

This causes it every time for me
```
play a game
> disable activated mic!
akinator
> disable activated mic!
yes
> assistant says "sorry, I don't understand"
play a game
> disable activated mic!
akinator
> disable activated mic!
yes
> assistant says "sorry, I don't understand"
play a game
> disable activated mic!
akinator
> disable activated mic!
yes
> assistant says "sorry, I don't understand"
what can you do?
```

**Comment by Melvin-Abraham** [comment]
Hey, @ItzBrunoToma. Based on the responses I see here, I think you should make sure that the option **_"Force New Conversation"_** under **"CONVERSATION"** settings is **disabled**...

**Comment by ItzBrunoToma** [comment]
I've disabled the option and started an akinator game. It worked fine but after answering all the questions it just started repeating "Sorry, there was a problem, please try again." over and over again

**Comment by Melvin-Abraham** [comment]
Ok. I will try to investigate the issue. Meanwhile, if you could help in any way, it would be appreciated... 😊

**Comment by ItzBrunoToma** [comment]
I don't know if I'll be able to help too much because you know how your code works way better than me, but try to prevent the assistant from saying that when it catches an Error: 14 UNAVAILABLE: Service unavailable, maybe display a small banner somewhere just in case

**Comment by Melvin-Abraham** [comment]
Actually, I too get the same `Error: 14 UNAVAILABLE: Service Unavailable` most of the times but I don't hear any such responses...

**Comment by ItzBrunoToma** [comment]
Yup! Seems like that fixes it for me.

**Comment by Melvin-Abraham** [comment]
I think that when a query requires _continuous conversation_, it triggers microphone multiple times. I will soon push a commit to fix this issue...

**Comment by ItzBrunoToma** [comment]
Awesome :+1:

**Comment by Melvin-Abraham** [comment]
@ItzBrunoToma I have pushed a commit, check if the problem still persists...

**Comment by Melvin-Abraham** [comment]
Closing this issue as no response on this was further received.
