### ISSUE TITLE
Add Option to Fully close on close button.

### ISSUE THREAD

**Issue by snaildos** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#20]
Not really sure if when I press the close button the application stops listening; Just want to clarify. I am pretty paranoid there is always someone listening. Just curious.

**Comment by Melvin-Abraham** [comment]
@snaildos When you close the application, it basically disables the processing of audio stream through mic even though the microphone is active. This makes sure that no audio stream is passed to the Assistant SDK whatsoever. You can clarify by checking out the source code.

If you still feel paranoid about that, don't worry, there is a setting which allows you to close the assistant immediately when you press the close button. You can toggle **Settings** > **Application** > **Always Close to Tray** if you want so.

If that helps don't forget to close this issue... 😊

**Comment by snaildos** [comment]
Thanks!
