### ISSUE TITLE
Visually Rich app support for games and animations

### ISSUE THREAD

**Issue by Devnol** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#200]
**Is your feature request related to a problem? Please describe.**
Using the Google Assistant Desktop Client, Actions that support smart display output such as games do not have that, it only has text and audio output.

**Describe the solution you'd like**
Ability for the client to operate like a smart display or like the Google Assistant mobile app, where it can display things like what I mentioned above.

**Additional context**
You can try what I mean by asking the Desktop Client to "Play Are You Feeling Lucky", play for a bit then try the same on a smart display or the mobile version of Google Assistant.

**Comment by Devnol** [comment]
I don't know how hard this would be but I'd figured I could point it out anyway.

**Comment by esau-morais** [comment]
Probably a duplicate of different versions and similar to the issue #137
