### ISSUE TITLE
Says im offline despite internet connection

### ISSUE THREAD

**Issue by EthanMac1915** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#202]
Opening the Google Assistant on my PC presents me with a "You are Offline!" message with the error message "Error: Getting Metadata from plugin failed with error: invalid_grant"

**To Reproduce**
Open with Win+Shift+A
Assistant should try listening
then default to error screen

**Screenshots**
![Screenshot 2021-03-02 103753](https://user-images.githubusercontent.com/17467585/109576284-6a37d000-7b43-11eb-958c-1d4a610677d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 21301.rs_prerelease
 - Version 1.0.0-rc.2

**Comment by esau-morais** [comment]
Please, check [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error)  at the FAQ and see if it solves your issue.

**Comment by EthanMac1915** [comment]
Fixed, Apologies for not checking this first.
