### ISSUE TITLE
no actions are done

### ISSUE THREAD

**Issue by nvsai** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#208]
![2021-03-04-15-54-24](https://user-images.githubusercontent.com/65706186/109950244-54243e00-7d02-11eb-8b0e-b4b59cd8ece5.png)
![2021-03-04-15-54-50](https://user-images.githubusercontent.com/65706186/109950251-55556b00-7d02-11eb-8c7a-bfee9bae84f1.png)
when i ask assistant something it returns voice result  ,but there is no screen result shown.
when I ask it to open youtube.com it says the opening website. but nothing is opening.

**Comment by luximus-hunter** [comment]
Are your settings in the google api set correctly?

Also, i dont know if the ability to open websites etc is implemented yet

**Comment by esau-morais** [comment]
Similar to #41 and #38

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
