### ISSUE TITLE
Error : "You are Offline!"

### ISSUE THREAD

**Issue by Etlok44** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#209]
this is the complete error:
"You are Offline!
Please check your Internet Connection...
Error: Getting metadata from plugin failed with error: invalid_grant"

two things happened between the last time everything was working correctly and today:
1-    I connected to a new internet box (I think this is rather anecdotal...)
2-    I had to reinitialise my computer's network cards because one day the wifi card was no longer recognised.
        I took two steps to fix this problem:
2.1- I reset my network cards by following this path:
       Setting > Network & Internet > Status > Network reset
       this did not solve my problem so I uninstalled and reinstalled my wifi card.
2.2- right click on the Windows button > Device manager > uninstall the wifi card > restart Windows

now my computer is working properly, I can connect to the internet with my browser but not with your assistant, even when I am connected to the internet with an RJ45 cable

I hope I have given you enough details and that this problem can be repaired.

**Screenshots**
![image](https://user-images.githubusercontent.com/80037582/109952377-0e09b300-7cdf-11eb-998f-2677cf62783b.png)

**Desktop**
Edition: Windows 10 Home
Version: 20H2
OS build: 19042.804

**Comment by rbrouwer** [comment]
Read the [FAQ](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error) or #58, #71, #154, #156, #160, #162, #166, #176 and #179.

**Comment by Etlok44** [comment]
ok but now I have a new code in my browser, but when I want to open the assistant, it opens a new google page to retrieve a code and closes instantly
maybe because I have set it to close when I select another window 
can I reinstall the software and reuse the "client_secret... .json" file?

**Comment by Etlok44** [comment]
I managed to get a new token 
thank you

**Comment by Melvin-Abraham** [comment]
> Would it be possible to automate this process

@LinqLover This has already been implemented as per ebc91efbe

**Comment by LinqLover** [comment]
@Melvin-Abraham Wo-hoo, one virtual cookie for you! 🍪 And I guess it will available through the next release? 🎉

**Comment by LinqLover** [comment]
@Melvin-Abraham Any chance for a new prerelease in near future? 😃
