### ISSUE TITLE
Unexpected Exception Occured

### ISSUE THREAD

**Issue by sepehrraisi** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#21]
I get this when I start Google Assistant on windows
Unexpected Exception Occured
An unexpected error occurred.
Error: Tried calling start() before the ready event!

**Comment by Melvin-Abraham** [comment]
@sepehrraisi Can you share a more verbose error log and/or relevant screenshot for the same?

**Comment by sepehrraisi** [comment]
Sorry for asking
How can I find the logs?

**Comment by Melvin-Abraham** [comment]
@sepehrraisi A screenshot of the error dialog would be sufficient as it contains the stack trace too along with error message.

**Comment by sepehrraisi** [comment]
After Reinstalling the App The problem got solve by it self.
Thank you.
