### ISSUE TITLE
Failed to get Tokens

### ISSUE THREAD

**Issue by blackstar123** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#212]
Assistant failed to fetch the tokens from server. Either the auth code is invalid or the rate limit might have exceeded.
Try selecting a different Google Account.
Error: Error getting tokens

**Comment by esau-morais** [comment]
Please, check [this](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) section on the FAQ

**Comment by blackstar123** [comment]
I have tried to make it work including change the key file path of OAuth authentication and try again the next day, from beginning to end, still failed

**Comment by blackstar123** [comment]
@Melvin-Abraham @esau-morais

**Comment by coder-lg** [comment]
Can you send a screenshot and whatever is printed there as text?

**Comment by Melvin-Abraham** [comment]
@blackstar123 Make sure that you have added the Google Account you are using to get the tokens in the "Test Users" section in your Google Cloud Console as stated in **steps 16 & 17** in [this section of the wiki](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-consent-screen)

**Comment by Melvin-Abraham** [comment]
_Closing as stale_

**Comment by AnotherKaby** [comment]
@blackstar123
I'm also having this problem, the solution is to move the JSON OAuth 2.0 credentials file to another drive (for example on drive D).
This works for me

**Comment by rsnpj** [comment]
Thanks @AnotherKaby, it did work.

**Comment by KovoByte** [comment]
wow this actually fixed the issue, thanks kaby!

**Comment by blitzdose** [comment]
Thanks @AnotherKaby But I had to change the "Saved Tokens Path" aswell to get it to work

**Comment by shabir9846** [comment]
Yeah!  have tried after one day, changed the Jason file to other drives [D, E] and check again by[unitalling & reinstalling assistant, doing the whole web steps again] still the problem persists is there any way to solve it ???

**Comment by beetrandahiya** [comment]
I have one drive (C:\\), mate 😅
any fix for me?

**Comment by Perfii** [comment]
I am also stuck on this screen. I have tried waiting a day and also moving the file around. I created a virtual hard drive (E), but still doesn't work. Any ideas?

**Comment by Shahed2006** [comment]
I am also stuck on this screen.
After one day, I tried changing the Jason file to other drives [D, E] and checked again, but the problem persists. 
Is there any way to solve it?
plz Help me.

**Comment by sumeshir26** [comment]
Delete the tokens.json and try again

**Comment by beetrandahiya** [comment]
So, i did it and it now opens the GET TOKEN window
but after that the browser auth opens, and I select the account.
![Screenshot (551)](https://user-images.githubusercontent.com/63427355/187035359-cc5e2776-692a-4930-ad9a-397397eabd98.png)
 
and then when I click continue
I get 
![Screenshot (552)](https://user-images.githubusercontent.com/63427355/187035391-ca9cb8f6-aa04-476e-90dc-e7f252ad1b9d.png)

**Comment by im-coder-lg** [comment]
From the URL, copy the contents between the queries `?code=` and `&scope` and paste it as your success code. What happens is, that Google's API allowed the request, but some internal(app) change has happened, resulting in this going to localhost. So, that's what you can do.

**Comment by beetrandahiya** [comment]
Yes, thanks, I found the fix when I opened issues 😅
thanks!
btw, it's working well, is there a continued conversation setting?
