### ISSUE TITLE
option to choose a preferred input method

### ISSUE THREAD

**Issue by Netherquark** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#213]
**Is your feature request related to a problem? Please describe.**
==> whenever I use the Win + Shift + A shortcut, the assistant launches in text input mode only and I have to activate voice recognition manually if I want to use it.

**Describe the solution you'd like**
==> more granular controls to change the input options. ie. a toggle that chooses a preferred input method like keyboard/mic and starts that input method whenever the assistant shortcut is used.

**Comment by Sukarth** [comment]
there is an option called 'Enable microphone on application startup' in settings of google assistant.

**Comment by Netherquark** [comment]
@Sukarth where exactly? i only see the key file and token path thing

**Comment by Netherquark** [comment]
sorry my dumb brain forgot to scroll lol
