### ISSUE TITLE
No internet - invalid_grant

### ISSUE THREAD

**Issue by suarep** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#215]
I'm using w10 pro and getting invalid_grant error with No internet message.

I deleted the token and restart it as it stated in FAQ. After that i entered the same json file. Should i create a new one? If yes, why this error came up like this?

Thanks.

**Comment by Sukarth** [comment]
You can fix this by deleting the tokens file that was fetched by the application (as per the "Saved Tokens Path") and relaunch the assistant. You will again be presented with "Get Token!" screen. Authenticate your Gmail account again and let it fetch the tokens. This should possibly fix the issue... If you are presented with this screen when you relaunch the assistant:
![image](https://user-images.githubusercontent.com/67836153/110137994-290d1d80-7dda-11eb-8cb2-ea7ad8a3cf58.png)
Then you should open setting and disable the 'Enable microphone on application startup' setting, save and then relaunch assistant. This should fix the issue.

**Comment by coder-lg** [comment]
Try a new auth if your old one does not work

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
