### ISSUE TITLE
Show me my reminders not working

### ISSUE THREAD

**Issue by Netherquark** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#218]
**Describe the bug**
The show me my reminders command gives audio output when spoken, but its text is spotty and often doesn't even show up in the app

**To Reproduce**
type in Show me my reminders after setting up multiple reminders

**Expected behavior**
they should show up correctly as they do on a phone

**Desktop (please complete the following information):**
 - OS: Windows 10 21h1
 - Version 1.0.0-rc.2

**Comment by rpt225** [comment]
I will be looking into this problem throughout the next week.

**Comment by Netherquark** [comment]
Hey @rpt225 is this fixed? I stopped using this program actually and would like to close this issue if its fixed

**Comment by im-coder-lg** [comment]
Could you share a screenshot, please?

You can just reinstall GAUDC(if you uninstalled it) or just start it and share a screenshot or video.

**Comment by Netherquark** [comment]
I actually switched from windows to linux so im not sure the software bug will be easily replicable. I will share my results with the linux version however

**Comment by Netherquark** [comment]
I'm getting this error:
![image](https://user-images.githubusercontent.com/65618735/141609697-c92e6266-8700-4751-8a2c-080d27978a54.png)

I don't have time for debugging this, etc.
This software is something that I couldn't integrate into my workflow, and now I'm trying to degoogle. So I'm afraid I won't be able to help. You can reopen this and continue working on this issue

**Comment by im-coder-lg** [comment]
I know this, try [`this`](https://gist.github.com/im-coder-lg/23fc93cbf983b36b21641563ed4f3d4e)

**Comment by Netherquark** [comment]
The original bug was different. After spotting the personal results and trying to debug it I eventually gave up. I think youll be able to replicate the original but yourself. Just type in "show me my reminders" it shows up formatted weirdly. As does "create a new reminder"
