### ISSUE TITLE
Choosing microphone input and audio output

### ISSUE THREAD

**Issue by OugiFormula** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#22]
**Hello Melvin!**

Recently I noticed that in the settings we can't choose which audio device google assistant will get the audio source from and send the audio source to.

Since I got multiple audio devices on my pc I need to change it to the ones I use regularly on almost every program or sometimes I want it to be on specific ones like my VR headset microphone in case I want to know some stuff while using my VR headset. 

A small selection drop-down box with all of the user's audio devices and you can choose the one for the microphone and one for the headset will do the job.

**Comment by Melvin-Abraham** [comment]
@czerotwo Thank you for your feedback 👋. These options will be soon added in the settings...
