### ISSUE TITLE
Oh dear god no, not another bloated electron app. Is there no other platform?

### ISSUE THREAD

**Issue by jmorgannz** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#220]
Title says it all.

**Comment by esau-morais** [comment]
I think this cannot be considered an issue. Recommend closing.

**Comment by Melvin-Abraham** [comment]
This issue does not follow the issue template and contributing guidelines and is not inline with current application development. Hence, closing as **invalid**.
