### ISSUE TITLE
Unable to download the file

### ISSUE THREAD

**Issue by Moosa07** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#231]
I am unable to download the installer in Chrome. When I try downloading, a Failed-Forbidden error pops up every time. Is the problem with Chrome or the installer? Please suggest any fix. Thank you.

**Comment by Melvin-Abraham** [comment]
This issue is not related to your system/browser and to the application. I would recommend searching the issue online...

**Comment by Moosa07** [comment]
Thank you Melvin, the issue is resolved now. The application is awesome
