### ISSUE TITLE
how do i put the white mode PIease?

### ISSUE THREAD

**Issue by C10kk0** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#233]
![bitmoji](https://sdk.bitmoji.com/render/panel/214e2e2c-3a98-46f6-9b61-50c57a0d8fca-b464c4b0-bfa5-4ca4-b609-e9e7308e5d62-v1.png?transparent=1&palette=1&width=246)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by esau-morais** [comment]
This issue is blank. Could you please explain what is the "white mode"? If you mean light mode, you just need to go into the settings and scroll down till find the option.

**Comment by lorenzosoannini** [comment]
With light theme enabled, the client opens in dark mode and after 2-3 seconds it changes to light theme

**Comment by esau-morais** [comment]
Hey, @lorenzosoannini. I tried to reproduce your issue and for me worked fine, with no delay. Please, refer to your comment as a new issue using the template

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
