### ISSUE TITLE
Escape to dismiss

### ISSUE THREAD

**Issue by SjorsMaster** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#234]
Please consider an "esc to dissmiss assistant" feature.

**Comment by esau-morais** [comment]
Duplicate of #92

**Comment by esau-morais** [comment]
This feature was already implemented on the built version. If you just installed the latest release, it still not available. Why I recommend is to build in your own machine in the meantime.

**Comment by Melvin-Abraham** [comment]
@SjorsMaster This feature has already been implemented in ede676c2

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
