### ISSUE TITLE
Light theme delay while opening the client

### ISSUE THREAD

**Issue by lorenzosoannini** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#235]
**Describe the bug**
With light theme enabled, the client opens in dark mode and after 2-3 seconds it changes to light theme.

**To Reproduce**
1. Open the client with keyboard shortcut or from the tray icon
2. The client opens in dark theme while loadind and then it changes to light theme

**Expected behavior**
The client should instantly open in light theme.

**Screenshots**

https://user-images.githubusercontent.com/35431333/110836694-a2a48000-82a0-11eb-9b76-2578695239ed.mp4

**Desktop:**
 - OS:  Windows 10 Home 20H2 (same problem in macOS 11.2.2)
 - Version: 1.0.0-rc.2

**Comment by esau-morais** [comment]
Did you build the Google Assistant in your local machine or just installed the latest version? I've tested it in mine, but it works perfectly

**Comment by Melvin-Abraham** [comment]
This was an issue related to the specific version of **electron** used in `v1.0.0-rc.2` release. The electron version has since been updated in the master branch and the issue doesn't seem to show up anymore.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
