### ISSUE TITLE
App crash on launch

### ISSUE THREAD

**Issue by Henry-YSLin** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#237]
**Describe the bug**
The "Google Assistant is running in background" notification appears, then a javascript error dialog pops up causing the app to freeze. The main app window seems to be open already, covering part of the screen (causing that part to be unresponsive to clicks) while being completely transparent. 

The app has launched successfully several times before. This error first appeared after a system reboot, then the app crashes consistently ever since. A reinstall does not solve the issue.

**To Reproduce**
1. Open the app
2. The error message appears

**Expected behavior**
App launches without error

**Screenshots**
![image](https://user-images.githubusercontent.com/25472513/110876938-737b2680-8313-11eb-856d-a846d8a5ae8d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 20H2
 - Version 1.0.0-rc.1

**Comment by esau-morais** [comment]
Please, check [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0) on the FAQ and see if it solves.

**Comment by esau-morais** [comment]
Several issues similar to this

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
