### ISSUE TITLE
Assistant Randomly Triggers

### ISSUE THREAD

**Issue by EliotHertenstein** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#239]
**Describe the bug**
A clear and concise description of what the bug is:
Assistant randomly triggers

**To Reproduce**
1. Install Assistant
2. Leave in the background, closed. 
4. Wait for trigger noise. 

**Expected behavior**
No random triggers

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.0-rc.2

**Comment by esau-morais** [comment]
Could you please provide a video and/or screenshot?

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
