### ISSUE TITLE
Shortcut Change

### ISSUE THREAD

**Issue by niksingh710** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#24]
Will be great if we can have an option to change the quick access shortcut.

**Comment by Melvin-Abraham** [comment]
@niksingh710 Thank you for the feedback 👋. This feature will be worked upon soon...

**Comment by Bulwagga** [comment]
> Will be great if we can have an option to change the quick access shortcut.

I'm using Ubuntu 20.10 and Super-Shift-A doesn't cause anything to happen.

**Comment by Melvin-Abraham** [comment]
@Bulwagga You will have to wait for sometime to let the assistant initialize (indicated by colorful tray icon as opposed to grayscale tray icon).

**Comment by CorvetteCole** [comment]
@Bulwagga are you in a Wayland session? I've run in to this in #46

**Comment by Bulwagga** [comment]
I never got beyond the gray icon.  I'm pretty sure I didn't wait long enough.  I'm using a standard 20.10 Ubuntu install.  I'm OK closing this. Thank you.

**Comment by Melvin-Abraham** [comment]
The assistant hotkey can now be changed from within the settings:
**Settings** > **Application** > **Assistant Hotkey**.

**Comment by niksingh710** [comment]
I have version 1.0.0-rc.2 and when I check for update it says "You have the latest version".
Installed it via Snap.

**Comment by Melvin-Abraham** [comment]
@niksingh710 That's because no new version has been released. This feature will be added to the next version after some time in addition to other bug fixes and enhancements. Meanwhile, you could test it if you want by cloning the repo and running/building it. :)
