### ISSUE TITLE
🐛 BUG: A JavaScript error occurred in the main process" after installing the program 

### ISSUE THREAD

**Issue by Jonny-T-cyber** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#241]
**Bug**
Popup error: "A JavaScript error occurred in the main process" after installing the program.

**To Reproduce**
1. Install the program v1.0.0-rc.2 (I also tried as Administrator)
2. The error popup appears immediately after installation
3. It is not possible to use the PC until the newly installed program is forcibly closed

**Screenshot**

![image](https://user-images.githubusercontent.com/33354144/111137758-767a4f00-857f-11eb-9f9a-e322e07d042c.png)

**Desktop:**
 - OS: Windows 10 Pro v.20H2 Build 19042.867

**Comment by esau-morais** [comment]
Several issues similar to this. Check [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0) at the FAQ to solve it.

**Comment by Giovanni-Trivigno** [comment]
So the problem would recur every time I change the screen resolution?

**Comment by Giovanni-Trivigno** [comment]
Also ... I don't know how to build on windows.
At the following link it is all very generic:

https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument- at-index-0

Please, could you give me support?
Thanks

**Comment by esau-morais** [comment]
> Please, could you give me support?

* Fork this project, clicking the "Fork" button at the Top-Right:

![Fork button](https://user-images.githubusercontent.com/55207584/111164494-e5a27400-857c-11eb-932a-09fa0bdf4e1c.png)

* Open the forked project folder with the command prompt

![Forked folder](https://user-images.githubusercontent.com/55207584/111165084-66fa0680-857d-11eb-9c55-7a3f38750d13.png)


> Before installing, you need to have the [nodejs ](https://nodejs.org/en/) LTS version installed on your machine

* To install the dependencies, type `npm install`

* Finally, to start the project, `npm run start`

**Comment by Giovanni-Trivigno** [comment]
I probably miss something but I have problems during installation, as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/33354144/111183710-7e9eb280-85b0-11eb-9e6f-d8d5962024f1.png)

**Comment by esau-morais** [comment]
There's nothing wrong, you didn't need to run the command `npm audit fix`, once it's just a warning that shows up to everyone.

**Comment by Giovanni-Trivigno** [comment]
OK thanks, now it works.
I would like to ask you these questions again:
1) So will I always have to run the program with the `npm run start` command?
2) Is there a planned release of a new version that fixes the JavaScript error problem?
3) If so, when? Is there a way to be notified of the new release?

Thanks again
G.

**Comment by esau-morais** [comment]
> So will I always have to run the program with the npm run start command?

Unfortunately, yes.

> Is there a planned release of a new version that fixes the JavaScript error problem?

Yes, the build release (that you've just forked) already has a lot of improvements. As soon as possible, it'll be released a new version.

> If so, when? Is there a way to be notified of the new release?

I don't know exactly, once I'm just one of the contributors. But there's a button in About at the settings to check new updates

**Comment by Jonny-T-cyber** [comment]
Ok, thank you very much

**Comment by esau-morais** [comment]
No problem :) Recommend closing the issue.
