### ISSUE TITLE
Deprecated Electron Function

### ISSUE THREAD

**Issue by waterlava** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#247]
**Describe the bug**
Startup error message:
`(node:57337) Electron: Loading non-context-aware native module in renderer: '/run/user/1000/snap.g-assist/.org.chromium.Chromium.iAE5Gz'. This is deprecated, see https://github.com/electron/electron/issues/18397.`

**To Reproduce**
1. Type `g-assist` in terminal

**Expected behavior**
Program start-up without error messages.

**Screenshots**
![image](https://user-images.githubusercontent.com/25158977/111568026-6082af00-8776-11eb-821e-84342235b3cf.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1, Shell: 5.4.0-67-generic, Bash: 5.0.17
 - v1.0.0-rc.2

**Comment by coder-lg** [comment]
Hi,
It is exactly normal, it is just a warning that Electron is deprecated, no worries, GAUDC will run.
From coder-lg

**Comment by coder-lg** [comment]
If you are running the npm terminal version, it will be shown.
Try downloading your Linux installer from here: [Releases](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.0.0-rc.2)
From coder-lg

**Comment by Melvin-Abraham** [comment]
This is due to a native module, `grpc`, used by this project and is just a warning which could be ignored for now. However, if there's a way to get it working via `grpc-js` (for both typed and voice queries), please do share it here.
