### ISSUE TITLE
Failed to start assistant

### ISSUE THREAD

**Issue by Goyoopp** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#258]
Error: Getting metadata from plugin failed with error: invalid_grant

**Comment by Melvin-Abraham** [comment]
This is a duplicate of #58 and many others. Please refer to [this FAQ section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error).

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
