### ISSUE TITLE
Not accepting dist build requests

### ISSUE THREAD

**Issue by coder-lg** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#260]
**Describe the bug**
So, seeing the latest commit, I cloned the repo and installed it via npm install. But, when I hit npm run dist, it just gives a nice start but then, a crash. I will try to add the log file here.
**To Reproduce**
Clone the repo.
Use npm install, it is successful.
Now, use npm run dist.
Start is fine, but crashes at the end.
**Expected behavior**
Installation to go properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7 Build 7601]
 - Version [e.g. 1.0.0-rc.2 repo code edition]

**Additional context**
The debug.log file contents
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle g-assist@1.0.0-rc.2~predist: g-assist@1.0.0-rc.2
6 info lifecycle g-assist@1.0.0-rc.2~dist: g-assist@1.0.0-rc.2
7 verbose lifecycle g-assist@1.0.0-rc.2~dist: unsafe-perm in lifecycle true
8 verbose lifecycle g-assist@1.0.0-rc.2~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user\Documents\GitHub\Google-Assistant-Unofficial-Desktop-Client\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\dotnet\;C:\Users\user\adb;C:\adb;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Ruby27-x64\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\dotnet\;C:\Users\user\adb;C:\Users\user\AppData\Roaming\npm
9 verbose lifecycle g-assist@1.0.0-rc.2~dist: CWD: C:\Users\user\Documents\GitHub\Google-Assistant-Unofficial-Desktop-Client
10 silly lifecycle g-assist@1.0.0-rc.2~dist: Args: [ '/d /s /c', 'electron-builder' ]
11 silly lifecycle g-assist@1.0.0-rc.2~dist: Returned: code: 1  signal: null
12 info lifecycle g-assist@1.0.0-rc.2~dist: Failed to exec dist script
13 verbose stack Error: g-assist@1.0.0-rc.2 dist: `electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid g-assist@1.0.0-rc.2
15 verbose cwd C:\Users\user\Documents\GitHub\Google-Assistant-Unofficial-Desktop-Client
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error g-assist@1.0.0-rc.2 dist: `electron-builder`
22 error Exit status 1
23 error Failed at the g-assist@1.0.0-rc.2 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by coder-lg** [comment]
Moreover, it is accepting only the `npm run start` command.

**Comment by coder-lg** [comment]
Same with `yarn dist`

**Comment by Melvin-Abraham** [comment]
@coder-lg Errors like this generally occur when the native module (used in the project) fails to compile. Make sure you have the required build tools installed on your machine before installing dependencies or building. Refer to [Windows Build Note](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/CONTRIBUTING.md#windows-build-note).

**Comment by coder-lg** [comment]
I will check and tell here

**Comment by coder-lg** [comment]
Also, the crash happened after it told it's unzipping Electron Builder

**Comment by coder-lg** [comment]
It....... didn't work☹️

**Comment by coder-lg** [comment]
Can you please tell an alternate build solution, please? I even got Windows Build Tools in my PC

**Comment by Melvin-Abraham** [comment]
@coder-lg Can you send the logs here?

**Comment by coder-lg** [comment]
I will retry installation and send the logs here.

**Comment by coder-lg** [comment]
[2021-04-04T04_39_39_691Z-debug.log](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/files/6253994/2021-04-04T04_39_39_691Z-debug.log)
FYI:This file is the latest log I have made. Please check.

**Comment by coder-lg** [comment]
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle g-assist@1.0.0-rc.2~predist: g-assist@1.0.0-rc.2
6 info lifecycle g-assist@1.0.0-rc.2~dist: g-assist@1.0.0-rc.2
7 verbose lifecycle g-assist@1.0.0-rc.2~dist: unsafe-perm in lifecycle true
8 verbose lifecycle g-assist@1.0.0-rc.2~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\new gaudc\Google-Assistant-Unofficial-Desktop-Client-master\Google-Assistant-Unofficial-Desktop-Client-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\dotnet\;C:\Users\DELL\adb;C:\adb;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Ruby27-x64\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\dotnet\;C:\Users\DELL\adb;C:\Users\DELL\AppData\Roaming\npm
9 verbose lifecycle g-assist@1.0.0-rc.2~dist: CWD: D:\new gaudc\Google-Assistant-Unofficial-Desktop-Client-master\Google-Assistant-Unofficial-Desktop-Client-master
10 silly lifecycle g-assist@1.0.0-rc.2~dist: Args: [ '/d /s /c', 'electron-builder' ]
11 silly lifecycle g-assist@1.0.0-rc.2~dist: Returned: code: 1  signal: null
12 info lifecycle g-assist@1.0.0-rc.2~dist: Failed to exec dist script
13 verbose stack Error: g-assist@1.0.0-rc.2 dist: `electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid g-assist@1.0.0-rc.2
15 verbose cwd D:\new gaudc\Google-Assistant-Unofficial-Desktop-Client-master\Google-Assistant-Unofficial-Desktop-Client-master
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error g-assist@1.0.0-rc.2 dist: `electron-builder`
22 error Exit status 1
23 error Failed at the g-assist@1.0.0-rc.2 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`
This is what it shows in the log

**Comment by coder-lg** [comment]
And, a striking similarity to my first log text: Two places where electron-builder is not in the code thing in my editor

**Comment by coder-lg** [comment]
Does anybody know these errors? I am confused

**Comment by Melvin-Abraham** [comment]
@coder-lg Do you have Visual Studio installed? _(I do not mean VSCode)_

**Comment by coder-lg** [comment]
Nope, it is heavy for all my PCs, it makes the computer slow

**Comment by coder-lg** [comment]
So, I don't have it. Must I install it?

**Comment by Melvin-Abraham** [comment]
@coder-lg I would recommend going through [Build Instructions (Windows)](https://www.electronjs.org/docs/development/build-instructions-windows), an official Electron Guide for building on Windows.

**Comment by coder-lg** [comment]
Can you explain the process?I am not able to understand it.

**Comment by Melvin-Abraham** [comment]
> Can you explain the process?I am not able to understand it.

Try installing Visual Studio 2017 15.7.2 or higher and do let me know if it works.

**Comment by coder-lg** [comment]
After installing, what should I do?

**Comment by Melvin-Abraham** [comment]
@coder-lg Can you try building again?

**Comment by coder-lg** [comment]
I will try.

**Comment by coder-lg** [comment]
Thanks a lot, it works now!
