### ISSUE TITLE
Voice Input Problem

### ISSUE THREAD

**Issue by DarkLord123418** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#263]
Every time i try to say something to the assistant, it only registers "Trial Version" no matter what I say. It does take those inputs when I type them manually, but not when I am speaking . I tried words that have no pronounciation similarity with "Trial version", but it didn't help.[
![Screenshot (247)](https://user-images.githubusercontent.com/71208162/113485391-e323a200-94ca-11eb-9440-f53410be81b6.png)
](url)

**Comment by Melvin-Abraham** [comment]
The problem is kind of unclear as per the description but it seems like a duplicate of #38 and #41.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
