### ISSUE TITLE
JavaScript error during launch, unable to use

### ISSUE THREAD

**Issue by onlytanmoy** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#266]
Hi, please see the error screenshot, I am getting it while trying to launch Google Assistant.
I am using Google_Assistant-Setup-1.0.0-rc.2 on my Win 10 ver 20H2 (OS Build 19042.867)
please let me know how to fix this, TIA

https://imgur.com/a/bwhzQ9r

**Comment by esau-morais** [comment]
Several issues similar to this one. Please, check [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0) at the FAQ.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_

**Comment by onlytanmoy** [comment]
> Several issues similar to this one. Please, check [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0) at the FAQ.

Thanks for you response mate, it's a shame my current resolution 3840 x 2160 is unsupported at the moment 😒 will keep an eye out for the next update, hopefully this issue will be resolved then, cheers!
