### ISSUE TITLE
🐛 BUG: Error: Tried calling start() before the ready event!

### ISSUE THREAD

**Issue by Playerek** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#268]
Hello. I am having some problem with the Google Assistant client. After following all the steps from here, I have added the location of the key file. I restarted the client and got an error (image). Again, I tried from scratch to add the key file or restart the program, but the error still appeared. I ignored the problem with the "ignore" button. I logged into the account and allowed all permissions. After pasting the token, I could not click the "submit" button. I tried a few more times, but to no avail.
Apologies for any language mistakes.

**Screenshots**
![image 1](https://user-images.githubusercontent.com/62960395/113508205-f710e780-954e-11eb-955a-6b92f64f4a80.png)
![error console](https://user-images.githubusercontent.com/62960395/113508706-bc5c7e80-9551-11eb-8e84-f0c1b2528bcd.png)

**Desktop:**
 - OS: Windows 10 Home 20H2
 - Version: v1.0.0-rc.2

**Comment by coder-lg** [comment]
Go to settings, and turn off Enable Microphone on startup and try. I got the same error. But I fixed it, so turn off that toggle.

**Comment by coder-lg** [comment]
This is for your information: [My way, i got error like this](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/185)
Duplicate of #185 btw

**Comment by coder-lg** [comment]
I recommend closing the issue if this is fixed.

**Comment by Playerek** [comment]
OK, thank you for your help. I think it will be all right now.
