### ISSUE TITLE
Get Token!

### ISSUE THREAD

**Issue by shubamsumbria66** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#269]
**Describe the bug**
Submit button is not working/stuck in Get Token! screen. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043.906
 - Version 1.0.0-rc.2

**Additional context**

**Comment by shubamsumbria66** [comment]
Check ASAP

**Comment by esau-morais** [comment]
Several issues similar to this

**Comment by esau-morais** [comment]
Check [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens) at the FAQ

**Comment by shubamsumbria66** [comment]
Thank you so much, really appreciate your work.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
