### ISSUE TITLE
Repeating the same

### ISSUE THREAD

**Issue by amcareem** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#273]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by Melvin-Abraham** [comment]
This issue is not descriptive. Please fill in all the required details as per the given template as it makes it easier to understand and test.

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
