### ISSUE TITLE
Unexpected Exception Occured

### ISSUE THREAD

**Issue by Camo911Triba** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#279]
**Describe the bug**
"Unexpected Exception Occured
An unexpected error occurred.
Error: Tried calling start() before the ready event!"

**To Reproduce**

**Expected behavior**
when I try to put a token in this pops up before I can put the token in so

**Screenshots**
![Google Assistant Unofficial Client 4_8_2021 11_36_23 AM](https://user-images.githubusercontent.com/65539391/114055433-c5ee2b00-985e-11eb-815d-b137a0f29058.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 20H2
 - Version: 19042.867

**Additional context**

**Comment by coder-lg** [comment]
Copy of issue #185
Turn off Enable microphone on startup and login again

**Comment by coder-lg** [comment]
Or, try building it in npm again, it might work

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
