### ISSUE TITLE
[Feature Request] Multiple instances change

### ISSUE THREAD

**Issue by regisandre** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#28]
Hello,

I really love your app, I have been waiting for a long time to have Google Assistant on Windows 10 and others and your app is just awesome!

My suggestion : Instead of displaying an error message "Preventing launch: An instance of Google Assistant is already running. Openration Aborted" when trying to open the Google Assistant when it is already open, the shortcut should activate the microphone.
![image](https://user-images.githubusercontent.com/21986104/97550756-5a13b680-19d2-11eb-912e-3a5f1460c205.png)

Thanks !

**Comment by Melvin-Abraham** [comment]
@regisandre I think that's more of a personal preference in my opinion. Some people might not like the assistant to just let the microphone start when this happens. So, I guess that could be left unchanged.

If you have any opinions about it, let me know...

**Comment by regisandre** [comment]
> @regisandre That's more of a personal preference in my opinion. Some people might not like the assistant to just let the microphone start when this happens. So, I guess that could be left unchanged.
> 
> If you have any opinions about it, let me know...

I think that you can add an option in the settings named "Preventing launch of multiple instances" enabled by default or "Activate the microphone when try to launch a new instance" 😅

**Comment by VinceBT** [comment]
> > @regisandre That's more of a personal preference in my opinion. Some people might not like the assistant to just let the microphone start when this happens. So, I guess that could be left unchanged.
> > If you have any opinions about it, let me know...
> 
> I think that you can add an option in the settings named "Preventing launch of multiple instances" enabled by default or "Activate the microphone when try to launch a new instance" 😅

I think this option might be the good one !
