### ISSUE TITLE
new bug while creating reminders

### ISSUE THREAD

**Issue by Netherquark** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#284]
**Describe the bug**
when i ask the assistant to create a reminder it sends a prompt to my phone, and even if I allow it to, it doesn't allow it actually. when I try again, it still asks the same thing. Issue wasn't there till today afaik

**To Reproduce**
1. Ask Google assistant to set a reminder

**Expected behavior**
it should set a reminder?

**Screenshots**
![image](https://user-images.githubusercontent.com/65618735/114212815-dea23200-997f-11eb-8b26-a1de4b408a92.png)

**Desktop (please complete the following information):**
 - android 11 phone
 - windows 10 21h1 build 
 - rc 2 build of assistant

**Comment by sumeshir26** [comment]
Similar to #301 #175

**Comment by Melvin-Abraham** [comment]
This issue is related to accessing user's personal results, thus will be tracked in #175.

**Comment by Melvin-Abraham** [comment]
_Closing this issue_
