### ISSUE TITLE
Can not open URL to authenticate: Application not found

### ISSUE THREAD

**Issue by TheCrazyMax** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#287]
**Describe the bug**
Everything is configured based on https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client and I added an application logo too after reading other issues.
BUG: When the assistant tries to open the authentication URL on the browser, I'm getting this error window :
![image](https://user-images.githubusercontent.com/15264289/114272085-e233c880-9a14-11eb-9c93-cf2a7795d5db.png)
And I can not copy the URL on that window

**Expected behavior**
Open the URL on the browser.
Be able to copy the authentication URL to paste in a browser ourselves

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/15264289/114272139-2aeb8180-9a15-11eb-9952-62e4fa644bdb.png)

 - Version 1.0.0-rc.2

**Comment by Melvin-Abraham** [comment]
@TheCrazyMax This error shows up when a default application to open the URI is not set. Please check if you have a default browser application set on your device.

On Windows 10, search for _"Default Apps"_ in Settings and scroll to _"Web Browser"_ section and check if a default app is configured there. If not, select a preferred browser and try again.

**Comment by TheCrazyMax** [comment]
> @TheCrazyMax This error shows up when a default application to open the URI is not set. Please check if you have a default browser application set on your device.
> 
> On Windows 10, search for _"Default Apps"_ in Settings and scroll to _"Web Browser"_ section and check if a default app is configured there. If not, select a preferred browser and try again.

Thank you :) I had the 403 error before and it was working, so I didn't suspect that, but for some reason my default browser was unset between the attempts.
