### ISSUE TITLE
Unexpected Exception Occured

### ISSUE THREAD

**Issue by NotFiilip** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#291]
The Assistant failed to initialize due to some unexpected error. Try reloading the assistant.
Error: Assistant init failed
Ubuntu 20.04, KDE Plasma
![error1](https://user-images.githubusercontent.com/82344313/114323454-9755a600-9b25-11eb-9808-151c331e9f5a.png)
![error2](https://user-images.githubusercontent.com/82344313/114323459-99b80000-9b25-11eb-8f6d-6d2e4fc16754.png)

**Comment by Melvin-Abraham** [comment]
@NotFiilip Was the issue resolved?

**Comment by NotFiilip** [comment]
> @NotFiilip Was the issue resolved?

@Melvin-Abraham Yes I did something wrong in the Cloud Console. Redid the whole thing and it works now.
