### ISSUE TITLE
Error:Getting metadata from plugin failed with error:invalid_grant 

### ISSUE THREAD

**Issue by Aguilarcho2021** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#295]
Hello, I have had this problem for a week, and when I open google assistant, I get this error, could someone tell me why I get this error? and how I could fix it?
![image](https://user-images.githubusercontent.com/82472371/114608751-9fb3fb00-9c63-11eb-9d42-4a5394302a98.png)

**Comment by coder-lg** [comment]
I think, it is your tokens.json that is causing this problem, try to delete it and create a new tokens.json. If you get another error and you are almost going to the success code level but it doesn't accept, you turn off Enable microphone on application startup, it will cause a start error.

**Comment by coder-lg** [comment]
If you get `Tried calling start() before the ready event`, refer to #185.

**Comment by Aguilarcho2021** [comment]
> I think, it is your tokens.json that is causing this problem, try to delete it and create a new tokens.json. If you get another error and you are almost going to the success code level but it doesn't accept, you turn off Enable microphone on application startup, it will cause a start error.

Thank you I will try

**Comment by coder-lg** [comment]
Has it worked?

**Comment by Aguilarcho2021** [comment]
Nope, i try all,and no 
![image](https://user-images.githubusercontent.com/82472371/114928261-023e0000-9df8-11eb-9186-93eaac0cce27.png)

**Comment by Melvin-Abraham** [comment]
@Aguilarcho2021 Refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error) of the FAQ to address this issue for now.

**Comment by Aguilarcho2021** [comment]
thank you, has been fixed, greetings from colombia.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
