### ISSUE TITLE
Auto Enable Microphone

### ISSUE THREAD

**Issue by Piflyer** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#3]
**Is your feature request related to a problem? Please describe.**
I'm always annoyed how the microphone isn't on when I press the hotkeys (Command+Shift+A)
**Describe the solution you'd like**
When you press the hotkeys (Command+Shift+A), the microphone turns on automatically so you can speak at it.
**Describe alternatives you've considered**
Toggle to enable or disable microphone when pressed.

**Comment by Melvin-Abraham** [comment]
@Piflyer Thank you for your feedback 👋. This option will be soon added in the form of a setting...
