### ISSUE TITLE
[Feature Request / Issue] Microphone monopolization on Windows 10

### ISSUE THREAD

**Issue by regisandre** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#30]
Hello,

I really love your app, I have been waiting for a long time to have Google Assistant on Windows 10 and others and your app is just awesome!

My suggestion : Ultimately, when you have succeeded in activating your application automatically with the sentences "Hey Google" and "Ok Google", take care not to monopolize the microphone. What is a bit annoying is that Windows displays when the mic is in use by an application and in this case since your application is using it all the time I can't tell "easily" when another application is using my mic without my permission. So this Windows option unfortunately loses all meaning.
![image](https://user-images.githubusercontent.com/21986104/97550890-892a2800-19d2-11eb-97a5-742994ef73bc.png)

Thanks !

**Comment by Melvin-Abraham** [comment]
@regisandre Well, it turns out that the `startMic()` function created a new `Microphone` instance every-time it was called instead of stopping/reusing the existing instance. Anyway, this will be fixed soon...

Related: #20

**Comment by regisandre** [comment]
Thanks @Melvin-Abraham, it's perfect !
