### ISSUE TITLE
A Javascript error ocurred in the main process

### ISSUE THREAD

**Issue by appedro** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#307]
From the last days I've been getting this follow error on win10: 
https://imgur.com/a/5wsjSDF
Then, I can't even use since it doesn't open. Somebody else with this same problem or know the fix?

**Comment by Melvin-Abraham** [comment]
This is a known bug but has been fixed and will be made available in the next release through updates. Till then you can refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0) of the FAQ to address this issue.
