### ISSUE TITLE
You are Offline!

### ISSUE THREAD

**Issue by himanshusankhala04** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#308]
**Describe the bug**
Whenever I try to use Google Assistant it throws "You are Offline!" Error even if I am connected to the Internet.

**To Reproduce**
1. Open Google Assistant
2. Search anything
3. See error

**Expected behavior**
It should work fine and there should be resent or troubleshooting option in setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/43336485/114980213-c1062880-9ea9-11eb-929d-7e83bac67eff.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 20H2
 - Version 1.0.0-rc.2

**Comment by Melvin-Abraham** [comment]
@himanshusankhala04 Refer [this section](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error) of the FAQ to address this issue for now.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
