### ISSUE TITLE
how to delete the configuration files ?

### ISSUE THREAD

**Issue by Fisummer** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#317]
i mean where is the configuration file located ? when i deleted the whole folder of the app and reinstall it ,in the settings it just keep my last saving settings so obviously the settings not keeping in the app folder.

**Comment by coder-lg** [comment]
It has to be the tokens.json you have, try deleting that or even the client_secret-------.json, it might solve the problem.

**Comment by Fisummer** [comment]
i don't think so, i delete all files of the app and the tokens.json, after a totally new installation, when click to the app settings of AUTHENTICATION SECTION to configure the key path and tokens , i noticed that the "Key File Path" and "Saved Token Path"  still keep my last settings path even though no files there ,i can duplicate it

**Comment by coder-lg** [comment]
Try making a new project in Actions Condole and Google Cloud again, it might work.

**Comment by coder-lg** [comment]
There is some glitch, the path of the tokens and the client secret json files will be present even if you delete them. You clear them and make the new project in Actions Console and Google Cloud.

**Comment by Melvin-Abraham** [comment]
If you want to start fresh, you may choose to delete the config file. To do that, go to **Settings** > **Developer Options** > **Open App Data Folder**. From there, locate the `config.json` file. You may manually edit the file or delete it to start fresh.

**Comment by Fisummer** [comment]
> If you want to start fresh, you may choose to delete the config file. To do that, go to **Settings** > **Developer Options** > **Open App Data Folder**. From there, locate the `config.json` file. You may manually edit the file or delete it to start fresh.

thank you,solved
