### ISSUE TITLE
Can I activate the Assistant by saying "Hey Google"

### ISSUE THREAD

**Issue by SnynsistSuff** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#322]
Can I activate the Assistant by saying "Hey Google"??
I dont want to press anytime on the button to avtivate it!!

**Comment by sumeshir26** [comment]
This is already on the roadmap and will be implemented as soon as possible...

(This issue is being tracked in #105)

**Comment by obed9057** [comment]
I am not comfortable using command prompt to activate a (beta) app cant there be an easier way that can't possibly damage my computer?

**Comment by sumeshir26** [comment]
@obed9057 Is this the same question as #324?
If yes, the question has already answered there.

**Comment by obed9057** [comment]
no, it is different and the creator already responded to me so thanks but I'm fine.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_

**Comment by obed9057** [comment]
?
