### ISSUE TITLE
[Repository] Add Project Board

### ISSUE THREAD

**Issue by sumeshir26** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#323]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was an Projects Board for this repository.
**Describe the solution you'd like**
It would be nice if you could see what needs to be worked on rather than scrolling through the issues and the un-detailed roadmap.
**Additional context**
I am thinking about something like this: [https://github.com/files-community/Files/projects/1]

**Comment by Melvin-Abraham** [comment]
@sumeshir26 That's a good suggestion. This would definitely be implemented in this project ✨✨

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
