### ISSUE TITLE
not able to  reinstall the client  pls help

### ISSUE THREAD

**Issue by Anshum-Bhargav** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#328]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by obed9057** [comment]
well now there's no point of responding
