### ISSUE TITLE
Google Assistant.exe detected as a virus by SMADAV Antivirus.

### ISSUE THREAD

**Issue by nawka12** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#329]
Hi, my antivirus detect this program as a virus. Is this really okay?
![image](https://user-images.githubusercontent.com/54880732/115741273-cab3f280-a3b9-11eb-98da-519308dfdee1.png)

**Comment by sumeshir26** [comment]
@nawka12 This program is perfectly safe (I have downloaded and built this multiple times).

(You can check the source code for proof.)

**Comment by ccrsxx** [comment]
I'm sure it's just a false positive.

**Comment by obed9057** [comment]
it only thinks its a virus because first of all its a .exe file second of all it is not certified by Google so it automatically thinks its a virus but it is not.

**Comment by im-coder-lg** [comment]
Too old issue, but for clarification, the app isn't certified. For a certificate, it'd be a lot of money, it's kinda hard. But the app is fine. If there was a certificate saying this is all good, the antivirus software would be accepting this.
