### ISSUE TITLE
Error: Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by boredcorgi** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#330]
It has been working for few day but suddenly it gave the error.
P.S I'm connected
![image](https://user-images.githubusercontent.com/62491748/115849116-27191f80-a457-11eb-939d-7f624ee7246a.png)

**Comment by sumeshir26** [comment]
@boredcorgi Try going through [this section of the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error).

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
