### ISSUE TITLE
Error: Getting metadata from plugin failed with error: invalid_grant

### ISSUE THREAD

**Issue by suryaduerre** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#332]
All of a sudden having this issue. Any solutions?

**Comment by sumeshir26** [comment]
@suryaduerre Try going through [this section of the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error).

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
