### ISSUE TITLE
A JavaScript error occurred in the main process...… how do I fix this?(windows 10)

### ISSUE THREAD

**Issue by maximumchar** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#333]
I have downloaded this app just now and have done everything as told but when i try to open it it says "A JavaScript error occured in the main process" i have attached a screenshot of the ERROR MESSAGE. Please help me, i always wanted to have Google assistant on my PC.
![Screenshot 2021-04-24 222543](https://user-images.githubusercontent.com/77259344/115966605-0979b200-a54c-11eb-80be-648a02b1e042.png)

**Comment by sumeshir26** [comment]
@maximumchar Try going through [This section of the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0)

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
