### ISSUE TITLE
[Issue] Startup launch issue on Windows 10

### ISSUE THREAD

**Issue by regisandre** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#34]
Hello,

I really love your app, I have been waiting for a long time to have Google Assistant on Windows 10 and others and your app is just awesome!

My issue : When I activate the option to launch the application at system startup on Windows 10, it does not appear in my system bar at the bottom left. On the other hand, when I add an application shortcut in the start-up folder of my "shell: startup" session, an error appears to show that another instance of Google Assistant has been launched.

So I disabled the option to start your app in its settings and left the shortcut in my start folder and it works just fine like that.

On Linux Mint 20 it works perfectly.

Thanks !

**Comment by Melvin-Abraham** [comment]
Can you check if "Google Assistant" appears in the **"Startup"** tab of Task Manager? Also, is there a possibility that you forgot to check the "Show Hidden Icons" button in the taskbar? Let me know...

**Comment by regisandre** [comment]
> Can you check if "Google Assistant" appears in the **"Startup"** tab of Task Manager? Also, is there a possibility that you forgot to check the "Show Hidden Icons" button in the taskbar? Let me know...

Yes everything is well activated. I am a system administrator so I also looked a little further for the cause of the problem, but I couldn't find anything 😕

**Comment by bhatmuchas007** [comment]
Hello, The same problem Is also faced by me. The system gives a **javascript error** when I try to open the version 1.0.0-rc.2  **(THE LATEST ONE)**

**Comment by Melvin-Abraham** [comment]
@bhatmuchas007 Can you share the screenshot of the error? What OS are you using? Are you using running the binary from the "Releases" or executing via `npm start`?

**Comment by Melvin-Abraham** [comment]
@regisandre Can you try the following?

- Try removing the application shortcut from **"shell: startup"**
- Clone this repo or fetch latest changes
- Run `npm install`
- Run `npm run dist`
- Go to `dist/` directory and run the installer

Check if the problem still exists...

**Comment by TheTUFGuy** [comment]
I am having the same javascript error issue. I tried installing it through yarn aas well as the direct setup files. Same error both the times. Have a look.
![Screenshot 2021-02-26 234453](https://user-images.githubusercontent.com/79718151/109339187-49465500-788d-11eb-9a69-d39774d8d17f.png)

**Comment by NovaViper** [comment]
Can confirm the same issue on Manjaro KDE, I tried both the Snap and App Image

**Comment by cmt29** [comment]
No sure if I'm encountering the same issue as above, but having just installed this via Snap under OpenSuse Leap 15.2, 'Launch at System Startup' switched on doesn't seem to have any effect - in that the application isn't launched at system startup. Please could you help me troubleshoot / determine if this is a bug?

**Comment by sumeshir26** [comment]
@cmt29 Try pressing super + shift + A. It doesn’t actually launch on startup but instead starts running in the background and listens for hot words if enabled

**Comment by cmt29** [comment]
OK thanks, @sumeshir26 . I've tried that, but still nothing.

**Comment by Melvin-Abraham** [comment]
@cmt29 Can you open it as a [new issue](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/new/choose)?

**Comment by Melvin-Abraham** [comment]
This issue has been fixed in the latest release.

_Closing as resolved_
