### ISSUE TITLE
Unable to use Google Assistant due to Network Error.

### ISSUE THREAD

**Issue by iDCoded** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#344]
When I launch the Assistant [WIN + SHIFT + A] 
It gives an error message saying 
```
You are Offline!
Please check your Internet Connection...
Error: Getting metadata from plugin failed with error: invalid_grant
```
I have setup the Assistant correctly and it was working fine for the first few days without any errors.

![image](https://user-images.githubusercontent.com/65074550/116177074-cfb5d080-a730-11eb-935e-cd55ac03ce61.png)

**Comment by yiqiangjizhang** [comment]
I have the very same issue! It stopped working after 1 day since I have installed it

**Comment by sumeshir26** [comment]
Hello @iDCoded and @yiqiangjizhang!

This issue is very common and the fix for it can be found [in the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error).

**Comment by yiqiangjizhang** [comment]
Sure! Just found it adn fixed it! Thank you for answering!!

> Hello @iDCoded and @yiqiangjizhang!
> 
> This issue is very common and the fix for it can be found [in the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#how-do-i-fix-invalid_grant-error).

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
