### ISSUE TITLE
GA not working!!! A javascript error...

### ISSUE THREAD

**Issue by yoga14s** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#346]
![515d1ae173a486fadfb5](https://user-images.githubusercontent.com/83391279/116511242-5a90f980-a8f0-11eb-9eb8-606ff87a8d60.jpg)
help me!!

**Comment by sumeshir26** [comment]
Hi @yoga14s! To fix this common issue, try going through [this section of the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0)

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
