### ISSUE TITLE
A Java script error occured in the main process

### ISSUE THREAD

**Issue by Whiteshadow-hacker** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#35]
I installed the google assistant (unofficial client) from the ubuntu software store. the installation was smooth, but when i try to launch the application from my applications menu, it opens a pop up saying that a java error occured in the main process i have attached a screen shot of the pop-up down here. and about my system specificaion, i use ubuntu 20.04.1 
![Screenshot from 2020-11-02 19-49-58](https://user-images.githubusercontent.com/56890843/97878430-a4839300-1d44-11eb-9a4a-9075165bf8de.png)

**Comment by Whiteshadow-hacker** [comment]
does anybody else face the same issue ?? please help me out if you fixed this error !!!

**Comment by Melvin-Abraham** [comment]
@Whiteshadow-hacker Well, I cannot reproduce this error. Also, to be honest, I have no idea what happened there. So, it might be a problem from electron's side. Anyway, I will probably add a commit for verbose logging in the console/file which could provide some idea where exactly error occurs. Until then, if you can clone this repo and run/build it, let me know if the error occurs again...

**Comment by Whiteshadow-hacker** [comment]
@Melvin-Abraham dude thank you very much!!! . i am really glad that you responded to my issue.
but just after i read your response i tried running the .appimage from your releases. even this time i got the very same error. please help me out. i would really love to use google assistant on my computer.
![Screenshot from 2020-11-03 18-37-35](https://user-images.githubusercontent.com/56890843/97988890-b415e100-1e03-11eb-80dc-160b13278fb0.png)

**Comment by Whiteshadow-hacker** [comment]
if you still want a clear idea of what's happening please see this video which I have screen recorded:: https://drive.google.com/file/d/1jmrBnHnA7ocWEgHo9vdrRuk2nvd2kQlB/view?usp=sharing

**Comment by Whiteshadow-hacker** [comment]
I tried the .exe in windows and it works just awesome !!!! after testing it in windows, now i feel even more curious to have it on my main computer in which i run ubuntu. i am really impressed by your program. please help to get this on my linux !!!!

**Comment by Melvin-Abraham** [comment]
@Whiteshadow-hacker Did you try cloning this repo and executing `npm start`?

**Comment by Whiteshadow-hacker** [comment]
dude, I was not completely into the idea of installing through npm but since you said, I tried and got a new error !!!
![Screenshot from 2020-11-04 22-52-34](https://user-images.githubusercontent.com/56890843/98144610-793da700-1ef0-11eb-8aa6-9488f17ca562.png)

**Comment by Whiteshadow-hacker** [comment]
if you want the log file of the error, i can provide it !!

**Comment by Whiteshadow-hacker** [comment]
and here is the error when i executed npm start::
![Uploading Screenshot from 2020-11-04 22-56-51.png…]()

**Comment by Whiteshadow-hacker** [comment]
and here is the error when I executed npm start ::
![Screenshot from 2020-11-04 22-56-51](https://user-images.githubusercontent.com/56890843/98146994-fa496e00-1ef1-11eb-9dfe-7800f1f80e34.png)

**Comment by Melvin-Abraham** [comment]
@Whiteshadow-hacker Can you try deleting the `package-lock.json` file and try again?

**Comment by Whiteshadow-hacker** [comment]
dude, can you please tell me how to execute npm run with the --no-sandbox flag ??, when i removed the package-lock.json it installed well but i dont know how to run it in root

**Comment by Whiteshadow-hacker** [comment]
dude, I figured out the problem !!! the error is neither with electron nor with your code !!! the problem is that it is not running in root !!!  when I try running it as a normal user it works good. but not as root ........ can you please tell me how to run it in root??, because i am a guy who always use root account !!!! anyways thank you very much for you support..... i became a fan of yours :+1:

**Comment by Whiteshadow-hacker** [comment]
if you can please tell me how to run it on root!!

**Comment by Whiteshadow-hacker** [comment]
or else if possible can you please release a .deb of the code ?? so it'll be easy for Debian users to install.

**Comment by Melvin-Abraham** [comment]
@Whiteshadow-hacker I think you are already a root user. You might notice a `#` instead of `$` at the end of the prompt meaning you are the root user.

**Comment by Melvin-Abraham** [comment]
Also, just out of curiosity, can you explain how you figured out what the problem was?

**Comment by Melvin-Abraham** [comment]
After deleting the `package-lock.json` you need to run `npm install` again. After that is done, you can proceed to `npm start`. Also, you don't need to use any flags when executing the start command...

Can you let me know if this causes any issues?

**Comment by Whiteshadow-hacker** [comment]
yes, dude, when I run npm start it says "Running as root without --no-sandbox is not supported" that's why i asked you how to run as root !!! I figured out the problem just by my instinct, i thought of running it in a normal user and it worked !!! so i concluded that there is some problem with the root. there is no error in what you said.

**Comment by Whiteshadow-hacker** [comment]
dude, i would really really love to use your google-assistant on my computer i have been searching a google-assistant setup for my linux for months. please help me run it on root !!!

**Comment by Melvin-Abraham** [comment]
Try changing `"start": "electron ."` under _"scripts"_ in **package.json** to `"start": "electron --no-sandbox ."` and try `npm start` again. Tell me if you encounter any issues...

**Comment by Whiteshadow-hacker** [comment]
dude, I am sorry to say but I got the very same error again !!!!
![Screenshot from 2020-11-06 19-38-51](https://user-images.githubusercontent.com/56890843/98375204-d3ad4380-2067-11eb-913c-c346f146b9ba.png)

**Comment by Melvin-Abraham** [comment]
@Whiteshadow-hacker Sorry for the delay. I have added a new commit for verbose logging which might give an idea at which point the error occurs. You can run the assistant with verbose logging in the console by executing the following line:

```
npm run start:verbose
```

_PS: Be sure to pull the latest changes from this repo beforehand._

**Comment by jfretin** [comment]
Hello there @Melvin-Abraham . I had the same error for some time, so I took the time to debug. It seems that the problem is that in some case, the window size is not what has been defined in onAppReady function (ie. 1000x420).

If I output window size as fetched in line 369 of app.js 
`let windowSize = mainWindow.getSize();`
it gives me 1001x421 ... So the division by 2 gives a float, and I think it's what throw the error.

If I force window size, for example:
` mainWindow.setPosition(
        (width / 2) - (1000 / 2) + x,
        (height) - (420) - 10
    );
`
it launches without an error!

I don't know, maybe it's a problem with the current theme maybe. I'm on Ubuntu.

**Comment by Melvin-Abraham** [comment]
@jfretin Thanks a lot for taking time to figure that out 🥳. I totally missed the information that `setPosition()` only accepts integer as an argument and also that the window size may vary from what is defined. So, a simple `Math.floor()` would fix this issue right away. Let me add a commit for the same. Again, thanks for this :)

**Comment by jfretin** [comment]
I confirm it now launches without error! Thanks! 

@Whiteshadow-hacker can you try this fix please?

**Comment by Whiteshadow-hacker** [comment]
@jfretin @Melvin-Abraham thank you very much for your efforts guys !!! i really appreciate that :smiley: but can you please be clear on what i have to do now to get it working ?, i am not a javascript programmer !!!

**Comment by Melvin-Abraham** [comment]
@Whiteshadow-hacker There's nothing that can be done about this as it is a bug within the app itself. This will be patched in the future release. For the time being you can pull all the latest changes from this repo (using `git pull origin master`) and build it locally (using `npm run dist`).

Hope that will work :)

**Comment by Whiteshadow-hacker** [comment]
@Melvin-Abraham thank you very much dude, I've become a fan of your application. i hope it'll come soon !!!! :smiley:
