### ISSUE TITLE
Settings button not working

### ISSUE THREAD

**Issue by gnpaone** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#351]
The settings button on the top left corner of the google assistant app release 1.0.0 rc2 is not working no matter how many times you click it.
![Screenshot (2612)](https://user-images.githubusercontent.com/78990165/116773173-7cfe5080-aa71-11eb-98f4-2b05c2ea1531.png)

**Comment by Melvin-Abraham** [comment]
Please refer [this section of the FAQ](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-setting-button-not-work).

**PS:** This issue has already been addressed as per b277437 within the source code.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
