### ISSUE TITLE
SOLVED - A new browser window doesn't open to get the Authentication Code

### ISSUE THREAD

**Issue by nickbird** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#352]
**Describe the bug**
Fails to open a new browser window permitting sign in to the test user google account to obtain the code to paste into the final part of the setup.

**To Reproduce**
The screen which states "a new browser window has opened" and asks you to paste an authentication code does not open the browser.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 21301 Windows Insider (but any version  I tried it on)
 - Version [e.g. 1.0.0-rc.2]

I fixed this by saving the JSON file from the Google Consent screen into the same directory as the Assistant (in my case it's C:\Users\nick\AppData\Local\Programs\Google Assistant). Using Windows Explorer I navigated to the Programs folder, .right clicked the Google Assistant folder and went to Properties - Security Tab. I added EVERYONE with FULL CONTROL to the folder and all files and then UNSET READ ONLY. I rebooted the machine and ran the assistant, opened settings, chose the JSON secret file again, and the browser opened, I signed in, got my code, pasted it in the Google Assistant and it worked as expected. 

I hope that helps someone!

**Comment by HackerSinhos** [comment]
What Browser are you using? if you don´t have Google Chrome, the authentication don´t open. But if You Have It´s a normally bug
