### ISSUE TITLE
launch on taskbar icon click

### ISSUE THREAD

**Issue by josh-65** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#359]
**Describe the solution you'd like**
I'm using this to replace Cortana, when pining the program to the task bar and clicking on it. it says that it already running instead of just do what the hotkey does. it should open the UI and start listening,

**Comment by sumeshir26** [comment]
Hi @josh-65!
The fix for this issue can be found by [building this project from source](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build) because the recent changes have not be released yet.

**Comment by josh-65** [comment]
cool ok. is there any plans for when it realing
