### ISSUE TITLE
Cannot use, error message: An unexpected exception has occurred🐛 BUG: 

### ISSUE THREAD

**Issue by yoda78121** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#365]
Hello, my assistant no longer works, it shows me this error message when ignore and I enter the key impossible to validate the key

![Capture d’écran 2021-05-09 225938](https://user-images.githubusercontent.com/83925350/117586735-4df37900-b11a-11eb-8677-1ca0640e7bc5.png)

please help me.

**Comment by obed9057** [comment]
if it called start before it was even running try re-launching it if it still does not work try reinstalling it it may have been an unauthorized modification to the installer that caused an unfixable error that can only be fixed by re-installing the latest update
