### ISSUE TITLE
"Okay Google" support

### ISSUE THREAD

**Issue by sumeshir26** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#375]
@Melvin-Abraham In the PR(#373) that just got merged, you said that there was no "Okay Google" support. I made [an issue in the Bumblebee repository](https://github.com/jaxcore/bumblebee-hotword/issues/16) and they just released a version with "Okay Google" support. Can we update the dependency and add support?

**Comment by Melvin-Abraham** [comment]
@sumeshir26 Thank you for mentioning that. I'll add it as well... ✌

**Comment by Melvin-Abraham** [comment]
Implemented in ec4b86b.
_Closing as resolved_
