### ISSUE TITLE
Wont open browser window

### ISSUE THREAD

**Issue by Ewan-droid** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#376]
Hello, I have installed and fallowed your instructions for setting this up, when the token page opens my browser wont open the tab for the sign in page. Yes it is my default browser lol! Thanks

**Comment by Melvin-Abraham** [comment]
This issue will be tracked in #352

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_

**Comment by Gala1996** [comment]
Hello i am not getting the token code

**Comment by sumeshir26** [comment]
@Gala1996 https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/784#issuecomment-1465096952
