### ISSUE TITLE
Error 403: restricted_client

### ISSUE THREAD

**Issue by iCloExecutable** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#382]
When i try to authorize the app for the token it says restricted_client

Authorization Error
Error 403: restricted_client
This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console https://console.developers.google.com/apis/credentials/consent?project=${your_project_number}

btw i was signed in with the same account as the one that i used to create the config file 

![opera_BxVmrqcIA1](https://user-images.githubusercontent.com/59067041/118189111-09cde480-b44a-11eb-8b5f-d89c5176141e.png)

**Comment by iCloExecutable** [comment]
i got it to work

**Comment by RaghavPoddar123** [comment]
create a new project

or add email and logo
