### ISSUE TITLE
Voice command not working when it should on Windows 10 Home

### ISSUE THREAD

**Issue by UnlistedPower** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#386]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by Melvin-Abraham** [comment]
@UnlistedPower Assuming you are using the downloaded package, this feature is not built in. It will be available in the next release though as it's implemented in the source but awaiting a release.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
