### ISSUE TITLE
@Melvin-Abraham 

### ISSUE THREAD

**Issue by sijey-praveen** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#391]
# This is not a issue can i use this image for my project! 

<img src="https://raw.githubusercontent.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/master/images/Assistant_light_dark.jpg" width="400px">

**Comment by Melvin-Abraham** [comment]
Please contact me at melvinredvirus@gmail.com.
