### ISSUE TITLE
New Browser Window Not Opening. Please HELP!

### ISSUE THREAD

**Issue by DreamHasBeenTaken** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#397]
Hey,
I just newly installed this software and it seems to be good until this step
![Untitled](https://user-images.githubusercontent.com/77918460/119828953-53bdcc80-bf18-11eb-9034-d20f1c335882.png)
I come to this step but the browser window never opens
For your information - I use Brave as my default browser and I also have Chrome. And also, I'm using Windows 7 64-bit
Would be really appreciated if any help can be given. AND A FAST REPLY WOULD BE GREAT!

**Comment by sumeshir26** [comment]
Hi @DreamHasBeenTaken, make sure that Chrome is your default browser and it is minimized for the token link to open. This requirement is present because this app is built on electron which is based on chrome. To retry in the release version, delete your key file path and try again.

**Comment by DreamHasBeenTaken** [comment]
It worked! thanks for you time

**Comment by DreamHasBeenTaken** [comment]
Also, i have one more question. Will this application require chrome even after the installation and setup?

**Comment by sumeshir26** [comment]
@DreamHasBeenTaken It will only be required when a link opens which is not many times.

**Comment by sumeshir26** [comment]
@DreamHasBeenTaken This issue then might be similar to #352.

**Comment by DreamHasBeenTaken** [comment]
@sumeshir26 
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/352#issue-873811938
i dont get this part where it says 'I added EVERYONE with FULL CONTROL to the folder and all files and then UNSET READ ONLY'
can you please explain what does this mean?

**Comment by sumeshir26** [comment]
@DreamHasBeenTaken 
>I added EVERYONE
This means that all emails are added everywhere during the setup process.
>With FULL CONTROL
This means that the Key File is not in a location with admin/superuser privileges.
>the UNSET READ ONLY
This means that you/the app has write permissions to both files.

**Comment by obed9057** [comment]
i am guessing you frogot that your supposed to go through the google cloud process before opening it

**Comment by DreamHasBeenTaken** [comment]
oh well! it is working, thanks!
