### ISSUE TITLE
Edges of the corners are not translucent

### ISSUE THREAD

**Issue by Piflyer** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#4]
**Describe the bug**
Whenever I launch the app, at every corner, they are not translucent, but white.

**To Reproduce**
1. Go to 'yarn start'
2. See error

**Expected behavior**
Clear and transparent rounded corners.

**Screenshots**
<img width="1022" alt="Screen Shot 2020-04-16 at 9 29 03 AM" src="https://user-images.githubusercontent.com/37424588/79465431-5639bd00-7fc9-11ea-83fa-f29e9d1adb07.png">

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina Version 10.15.1 (19B88)]
 - Version [1.0.0-rc.1]

**Comment by Melvin-Abraham** [comment]
A transparent background was explicitly added in the `app.js` as per this commit: 8994c73. Did you clone the latest commit?

**Comment by Melvin-Abraham** [comment]
> Yes, I am on the latest version and do see that in my app.js file. However, it is not working somehow

Well, I'm on a Windows machine, so, I can't test if it works but try out if `titleBarStyle: 'hidden'` inside `BrowserWindow` options in **"app.js"** works.

**Comment by Piflyer** [comment]
Sorry for the long wait, that does not work.

**Comment by Melvin-Abraham** [comment]
Well, maybe try adding the following line to `app.js` after **line 10**:

```js
app.commandLine.appendSwitch('enable-transparent-visuals')
```

If that doesn't work, let me know if `app.disableHardwareAcceleration()` works.

**Comment by Piflyer** [comment]
Doesn't work

**Comment by ayush06feb** [comment]
Can confirm that the issue is also present in Ubuntu 20.04 LTS (gnome desktop).

**Comment by Melvin-Abraham** [comment]
Seems like there is an issue with this version of Electron framework wherein the background color becomes white when the page is **reloaded**. _(PS: with vibrancy off)_

A workaround would be to relaunch the application via `app.relaunch()` but that will result in significant delay compared to reloading the page. But this is the only option I see.
