### ISSUE TITLE
Linux executables fail to launch 

### ISSUE THREAD

**Issue by the-quantum-nargle** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#40]
**Describe the bug**
I tried installing the snap but I got a pop up error textview with boxes on it. When I tried to open the AppImage I got a similar-looking text view but with proper text. As seen here:
![image](https://user-images.githubusercontent.com/63701425/100413606-d2d36480-309d-11eb-9a5b-aa480d0a115b.png)
I'm using Arch Linux and I've tried the same on XFCE and GNOME environments.

**To Reproduce**
1. Install Snap / AppImage
2. Run them

**Expected behavior**
They should've ran.

**Screenshots**
Screenshot of App Image attached above, here is a screenshot of snap:
![image](https://user-images.githubusercontent.com/63701425/100413767-25ad1c00-309e-11eb-96d8-63f0a9d5aaf9.png)

**Deskto:**
 - OS: Arch Linux [Manjaro] on Gnome/XFCE
 - Version: Kernel 5.9.11

**Comment by Melvin-Abraham** [comment]
Similar to issue #35

@the-quantum-nargle Can you try cloning this repo and run via `npm start:verbose`?
Let me know if the persists

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
