### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by obed9057** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#406]
I think it would be easier to install an updater in the next update so then you don't have to re-install the app and go through the process over and over and over every time there is a new version I rather just have a built-in updater so then it saves the device registration and all that so then all it has to do is replace the code with the new version then that's it I know its better said than done but it would make it easier

**Comment by sumeshir26** [comment]
@obed9057 The updater is already present. In settings, scroll all the way to the end and click 'check for updates'

**Comment by obed9057** [comment]
for me when i go in setting it show the paths I entered for it to function it does not show check for updates if this helps I'm on the black version
