### ISSUE TITLE
"Error: Tried calling start() before the ready event!" 

### ISSUE THREAD

**Issue by TheMoodBoardz** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#410]
**Describe the bug**
When The Program Is Launch For The First Time It Will Say "Unexpected Exception Occurred"  Saying It "Error: Tried calling start() before the ready event!". The Program Was Uninstalled & All Files Relating To This Were Removed Fully Followed By A Restart But Keeps Occurring.

**To Reproduce**
Steps to reproduce the behaviour:
1. Lunch Program
2. Whilst Being Redirected To Login To Google Account Error Will Pop-Up In Program

**Expected behaviour**
Without This Issue It Should Allow You To Signing & Fully Work

**Screenshots**
Please See Here [Screenshot.Redirect](https://i.imgur.com/Hd6gJrQ.png) For Screenshot

**Desktop (please complete the following information):**
 - OS: 19042.985
 - Version Win 10 ENT

**Additional context**

**Comment by coder-lg** [comment]
Try checking issue #185

**Comment by coder-lg** [comment]
![Screenshot_20210530_111248.jpg](https://user-images.githubusercontent.com/76845820/120093453-0750d780-c138-11eb-8408-0133b2b23eae.jpg)

**Comment by coder-lg** [comment]
Check the image above

**Comment by coder-lg** [comment]
@TheMoodBoardz or check it here: [FAQ](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens)

**Comment by TheMoodBoardz** [comment]
@coder-lg 

Ok Thanks For The Information

- Locked

**Comment by coder-lg** [comment]
Anytime.
