### ISSUE TITLE
hi i want to say you should add a code to it to open application of desktop from assistant also when user says open this website then open the website in browser 

### ISSUE THREAD

**Issue by hemang111** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#417]
**Is your feature request related to a problem? Please describe.**
NO 

**Describe the solution you'd like**
I WANT THAT ASSITANT SHOULD HAVE A FEAUTRE BY WHICH WE CAN OPEN PROGRAMS BY SAYING TO IT AND ALSO HAVE A OPTION TO VIEW IN BROWSER

**Describe alternatives you've considered**
ALSO I WANT TO SAY THAT ASSISTANT SHOULD RESPOND TO MICROPHONE ASSISTANT BUTTON ON HEADPHONES

**Comment by hemang111** [comment]
if you can add these enchancement it will be the best assistant for a pc available for win7/8/10

**Comment by hemang111** [comment]
also if assistant can open installed programs

**Comment by Melvin-Abraham** [comment]
Please add any description you want in the description as per the template. Avoid adding issue description in the title.

**Comment by hemang111** [comment]
SEE NOW

**Comment by hemang111** [comment]
Is your feature request related to a problem? Please describe.
NO

Describe the solution you'd like
I WANT THAT ASSITANT SHOULD HAVE A FEAUTRE BY WHICH WE CAN OPEN PROGRAMS BY SAYING TO IT AND ALSO HAVE A OPTION TO VIEW IN BROWSER

Describe alternatives you've considered
ALSO I WANT TO SAY THAT ASSISTANT SHOULD RESPOND TO MICROPHONE ASSISTANT BUTTON ON HEADPHONES

**Comment by hemang111** [comment]
BY THE WAY YOU ARE GOOD DEVELOPER

**Comment by Melvin-Abraham** [comment]
Duplicate of #33 and #41. Any progress regarding this will be tracked there...

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
