### ISSUE TITLE
Window closes during setup

### ISSUE THREAD

**Issue by josh-65** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#418]
**Describe the bug**
When running setup authorising it with my google account and AUTH key. my setup set to close on blur/click away witch makes it impossible to do.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have no AUTH files
2. Set to close on blur
3. Go through setup
4. wait for browser or file location needed
5. See it close and reset

**Expected behaviour**
It should be force set to normal behaviour during setup.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043.856
 - Version 1.0.0-rc.1

**Comment by josh-65** [comment]
Side note i cart change it it just wont save it

**Comment by ayaanvxm** [comment]
I have the same thing could you provide a solution for it?

**Comment by Melvin-Abraham** [comment]
If you are on Windows go to `%APPDATA%/Google Assistant`, locate the file `config.json`. There search for `"windowFloatBehavior"` and set the value to `"always-on-top"`, like so

```
"windowFloatBehavior":"always-on-top"
```

Quit the Assistant and launch again.

**Comment by lightningquick** [comment]
> always-on-top

You are a saviour. Been trying to fix this for a while
