### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by editinghero** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#427]
how to unistall google assistant not showing control panel

**Comment by sumeshir26** [comment]
Assuming you are on Windows 10, you can go to Settings > Apps > Apps & Features, then find Google Assistant(Or search for it) click on the app, and click 'Uninstall'

**Comment by editinghero** [comment]
**### i know this method but this isnt work so i asked you**
![Screenshot (16)](https://user-images.githubusercontent.com/69391940/122319004-9e41d000-cf3d-11eb-94af-ea75202080f0.png)

this is the proof
please provide uninstall.exe

**Comment by coder-lg** [comment]
Did you build it?

**Comment by coder-lg** [comment]
From Command Prompt?

**Comment by editinghero** [comment]
no Sent from Mail for Windows 10 From: LGSent: 17 June 2021 08:01To: Melvin-Abraham/Google-Assistant-Unofficial-Desktop-ClientCc: editinghero; AuthorSubject: Re: [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client] how to uninstall (#427) Did you build it?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by coder-lg** [comment]
Is the uninstaller at least present in Control Panel?
If not, how did you install it? Via `npm install`?

**Comment by editinghero** [comment]
yes i installed it from cdm

**Comment by editinghero** [comment]
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases

**Comment by editinghero** [comment]
i found the solution to unistall it

**Comment by editinghero** [comment]
to unistall i agian donloaded the application and installed it while installing it i found the path

**Comment by editinghero** [comment]
steps to unistall
1.unable show hidden files option in file explorer
![gf](https://user-images.githubusercontent.com/69391940/122403817-4b4b3580-cf9c-11eb-821d-5a16963f8803.png)

**Comment by editinghero** [comment]
2.go to this path
C:\Users\!!!!!!!!!!Y**our  desktop User Name** !!!!!!!!!!!!\AppData\Local\Programs\Google Assistant

**Comment by editinghero** [comment]
3. click on unistall.exe
![dfdfxfxc](https://user-images.githubusercontent.com/69391940/122404132-96654880-cf9c-11eb-91bc-d7f89acae3b4.png)

**Comment by editinghero** [comment]
5.Unistalled succesfully
![Untitled](https://user-images.githubusercontent.com/69391940/122404202-a5e49180-cf9c-11eb-8d8c-618d9b52a063.png)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_

**Comment by editinghero** [comment]
Thanks this thread may help anybody

**Comment by arnabb1swas** [comment]
how to uninstall it in ubuntu??

**Comment by editinghero** [comment]
this much old thread but i got mail so ill tell you

**Comment by editinghero** [comment]
you may follow the same process 
if you have uninstaller file present then just do it
if not then again install it then find unistaller file and done
