### ISSUE TITLE
More instructions needed.

### ISSUE THREAD

**Issue by Dvalin21** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#43]
<!-- 
NOTE:

Limit this issue to not more than **one bug report** for clarity and discoverability.
Keep the issue concise and clear as much as possible.

Hello and thank you for the hard work in this project.  The only issue that Im having is when I get to the part its suppose to issue a token, i use my account, but it says permission denied, either the dev didnt give me access or Google hasn't reviewed it yet.  Sounds like somethings may have changed when you last updated the instructions.  Thanks in advance for your help.

**Comment by Melvin-Abraham** [comment]
This issue neither contains any verbose description nor does it have any descriptive title.

Hence, closing as **invalid**.

This issue will be reopened once all the above conditions are met. In such case you can @mention. Also, use issue template if possible to keep this issue consistent.
