### ISSUE TITLE
unable to submit token 

### ISSUE THREAD

**Issue by nawinlol3211** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#437]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by morgenman** [comment]
I also have this issue, Submit on the get token screen does not work

**Comment by sumeshir26** [comment]
Hi @morgenman,
Please check #88.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
