### ISSUE TITLE
Option to disable the indicator and launch the app from the launcher (Linux)

### ISSUE THREAD

**Issue by logant547** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#44]
Please give us the option to disable the indicator, so when you click on the icon's launcher it runs instead of starting it through the indicator menu.

**Comment by Melvin-Abraham** [comment]
@logant547 That seems like a reasonable request. Though, tray indicator will not be removed but instead an option to launch it directly on the first run will be added soon.

**Comment by logant547** [comment]
OK, thanks.
