### ISSUE TITLE
Personal Results

### ISSUE THREAD

**Issue by Carteeair05** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#446]
Hi,
I can't ask the assistant anything related to personal results. She sends a notification to my phone which asks me to turn on personal results. I have tried turning it on multiple times but it will not work.

**Comment by technom16** [comment]
yeah man same goes with me !!

**Comment by milindbl** [comment]
Same issue for me, pressing allow on the phone does nothing, I just get a new notification whenever I ask something that requires personal results again.

**Comment by DeanTrivi** [comment]
The solution [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184) worked for me.

**Comment by Carteeair05** [comment]
Thanks a million, this worked!
