### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by sumeshir26** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#447]
Hi, haven't seen any commits in a month or you responding to any issues/discussions. Just wondering if you are still working on this app.

**Comment by Melvin-Abraham** [comment]
This project is definitely active. I have been a bit busy lately due to which I wasn't able to give much time for this project. But I am now trying to manage it and will resume commiting and interacting soon. Thank you for the concern... 😊😊😊

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
