### ISSUE TITLE
[Issue][Ubuntu 20.04] Not Working Mic or Config Button.

### ISSUE THREAD

**Issue by gui679** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#45]
**Describe the bug**
I've just installed by snap command, as the main page says...
When I open it from the tray, it opens normally but i can't send commands, the mic button doesn't work, neither the config button.
the screen is not frozen because the animations works, the close and maximize button works, and the text box works (but not send commands anyaway)
i've opened from the terminal just to see if it has errors, but not relevant, see the screenshot.

**To Reproduce**
1. Open g-assist from terminal or by shortcut
2. launch app from the tray
3. Not working buttons.

**Expected behavior**
Mic buttons to send commands that i've typed (yes, the type is working)

**Screenshots**
![image](https://user-images.githubusercontent.com/15015995/100661348-1b0ab500-3332-11eb-866b-bb85adc9bd73.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS, kernel 5.9.8-050908-generic]
 - Version [1.0.0-rc.2]

**Comment by morozdan2003** [comment]
I had the such problem, but it solved by clicking "Get Started" button. Did you tried to do such action?

**Comment by Melvin-Abraham** [comment]
@gui679 The settings button is intentionally disabled since when you first install and run the assistant no config file is created. You will need to press "Get Started" and "Proceed" button successively to continue.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved._
