### ISSUE TITLE
it is successfully working on windows 11, but it can be more powerful if it can open apps on voice commands like it do in android.

### ISSUE THREAD

**Issue by KavyanshJain** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#451]
This is a great project and it is successfully **working on windows 11** which is a good news. But I want a enchantment of it able to open apps on commands like it do in android normally. I think we use **run app** of windows with assistant to open apps which we command or any other possible way to do it. But if it done it will be a great advancement of the assistant client

**Comment by Melvin-Abraham** [comment]
@KavyanshJain This is definitely one of the milestones. This feature request has already been addressed in #33. Any progress regarding this will be tracked there :)

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
