### ISSUE TITLE
I can not talk to Google

### ISSUE THREAD

**Issue by cookiex0x** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#452]
I clicked on the Microhone on the Application but when i talk the Assistant Cant hear me. My micrphone is active!

**Comment by Melvin-Abraham** [comment]
Can you send a screenshot regarding the issue you are facing...

**Comment by MrKampfer** [comment]
Same problem here

> I clicked on the Microhone on the Application but when i talk the Assistant Cant hear me. My micrphone is active!



> I clicked on the Microhone on the Application but when i talk the Assistant Cant hear me. My micrphone is active!

same problem here

**Comment by MrKampfer** [comment]
> I clicked on the Microhone on the Application but when i talk the Assistant Cant hear me. My micrphone is active!

Same problem here

**Comment by Melvin-Abraham** [comment]
Can you check if your device's microphone can detect audio in other applications?

**Comment by Melvin-Abraham** [comment]
Possibly related to #495

**Comment by Melvin-Abraham** [comment]
_Closing as stale_

**Comment by marioegghead2** [comment]
Closing as stale
