### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by hallowiegehtsso** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#456]
When i try to run the assistent after the instalation im getting an java script error
![image](https://user-images.githubusercontent.com/68867941/126503361-fc1dd519-75c0-4b72-b86e-b5deeca78e04.png)

**Comment by sumeshir26** [comment]
Hello @hallowiegehtsso,
Please find more information [in the FAQ's](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0).

**Comment by Melvin-Abraham** [comment]
The patch will be released in the next update...

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
