### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dxkyy** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#468]
After I install the Assistant and click on "Launch", I get an error and it doesn't work.

`A JavaScript error occurred in the main process
Uncaught Exception: TypeError: Error processing argument at index 0, conversion failure from
at Timeout.onAppReady (as_onTimeout] (C:\Users\NAME\AppData\Local\Programs Google Assistant resources app.asar app.js:192:16)
at listOnTimeout (internal/timers.js: 531:17) at processTimers (internal/timers.js:475:7)`

**Comment by coder-lg** [comment]
Try building via NPM. If you want installed edition, you got to meddle with your screen resolution which is uncomfortable or build with NPM, which worked for me.

**Comment by coder-lg** [comment]
/ping @dxkyy if it worked, please close the issue. If it didn't, tell the result here.
