### ISSUE TITLE
Mic input doesn't work

### ISSUE THREAD

**Issue by Apolycious** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#470]
Mic input doesn't work when I speak

**Desktop:**
 - Chrome: 92.0.4515.107
 - Version: 1.0.0-rc.2

**Comment by coder-lg** [comment]
Same, except:
I use multiple browsers, which are:

- Chrome
- Vivaldi
- Brave
- Chromium

enabled the toggle in the settings but it doesn't respond to me, it responded to the system audio once or twice though

**Comment by Apolycious** [comment]
what kind of settings should I toggle?

**Comment by coder-lg** [comment]
Well, in the settings, there is a toggle named Hey Google/Ok Google but never worked for me. It works only on system audio maybe but failed for me. You try it.
