### ISSUE TITLE
Error: Assistant init failed

### ISSUE THREAD

**Issue by mindingulove** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#475]
After one day of using the app flawlessly in mac os I got:

Unexpected Exception Occured
The Assistant failed to initialize due to some unexpected error. Try reloading the assistant.
 Error: Assistant init failed

<img width="1271" alt="Screen Shot 2021-08-04 at 1 02 10 AM" src="https://user-images.githubusercontent.com/24813488/128120502-b24ee4e3-2d3b-465b-a47e-b4ed6bf59885.png">

couldn't find a similar issue. 
Does anyone have any ideas?
thank you

**Comment by coder-lg** [comment]
Have you tried relaunching?

**Comment by mindingulove** [comment]
I guess the problem is the id token. Tried adding a new one and got it working now. Thank you

**Comment by coder-lg** [comment]
Well, make sure you follow the instructions in the Wiki correctly and do it as it is.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_

**Comment by aumgagan** [comment]
same problem

**Comment by aumgagan** [comment]
> _Closing as resolved_

I don't understand what are you saying?
