### ISSUE TITLE
Add Russian Language

### ISSUE THREAD

**Issue by morozdan2003** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#48]
**Is your feature request related to a problem? Please describe.**
Google Assistant officially supports Russian language, but your app isn't. Google Home device supports Russian language too, so it supposed to be inplemented in Google Assistant API.

**Comment by Melvin-Abraham** [comment]
@morozdan2003 This application uses Google Assistant SDK in the core which is different from the official Google Assistant Client. Thus, it has limited number of support for languages. You can track the language support for Google Assistant SDK [here](https://developers.google.com/assistant/sdk/reference/rpc/languages).

Although, you can use a workaround. If you have an Android Device, you can set the Language to Russian in Google Assistant Settings. This change will be directly reflected in this client and you'll be able to use Russian as a language.

_PS: Make sure you use the same Google account to authenticate._
