### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by QuestYouCraft** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#480]
What are the minimum system requirements (in particular, the minimum OS version and processor architecture) for running the program? @Melvin-Abraham, on Windows 7 x86, the program does not run.

**Comment by Melvin-Abraham** [comment]
@QuestYouCraft The application works just fine in Windows 7 (both x86 and x64). Once you run the application, it is hidden in the tray by default and could be invoked anytime by pressing <kbd>Windows Key</kbd> + <kbd>Shift</kbd> + <kbd>A</kbd>.

**Comment by QuestYouCraft** [comment]
Perhaps I explained it incorrectly. The Google Assistant installer does not start.

**Comment by coder-lg** [comment]
Well, @QuestYouCraft I don't know maximum kind but I think it works in Windows 7+, Mac OS Mojave and above and maybe latest Linux distos. But I do know that it works on computers running Windows 7 and above.
