### ISSUE TITLE
Windows microphone constantly being used

### ISSUE THREAD

**Issue by sgm-17** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#482]
**Describe the bug**
Whenever the app is running in the background Windows shows the microphone icon in the system tray indicating Google Assistant as using the microphone at all times. 

**Expected behavior**
Only shows the icon when the Assistant is actively listening after being initiated by the command Win+Shift+A.

**Desktop**
 - OS: Windows 10 21H1 Build 19043.1110
 - Version 1.0.0-rc.2

**Comment by Melvin-Abraham** [comment]
This has been fixed in the codebase but not released yet. It will be released later. Meanwhile, you can build the project to test it out.
_Closing as resolved_
