### ISSUE TITLE
Not saving settings

### ISSUE THREAD

**Issue by minkyman1** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#5]
Hi, sorry to bother you

My save settings wont work. I've put in the Key File Path and clicked save, it then autmatically puts the saved token path as the tokens.json but when I click the save button nothing happens. It wont work work, please please help as it was working on my other PC.

**Comment by Melvin-Abraham** [comment]
Hey, @minkyman1 👋. Try this to get more information on what's happening:

Make sure you have cloned the latest commit of this project, after which you must execute the line `npm start` to start the application.

In the settings, under "DEVELOPER TOOLS" section, click the "Open DevTools" option. Then, click "Save". You might get an error on the devTools console which will let you know the actual problem. Share the devTools log here, if you still need help... 😊

**Comment by minkyman1** [comment]
Hey thanks for the quick reply! Sorry, Let me go through what I have done:

Note : I used the installer, I didn’t build it myself

Made gmail account and setup all the API stuff, downloaded the key file. Opened the assistant and went to settings, put the key file in the path (I didn’t get given a token file from the API setup). Then I clicked saved, it asked for me if I would like to automatically put the same path for token, I clicked yes. Then I clicked save but nothing happened.

Firewall and anti virus are both on, not sure but that might be the problem?

**Comment by minkyman1** [comment]
Would I be able to do the log with the exe file? As I said I didn’t build it

**Comment by minkyman1** [comment]
![yUT7MI84Dp](https://user-images.githubusercontent.com/36448068/81427180-53f2fa80-9152-11ea-81a6-ab92ba1f0d07.gif)

**Comment by minkyman1** [comment]
Tried re install and install it, same thing

**Comment by Melvin-Abraham** [comment]
@minkyman1 Check if you have **"Google Assistant"** directory in `%APPDATA%`.

**Comment by minkyman1** [comment]
![image](https://user-images.githubusercontent.com/36448068/81429896-6c651400-9156-11ea-9e9e-9e00c1121d5a.png)

Yes in roaming not in local @Melvin-Abraham

**Comment by minkyman1** [comment]
Its rlly annoying as it was working fine on my other PC and its so usefull

**Comment by Melvin-Abraham** [comment]
@minkyman1, I think if you clone the repo and run it with the devTools open, it would be easy to pinpoint any exceptions that may occur while you are saving the settings.

Just clone, run and share the logs :)
Let me know if you have any problem in any of the steps

**Comment by minkyman1** [comment]
How do you run with DevTools? Ive installed with npm and run it. still same

**Comment by Melvin-Abraham** [comment]
> How do you run with DevTools? Ive installed with npm and run it. still same

`Ctrl + Shift + I`

**Comment by minkyman1** [comment]
Aha!
![yUT7MI84Dp](https://user-images.githubusercontent.com/36448068/81436529-8e17c880-9161-11ea-8533-b638f6fbac0f.gif)
Srry for asking so many questions

**Comment by minkyman1** [comment]
![vbu4i6nn1N](https://user-images.githubusercontent.com/36448068/81436572-9e2fa800-9161-11ea-9cca-8c604d3040d9.gif)

Aha! Sorry for asking so many questions :(

**Comment by minkyman1** [comment]
![image](https://user-images.githubusercontent.com/36448068/81436630-b4d5ff00-9161-11ea-8ab8-7d618e081ef8.png)

**Comment by minkyman1** [comment]
How would I fix this?

**Comment by Melvin-Abraham** [comment]
@minkyman1, Thank you for the contribution. The issue is being caused since "config" is not initialised in your case as it is your first time running the program and so initialisation is halted but in the settings, the _"isNew"_  option inside **"config"**  is being updated while saving.

This issue will soon be fixed.

So, for the time being, you can create `config.json` inside `%APPDATA%/Google Assistant` and paste the following inside it:

```json
{ "keyFilePath": "", "savedTokensPath": "", "forceNewConversation": false, "enableAudioOutput": true, "enableMicOnContinousConversation": true, "startAsMaximized": false, "launchAtStartup": true, "alwaysCloseToTray": true, "enablePingSound": true, "enableAutoScaling": true, "enableMicOnStartup": false, "hotkeyBehavior": "launch+mic", "theme": "dark" }
```

Finally, relaunch the assistant.

**Comment by minkyman1** [comment]
Cheers so much! Finally working!
