### ISSUE TITLE
I want a new update

### ISSUE THREAD

**Issue by marioegghead2** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#500]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when google assistant didn't hear my voice

**Describe the solution you'd like**
Ask permission to access your voice before using it.

**Describe alternatives you've considered**
Make google assistant say 
```
Hello! Before we get started, I need to access your voice and microphone.
```

**Additional context**
Done.

**Comment by im-coder-lg** [comment]
So, in a nutshell, you want Google Assistant to ask for permission to use your microphone?

**Comment by marioegghead2** [comment]
yes xD

**Comment by im-coder-lg** [comment]
then this IS a feature request. @Melvin-Abraham is this possible, like how Android and iOS asks for permission for microphone and all, is this possible? And also, the `bug` label can be removed, the workflow has errors I guess...

**Comment by Melvin-Abraham** [comment]
@marioegghead2 Can you confirm if you are addressing issue #30?

**Comment by marioegghead2** [comment]
yes

**Comment by marioegghead2** [comment]
>kjdjsdsg
              > jkfdxjhgbdfhbjkfdfd

**Comment by marioegghead2** [comment]
:rage2:

**Comment by Melvin-Abraham** [comment]
> yes

This issue is already fixed in the codebase.
_Closing as resolved_
