### ISSUE TITLE
Launching programs in Windows

### ISSUE THREAD

**Issue by Efikun** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#504]
Is it possible to launch programs through google assistant in windows? It didn't seem to work for me and I am wondering if there is a way to configure that. I used a voice command like "open discord" or "open Powerpoint".  Is there a way to configure it to launch a certain app on certain voice command? That would be great.
Thanks!

**Comment by im-coder-lg** [comment]
No, since the app isn't integrated deeply, it is not possible.

**Comment by Melvin-Abraham** [comment]
@Efikun This is definitely a milestone that is being planned. At the time being this is not implemented and will be worked on sometime later. But I guess Windows integration might probably roll out after the Linux and MacOS ones.

**Comment by Efikun** [comment]
Alrighty, thanks! I'll be looking forward to it.
Thank you for your work, I'm really enjoying having Google assistant on my desktop as well :)

**Comment by Littlemac123** [comment]
the app should be able to know what your saying when you say "Launch" regardless if google actually knows what your doing or not. like there should be a way to make custom commands like "launch" "firefox" and then the app can just auto mute google cause it knows that you didn't care what google thinks, just the fact that its using googles servers to register your voice. then just load firefox
