### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by HimanM** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#51]
when i click mic button or when i do a random search. 

[2020-12-12-20-07-49.zip](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/files/5683250/2020-12-12-20-07-49.zip)
here is the video and i already set my tokens and things but not working

**Comment by Melvin-Abraham** [comment]
@HimanM Can you open DevTools  via **Ctrl + Shift + I** _(after launching the assistant)_ and share the error log?

**Comment by HimanM** [comment]
Ah thanks man i found the problem and i accidently disabled the api 😂.
Sorry for the interruption.

Great work btw

**Comment by Melvin-Abraham** [comment]
@HimanM Thank you for confirming.
_Closing this issue as resolved_.
