### ISSUE TITLE
[🐛 Bug]: Window closes after clicking "Automatically set a path"

### ISSUE THREAD

**Issue by LonelyKing01** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#515]
### What went wrong?

After a click "Automatically set a path" the window closes, and when I open it again it resets. 

### What did you expect to happen?

I expected to see the "Get a token!" screen, but I didn't.

### Steps to reproduce the bug

Click on Google Assistant icon
Select Settings
Select the path
Select Save
Select "Automatically set a path"
Window closes(error)

### App Version

v1.0.0-rc.2

### OS Version

Windows 10 Pro

### Pre-submission Checklist

- [x] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one paricular bug or issue

**Comment by im-coder-lg** [comment]
Can you share a screenshot please?

**Comment by im-coder-lg** [comment]
One minute... Did you download Google Assistant from the Releases page or compiled it from source?

**Comment by LonelyKing01** [comment]
> One minute... Did you download Google Assistant from the Releases page or compiled it from source?

Hummm

I did exactly what's on this website (step by step): https://www.lifewire.com/google-assistant-on-windows-4628292

**Comment by LonelyKing01** [comment]
> Can you share a screenshot please?
Yes. The 1st is before clicking "Automatically set a path"
![image](https://user-images.githubusercontent.com/90360746/132768264-42b0a24c-fd85-4469-aa56-7c83fc0ca05a.png)

The 2nd is what comes after 
![image](https://user-images.githubusercontent.com/90360746/132768415-2f2e4732-f8be-41ec-ad60-9c5c07c26448.png)

It doesn't show any message box, or something, it simply closes

**Comment by Melvin-Abraham** [comment]
@LonelyKing01 Based on the issue, I think you have the Window Float Behavior set as "Close on Blur". To fix this, go to **Settings** > **Window** > **Window Float Behavior** and change the value from _"Close on Blur"_ to any other option and give it a try again.

**Comment by LonelyKing01** [comment]
> @LonelyKing01 Based on the issue, I think you have the Window Float Behavior set as "Close on Blur". To fix this, go to **Settings** > **Window** > **Window Float Behavior** and change the value from _"Close on Blur"_ to any other option and give it a try again.

It worked, and now an error message is appearing, can you help me?

![image](https://user-images.githubusercontent.com/90360746/132925128-9c246d39-a61b-4041-b3ce-4878e7f40da3.png)


Even if I click "ignore" after I paste the token and select "submit" nothing happens.

**Comment by im-coder-lg** [comment]
Ya this one solution is in the FAQ.

**Comment by im-coder-lg** [comment]
@LonelyKing01 look at this(taken from the FAQ:
![image](https://user-images.githubusercontent.com/76845820/133031582-5aed84e7-02d1-4e64-a8c2-5e12de04fc0c.png)
There are two options. One is to compile the app(suggested since everything is latest) or the other is to follow the instructions given in the FAQ or the image above(taken from faq)

**Comment by LonelyKing01** [comment]
> @LonelyKing01 look at this(taken from the FAQ:
> ![image](https://user-images.githubusercontent.com/76845820/133031582-5aed84e7-02d1-4e64-a8c2-5e12de04fc0c.png)
> There are two options. One is to compile the app(suggested since everything is latest) or the other is to follow the instructions given in the FAQ or the image above(taken from faq)

Now it's working, thank you very much.
