### ISSUE TITLE
[🐛 Bug]: Get started button doesn't appears on windows 10

### ISSUE THREAD

**Issue by El-mou33** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#522]
### What went wrong?

Doesn't appears the get started button when I launch the assistant for the first time. Also the wheel doesn't works.

### What did you expect to happen?

The get started button doesn't appears.

### Steps to reproduce the bug

1. Install
2. Launch
3. Nothing else happends

### App Version

v1.0.0-rc.2

### OS Version

Windows 10 Home 21H1 19043.1165

### Relevant Assets

![image](https://user-images.githubusercontent.com/90722688/133319966-69e7a1da-22b1-4281-98a4-e8db5b5c51c1.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one paricular bug or issue

**Comment by im-coder-lg** [comment]
Looks like something is corrupt, try reinstalling Google Assistant or build it from the source code.

**Comment by El-mou33** [comment]
> Looks like something is corrupt, try reinstalling Google Assistant or build it from the source code.

I tried to reinstall, reboot and nothing happened.

**Comment by im-coder-lg** [comment]
Then, try building from the source code and try again. If that also doesn't work, click <kbd>Windows</kbd> + <kbd>R</kbd> and type `%appdata%/Google Assistant`. It will open the directory. Cceck if it exists in the first place. If it does, delete it. Then, reinstall GAUDC from the installer you built from source code(found inside `dist`) or close GAUDC and then, open the folder where you got the source code, go inside dist\win-unpacked and run Google Assistant.exe

**Comment by Melvin-Abraham** [comment]
@El-mou33 After starting the application, press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> to open the DevTools. Then you can head over to the `Console` tab and share the error logs here so that we can assist you according to the root cause of the issue.

**Comment by El-mou33** [comment]
![image](https://user-images.githubusercontent.com/90722688/133641350-2ba7b6ec-e10c-4ea7-9055-7c2d077eefaf.png)

**Comment by El-mou33** [comment]
![image](https://user-images.githubusercontent.com/90722688/133642985-59394ffa-2da8-48e5-8f6b-b6427608723e.png)

I´m so sorry. I'm stupid. For the first time I run the program I should execute as an administrator and I didn't do that. Now everything works. I'm so sorry again.
