### ISSUE TITLE
[🐛 Bug]: get no response from google assistant

### ISSUE THREAD

**Issue by Voten641** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#523]
### What went wrong?

as in the title, I didn't get any answer from the assistant when I asked him a question
https://imgur.com/a/3AwCwy9

### Steps to reproduce the bug

1. Open assistant Win+Shift+a
2. type "weather" or something else
3. no respond from assistant

### App Version

v1.0.0-rc.2

### OS Version

Windows 11 Pro Build 22449.rs_prerelease.210827-1350

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one paricular bug or issue

**Comment by im-coder-lg** [comment]
> ### Steps to reproduce the bug
> 1. Open assistant Win+Shift+a
> 2. type "weather" or something else
> 3. no respond from assistant

You mentioned that if you _type_ `weather`, it doesn't respond. Yes, it doesn't because it responds to _voice_ commands. I assume you _can_ change them in the settings.

**Comment by im-coder-lg** [comment]
![image](https://user-images.githubusercontent.com/76845820/133453765-d5778c0c-1f3b-41d3-8ed5-097b9adb66b3.png)
Yeah, that is possible. Enable audio output for typed queries

**Comment by Voten641** [comment]
but i dont want to user voice, i want to type queries and read what assistant showed me

**Comment by im-coder-lg** [comment]
Yes, that is what queries are called. If you type "Weather", the search is called query. If I type "Rickroll me" or "What is my name?"(sometimes I do), that is a query. Anything you ask the Assistant will be queries. That is why Google sometimes says "search queries" since it considers your search as a query.

**Comment by im-coder-lg** [comment]
Tried to tell the same thing... Can removing the configuration for a fresh reset of Google Assistant work? This seems relatively new...

> Note: I have seen this error sometimes for the Personal Requests issues. It is fixed now thanks to people in the community(the gist was documented but the original credit is mentioned) but if it is not added yet then this would occur. Looks like it just widespread-ed to this... Let me try recreate efforts.

**Comment by im-coder-lg** [comment]
PS: Looks like this wasn't compiled from source so I have to get the installer.

**Comment by Voten641** [comment]
> @Voten641 After asking/typing the query, press Ctrl + Shift + I to open the DevTools. Then you can head over to the `Console` tab and share the error logs here so that we can assist you according to the root cause of the issue.

Thanks, i found that i enabled google assistant api in wrong project, now everything is working well

**Comment by im-coder-lg** [comment]
What? I didn't understand that one bit. Are you trying to mean that you enabled the Assistant API in another Google Cloud project?
Well, be careful from now and try using the compiled version that you get from the source code, you get a whole lot of bug fixes. Remember, you don't need to suffer or anything, just authenticate it as usual, everything is there by default so you don't need to worry, the guide is in the README, npm is on Node JS(google that if you need it), yarn can be installed via `npm i -g yarn` and after `npm install && npm run build` you can open Explorer or File Manager, go to the Google Assistant folder, go to `dist\win-unpacked` and run Google Assistant.exe which starts the newly-compiled, unzipped GAUDC app. You can also run the installer located in `dist` to install the compiled app.
