### ISSUE TITLE
Can't save the key file path

### ISSUE THREAD

**Issue by junx2000** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#524]
When I try to click on save button, I hear the typical windows 10 sound, when you can't open a file or have done something wrong. I tried with admin. access and I've received the same behaviour. And when there isn't a path, I can save without any problem.
I found that is the background sound. https://youtu.be/sRTvrtuuGJQ?t=176

**Comment by im-coder-lg** [comment]
Hey @junx2000 can you try sharing a video on _how_ it happens and a screenshot of DevTools(click the GAUDC app, and hit Ctrl+Shift+I)? Or can you show a screenshot of the app?

**Comment by junx2000** [comment]
@im-coder-lg I solved the issue, I've had problems with windows (openning .txt with notepad prinstalled, advance config in control panel doesn't open, etc). So Last night I reinstall w10, and everything work fine :)
