### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by jesusvallejo** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#525]
### What went wrong?

Token set up fails if the Key File Path is in the installation path. Works qhen in any of the user paths.This is do to a lack of permissions.

### What did you expect to happen?

Maybe an appdata file path could be created, you tell where to find the file to the program and it copies the .json to ist appdata file path.

### Steps to reproduce the bug

1. Copy the .json to installation path 
2. Retrieve the token 
3. Configuration will fail

### App Version

v1.0.0-rc.2

### OS Version

Windows 10 pro 2004 19041.1237

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one paricular bug or issue

**Comment by im-coder-lg** [comment]
Actually, you don't need to put it inside the installation path, put it normally in a folder like Documents or your desktop or if you have another drive, put it inside that.

**Comment by jesusvallejo** [comment]
> Actually, you don't need to put it inside the installation path, put it normally in a folder like Documents or your desktop or if you have another drive, put it inside that.

yes i know, and i have placed it under the appdata path, at first i though it was a bug , but its more of an inconvenience to have the file on other directories but i guess i will close it.
