### ISSUE TITLE
Closes on blur so can't enter new token[🐛 Bug]: 

### ISSUE THREAD

**Issue by einiman** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#529]
### What went wrong?

I have to enter a new token, but I've set the program to close on blur, so it automatically closes every time I open it as it redirects to the web browser. Is there a way I can disable close on blur when I can't get to the setting page?

I found a dublicate issue, but there was no response
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/331

### Steps to reproduce the bug

Enable close on blur, then delete the token file

### App Version

v1.0.0-rc.2

### OS Version

Windows 10 Pro 21H1 19043.1237

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one paricular bug or issue

**Comment by im-coder-lg** [comment]
Hey, sorry for the late reply, I noticed this but I forgot about the issue.
I think I know a solution. You will have to reset GAUDC or configure the config.json file where the settings are stored. I suggest changing. 
1. Hit <kbd>Windows</kbd> + <kbd>R</kbd>
2. Search for one `config.json`
3. Right click and open on your favourite text editor.
4. Now, hit <kbd>Ctrl</kbd> + <kbd>F</kbd> or <kbd>F3</kbd> to open the Text finder.
5. Search `windowFloatBehaviour` and locate it.
6. Now, it will look like this:
```json
"windowFloatBehavior":"closeOnBlue"
```
7. Change `closeOnBlur` or anything inside it to `always-on-top`. For the time being.
8. Restart GAUDC
9. Try authenticating.
***
If it worked, tell us over here. If it didn't, try this:
1. Open the app
2. Hit <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>, head to the `Console` section in that new window and share us a screenshot of it.

**Comment by einiman** [comment]
Thanks, this worked perfectly!

**Comment by Melvin-Abraham** [comment]
Re-opening this issue as the bug is still to be addressed in the application level. This issue will be closed later once the root issue is fixed...

**Comment by im-coder-lg** [comment]
Till then, why not document this in the FAQ? That could be helpful... :thinking:

**Comment by im-coder-lg** [comment]
Is it fixed now?
