### ISSUE TITLE
Problem with Google Assistant starting up.

### ISSUE THREAD

**Issue by KristianImposter** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#535]
Hello! So, I just uninstalled Google Assistant due to the fact that every time I tried to start it up, it just wouldn't show the Google assistant.
Could this be fixed in a future update? Thanks!

**Comment by im-coder-lg** [comment]
Have you tried resetting the config? Try deleting this folder: %appdata%\Google Assistant and try again.

**Comment by Melvin-Abraham** [comment]
Which OS are you running the app on? Can you specify the steps you took since launching the app from launcher and/or system startup? Did you try starting up using <kbd>Windows Key or Cmd</kbd> + <kbd>Shift</kbd> + <kbd>A</kbd>

**Comment by KristianImposter** [comment]
I am using Windows 11, and, no, I have not tried with Windows Key or CMD + Shift + A. I will try it tomorrow. I will reply if it works and I will close this thread if it works.

**Comment by KristianImposter** [comment]
Nope, did not work at all. Could you check out the code?

**Comment by KristianImposter** [comment]
Never mind, it worked, thanks for the help!
