### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by mrtajniak** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#538]
### What went wrong?

macOS High Sierra : "Tried calling start() before the ready event!" after clicking ignore cannot click submit button with correct token

### Steps to reproduce the bug

1. Setup app as normal on macOS High Sierra

### App Version

v1.0.0-rc.2

### OS Version

macOS High Sierra 10.13.6 (17G14042)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one paricular bug or issue

**Comment by sumeshir26** [comment]
@mrtajniak Please check the FAQs

**Comment by im-coder-lg** [comment]
Your answer can be found in the FAQs [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-does-the-get-token-screen-fail-saving-tokens)
