### ISSUE TITLE
not working out of the box

### ISSUE THREAD

**Issue by OmarShawky1** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#54]
**Describe the bug**
not working out of the box when i installed from snap

**To Reproduce**
1.just try to run it (no matter what permissions you give it)

**Desktop (please complete the following information):**
 - OS: Elementary OS Hera 5.1.7

**Comment by Melvin-Abraham** [comment]
@OmarShawky1 By default the assistant will be hidden and minimized to tray when launched. You will need to follow either steps to launch the assistant after running the application:

- Try launching the assistant with the keyboard shortcut `Super + Shift + A`
- Right-click on the Google Assistant tray icon and click on **"Launch Assistant"**

**PS:** The assistant will take some time to initialize _(indicated by grayscale Google Assistant icon)_. Executing any of the above steps during this time will not launch the assistant. You will have to wait until you see the colorful Google Assistant Icon in the tray and then try to launch the assistant.

**Comment by OmarShawky1** [comment]
as you can see from the system monitor:

**Comment by Melvin-Abraham** [comment]
@OmarShawky1 You are checking in the dock, tray generally resides on the top-right side of the screen:

!["g-assist" Tray Icon](https://user-images.githubusercontent.com/26056183/103276592-fd8e4100-49ec-11eb-9dd9-9b283139b329.png)

Also, Seems like you missed one of the keys _(the `Super` key, same as the `Windows Key`)_ when pressing the hotkey. The correct key combination is `Windows Key + Shift + A` or `Super + Shift + A`

**Comment by OmarShawky1** [comment]
actually it works, but in elementary OS the icon tray does not appear at all as in this picture:
![image](https://user-images.githubusercontent.com/51538094/103284307-8e601f00-49e3-11eb-828d-8d71db203dc7.png)


generally the issue is resolved :)
