### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by ThemihanWeb** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#549]
### What went wrong?

When I search for a web result like, youtube video and some google result with the help of google assistant, it is not opening the browser. Recently I seached for eternals trailer in google assistant, then it told  "**Here's the top TouTube result**". But there was no action happened

https://user-images.githubusercontent.com/92494550/137236417-b424ba76-103e-4396-bf20-010ce893fab9.mp4

n
![Screenshot 2021-10-14 070946](https://user-images.githubusercontent.com/92494550/137236453-3e9a53f3-8e72-4ab5-9e45-d53539571125.png)
.

### What did you expect to happen?

I expected google assistant to open the web browser and give me the result or atleast it might be able to give me the result in the google assistant app.

### Steps to reproduce the bug

Go to google assistant desktop client type any youtube video. example :-" Play the eternals trailer"
Then googe assiatant will tell "I found this on Youtube"
But there **will be no action done by google in that moment.**

### App Version

v1.0.0

### OS Version

Windows 10 Version 21H1 (OS Build 19043. 1237)

### :information_source: Platform Info
Running on **Windows_NT x64 10.0.19043**

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by ThemihanWeb** [comment]
@Melvin-Abraham  please consider my report👆

**Comment by Melvin-Abraham** [comment]
@ThemihanWeb This issue has already been taken into consideration as per #41. The implementation although would have some caveats like hit or miss scenarios and multi-language support. This will still be worked upon later on probably after the release of the next major version as the application will be rewritten from ground up which would provide a clear idea regarding how to tackle these issues.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
