### ISSUE TITLE
Cant authorize

### ISSUE THREAD

**Issue by BakaDolev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#55]
When i try to authorize the app for the token it says access denied

Authorization Error
Error 403: access_denied
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (thebaka1272@gmail.com).

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/76722418/103262075-7f11af00-49ac-11eb-81ab-3a66ac1e26a2.png)

**Comment by BakaDolev** [comment]
Nvm fixed it

**Comment by Melvin-Abraham** [comment]
@BakaDolev Thank you for reporting this issue. I have updated the wiki as per the latest changes.

**Link:** https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
