### ISSUE TITLE
ISSUE: Assistant not working.

### ISSUE THREAD

**Issue by Mr-Dalgleish** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#57]
**Describe the issue**
When tapping the microphone button on the UI, it shuts off straight away, however, the assistant 'bing' came up when pressing the mic. When typing to it, a blue loading bar goes halfway on the bottom of the header and shows what I've typed on the top of the window, no output noise or response was given.

**Screenshots**

[Assistant Capture.zip](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/files/5761235/Assistant.Capture.zip)

**Desktop**
 - OS: Windows 10 Build 21277
 - Assistant Version: 1.0.0-rc.2

**Comment by Melvin-Abraham** [comment]
@Mr-Dalgleish After opening the assistant, can you perform these actions with the DevTools open _(`Ctrl + Shift + I` or **Settings** > **Developer Options** > **Open DevTools**)_ and share the error logs?

> Just as a side note, you can now directly embed videos within GitHub markdown editor. You need not archive it separately :)

**Comment by Mr-Dalgleish** [comment]
Nevermind, it just started to work miraculously. Might have been a sync error with the API. 

> With that side note, I tried to embed the video through it but the file size was too large. But thanks for the tip ;)
