### ISSUE TITLE
[issue][Solved] Not respondig In linux ,

### ISSUE THREAD

**Issue by Dixit-deegit** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#59]
**Describe the bug**
Not answering or responding also the mic is not working.
when I typed I don't get an answer.
After Restart os  client, not running like a close button, setting button.

**Screenshots**
Not respondig image 
![Screenshot from 2021-01-05 11-09-25](https://user-images.githubusercontent.com/72870029/103612078-a7b81c80-4f49-11eb-899b-90577f786b1e.png)

**Desktop (please complete the following information):**
 - OS: [Linux Mint 20]
 - Version [e.g. 1.0.0-rc.2]

**Additional context**
Please help me if it's not a bug please help me to solve

**Comment by Dixit-deegit** [comment]
Please help me

**Comment by Dixit-deegit** [comment]
Please help me please

**Comment by Dixit-deegit** [comment]
Its closed by mistake.

**Comment by Dixit-deegit** [comment]
solved 
solution:--- re-enable assistant API services. check top google bar to ensure that you select your current assistant project

**Comment by Melvin-Abraham** [comment]
_Closing as resolved._
