### ISSUE TITLE
Add more language.

### ISSUE THREAD

**Issue by Dlunhappy226** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#592]
### What's the Problem?

I can't use Chinese and Cantonese.

### What's your solution or idea?

Add more language.

### Alternatives Considered

Add more language.

### App Version

v1.0.0-rc.2

### OS Version

Windows 10

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by sumeshir26** [comment]
@Dlunhappy226 i18n support is comming soon...

**Comment by L12275** [comment]
Please add support for simplified Chinese language in the language dialogue.Thank you !
