### ISSUE TITLE
Addition of compiled executables for linux.

### ISSUE THREAD

**Issue by ayush06feb** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#6]
Hello Melvin,
I have compiled packages for linux systems and have uploded them to my fork. Unfortunately, I wasn't able to make a pull request for releases (I am new to contributing through GitHub). Please add them from their to your project so that others can simply download and run it.
PS:I have compiled them as appimages and snap package for x86 systems.
Here's the link: https://github.com/ayush06feb/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.0.0-rc.1

**Comment by Melvin-Abraham** [comment]
@ayush06feb Since I've already added build instructions for linux (as per b2edeb7), you can be sure that the next release is going to include the packages for linux as well.

**Comment by ayush06feb** [comment]
That's good! It would be helpful for others who are not able to compile the program themselves.
