### ISSUE TITLE
[🐛 Bug]: Doesn't show any images and texts

### ISSUE THREAD

**Issue by pritudev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#606]
### What went wrong?

Whenever I search for something using google assistant it gives me results but doesn't show any image or text to help me to fix it.

![image](https://user-images.githubusercontent.com/75468116/146497011-b4f17d53-099e-48ce-b1c5-956c6b6a8a71.png)
![image](https://user-images.githubusercontent.com/75468116/146497989-4ce133e0-c4a9-4968-8649-551143562230.png)

### What did you expect to happen?

Show images and text on search.

### Steps to reproduce the bug

1. ask the assistant for any diagram or something.
2. see the error.

### App Version

v1.0.0

### OS Version

Windows 10 20H2 19042.1415

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by im-coder-lg** [comment]
I kinda think we have seen this before and I also noticed this getting fixed with Personal Results instegration, so @Melvin-Abraham is it fine if I post the link here? I think Personal Results fixed this for me so it might work here too.

**Comment by pritudev** [comment]
> I kinda think we have seen this before and I also noticed this getting fixed with Personal Results instegration, so @Melvin-Abraham is it fine if I post the link here? I think Personal Results fixed this for me so it might work here too.

Post it please

**Comment by sumeshir26** [comment]
@pritudev Here is the link: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional

**Comment by im-coder-lg** [comment]
If the wiki guide doesn't work, do tell us here, we'll help you out. Mostly 
I expect it's Account Linking, so we'll help you there.

**Comment by pritudev** [comment]
> If the wiki guide doesn't work, do tell us here, we'll help you out. Mostly I expect it's Account Linking, so we'll help you there.

That authentication is already done but still not working

**Comment by sumeshir26** [comment]
@pritudev Try this:
https://gist.github.com/im-coder-lg/23fc93cbf983b36b21641563ed4f3d4e

**Comment by pritudev** [comment]
> @pritudev Try this: https://gist.github.com/im-coder-lg/23fc93cbf983b36b21641563ed4f3d4e

Doesn't working... 😢

![image](https://user-images.githubusercontent.com/75468116/146628657-dc6fb452-cb0d-4368-8ace-acbcf7cda73e.png)

**Comment by Melvin-Abraham** [comment]
> I also noticed this getting fixed with Personal Results instegration ... I think Personal Results fixed this for me so it might work here too.

@im-coder-lg Can you share a screenshot of your assistant client for the queries asked by the OP?

**Comment by im-coder-lg** [comment]
It's on the gist, the Steve Jobs search, I used Personal results _with_ 
Account Linking enabled.

**Comment by pritudev** [comment]
If we ask for any image for anything else it doesn't show anything

**Comment by pritudev** [comment]
![Uploading image.png…]()

**Comment by im-coder-lg** [comment]
Did you enable Account Linking? Also, did you follow all the steps?

**Comment by pritudev** [comment]
> Did you enable Account Linking? Also, did you follow all the steps?

yeah

**Comment by im-coder-lg** [comment]
Wait, let me clone the repo and build from source, let's see.

**Comment by pritudev** [comment]
> Did you enable Account Linking? Also, did you follow all the steps?

![image](https://user-images.githubusercontent.com/75468116/146629682-102e3b8a-a3fd-4fd6-8379-73c7a737d8d5.png)

**Comment by im-coder-lg** [comment]
Testing this from my side, if it works, I will share the latest build with you and you can test that.

**Comment by pritudev** [comment]
> Testing this from my side, if it works, I will share the latest build with you and you can test that.

Sure

**Comment by im-coder-lg** [comment]
Kinda feel dejected...
This works:
![image](https://user-images.githubusercontent.com/76845820/146630115-33d87d45-ac56-4747-8014-6b40e25e2023.png)
But this doesn't:
![image](https://user-images.githubusercontent.com/76845820/146630127-aa7362f3-44d5-4e9f-85a2-e07df01004d4.png)
I kinda think, since I have searched Steve Jobs on my mobile, it is appearing. So maybe I'll shut GAUDC down for now, search something like Turbo C or Qbasic images and do the same on GAUDC...

**Comment by pritudev** [comment]
it doesn't working like you did second time why Is there any fix?

**Comment by pritudev** [comment]
> Kinda feel dejected... This works: ![image](https://user-images.githubusercontent.com/76845820/146630115-33d87d45-ac56-4747-8014-6b40e25e2023.png) But this doesn't: ![image](https://user-images.githubusercontent.com/76845820/146630127-aa7362f3-44d5-4e9f-85a2-e07df01004d4.png) I kinda think, since I have searched Steve Jobs on my mobile, it is appearing. So maybe I'll shut GAUDC down for now, search something like Turbo C or Qbasic images and do the same on GAUDC...

![image](https://user-images.githubusercontent.com/75468116/146630308-e6b0c719-e504-4b19-b28b-2b99b58a283b.png)


Google Assistant on PC is helping me in a lot of things like assignments and questions but this is the only thing not working and it should fixed

**Comment by im-coder-lg** [comment]
Yeah... I expect the query is supposedly saved or something, and I am still testing the search in mobile, then GAUDC trick.

**Comment by pritudev** [comment]
> Yeah... I expect the query is supposedly saved or something, and I am still testing the search in mobile, then GAUDC trick.

Okay

**Comment by im-coder-lg** [comment]
But, at the same time, the app is using the Google Assistant SDK, which is limited in its capabilities, compared to the Android Assistant, which uses the device itself. The SDK doesn't use the entire system though.

**Comment by im-coder-lg** [comment]
Well, Qbasic doesn't appear but the famous Never Gonna Give You Up(not intended to rickroll here) song does, which makes me think sus, I never searched it and it appeared, whereas I searched Qbasic but that doesn't? Maybe the SDK only queries frequently-searched searches only.

**Comment by pritudev** [comment]
What we are supposed to do now?

**Comment by im-coder-lg** [comment]
Well, this is a true bug. The best is to keep this open and use the browser for important searches and GAUDC for quick info like weather, etc.

**Comment by pritudev** [comment]
> Well, this is a true bug. The best is to keep this open and use the browser for important searches and GAUDC for quick info like weather, etc.

so this thing will never fix?

**Comment by im-coder-lg** [comment]
Idk, but it's best to wait for a fix tho

**Comment by 93boba** [comment]
It does show personal results. However, notes are unreadable due to a weird position on the screen. Except for Wikipedia, I am not getting any search results on PC. Is there a way to link PCassistant to a default web browser and show the first result from Google?

**Comment by im-coder-lg** [comment]
Not yet. If you do know a module that does just that, do tell us here!

**Comment by TJ2005** [comment]
is there an update yet?

**Comment by im-coder-lg** [comment]
No :( you got any idea to fox this here?
