### ISSUE TITLE
[Feature Request] Needs more feature improvement like  "ok Google"  

### ISSUE THREAD

**Issue by Dixit-deegit** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#61]
**Describe alternatives you've considered**
Ok Google feature needed .

**Comment by Melvin-Abraham** [comment]
This feature is planned for future and will surely be added later once the essential fixes and features are included

**Comment by thecoder08** [comment]
I would love this feature as well

**Comment by Melvin-Abraham** [comment]
This issue will now be tracked in #105.
_Closing this issue_
