### ISSUE TITLE
Getting the device registration more end-user friendly?

### ISSUE THREAD

**Issue by tjsuominen** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#63]
Any possibility to have the device registration / "token files" either:

a) obsolete (not needed) OR
b) more user friendly (in terms of simplified process)

or is this just because "Required by Google"?`

**Comment by AnishDe12020** [comment]
It is more of a Required by Google case as it is unofficial and the API is in use

**Comment by tjsuominen** [comment]
Ah I see, then we'll have to live by that.
