### ISSUE TITLE
Personal Results are Not Working

### ISSUE THREAD

**Issue by bkjimena11** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#635]
I cannot get personal results to work.

**Comment by sumeshir26** [comment]
Did you try out the guide over here: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional ?

**Comment by bkjimena11** [comment]
It seems to work now.

**Comment by NiviAppno** [comment]
Im having this issue without any sign of success

I followed the gits, I looked through the issues and comments, nothing works
I enabled linking
I restarted the app with fallback
The Tokens were created yesterday.
