### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by mrkproductions** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#637]
### What went wrong?

Great work!

Hey Google, OK Google trigger dont work!!!

### What did you expect to happen?

I expect call to Assistant with "Hey Google"

### Steps to reproduce the bug

Say "Hey Google"

Dont work

### App Version

v1.0.0

### OS Version

Windows 11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by im-coder-lg** [comment]
Dupe of #472 It's Bumblebee Hotword.
