### ISSUE TITLE
[💡 Feature Request]: 

### ISSUE THREAD

**Issue by sudarshandubey0608** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#657]
### What's the Problem?

Can we connect the search results to be displayed in the browser. 

### What's your solution or idea?

just redirect query to browser

### Alternatives Considered

Nope

### App Version

Built from source

### OS Version

Windoes 

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by im-coder-lg** [comment]
Simply put, we need a web browsing module or something that could potentially even control the system as root that can redirect queries.

**Comment by Melvin-Abraham** [comment]
This seems to be related to #41
_Closing as duplicate_
