### ISSUE TITLE
[🐛 Bug]: Does not start

### ISSUE THREAD

**Issue by DATL4G** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#660]
### What went wrong?

I cannot start the program, because it can't (access?) the GPU.
I have an Nvidia RTX 2080, latest drivers installed

```bash
19:28:23.767 › Starting Updater Service...
19:28:23.774 › Checking for updates
19:28:24.133 › No updates available for v1.0.0
[46165:0223/192826.051328:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    46165 trace trap (core dumped)  g-assist
```

### App Version

v1.0.0

### OS Version

Fedora 35

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by Melvin-Abraham** [comment]
Can you try running the application with `--no-sandbox` flag and share the result?

**Comment by DATL4G** [comment]
This worked.
Now it starts and is usable as it should. (And no errors in terminal)
