### ISSUE TITLE
Not able to open Google Assistant on windows 10

### ISSUE THREAD

**Issue by SlavenDj** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#67]
I have just installed the app and I couldn't open it. In task manager, it just appears for a second and disappears again.

 - OS: Windows 10 Build 2004
 - Version 1.0.0-rc.2

**Comment by Melvin-Abraham** [comment]
@SlavenDj The application immediately minimizes to the tray (check hidden icons on the right side of taskbar). You can launch it with either of these ways:

- Press `Windows Key + Shift + A`
- OR Right click on the Google Assistant Tray Icon and click on **"Launch Assistant"**

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
