### ISSUE TITLE
[🐛 Bug]: Unable to process request due to missing initial state. This may happen if browser session Storage is inaccessible or accidentally cleared.

### ISSUE THREAD

**Issue by Nezyyyyy** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#677]
### What went wrong?

@Melvin-Abraham Dear sir I am not sure if it is a duplicate if so i am sorry but please help me 
 OS:- Windows
 Issue:-
<img width="942" alt="image" src="https://user-images.githubusercontent.com/90066444/159109048-b98be08f-6a88-436e-a146-48fd8be6d3f6.png">
![image](https://user-images.githubusercontent.com/90066444/159109056-5e2fb022-bdd4-43fb-bf97-f7de749669bb.png)
After requesting token this happens please help me this is preventing my from using your application 
Thanks in advance...

### What did you expect to happen?

I expected to get the code

### Steps to reproduce the bug

After getting redirected then after clicking the continue button this comes 
![image](https://user-images.githubusercontent.com/90066444/159109102-870c1e8a-0767-4e8f-b7bf-dd244435b5bf.png)

### App Version

v1.0.0

### OS Version

Windows 11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by afrizalyogi** [comment]
Hello, I got the same problem as you mentioned above and I solved it. I have shared my way to solve it in the comments section at #671  or you can straighly <a href="https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/671#issuecomment-1072699291">here</a>. Hopefully it can help you.

**Comment by Nezyyyyy** [comment]
> Hello, I got the same problem as you mentioned above and I solved it. I have shared my way to solve it in the comments section at #671 or you can straighly [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/671#issuecomment-1072699291). Hopefully it can help you.

Hi

**Comment by Nezyyyyy** [comment]
Thankyou Sooo much Sir you are a genius not it is working !!! Lots of Love
Nezzy
