### ISSUE TITLE
unexcepted exception occured

### ISSUE THREAD

**Issue by kheshav-coder** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#68]
just before few days the google assistant was working good but i don't why its not working now, it says some unexpected error occured.....
![Screenshot 2021-01-12 22:07:01](https://user-images.githubusercontent.com/61469266/104344104-be9ad800-5522-11eb-8fc0-1e4b0bac045b.png)

**Comment by kheshav-coder** [comment]
i tried relauncihin the assistant but still the same condition !

**Comment by Melvin-Abraham** [comment]
@kheshav-coder Can you open the DevTools _(`Ctrl + Shift + I` or **Settings** > **Developer Options** > **Open DevTools**)_ and share the error log you get in the console when this error occurs?

**Comment by kheshav-coder** [comment]
error log in console:
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/61469266/104633168-c4302380-56c4-11eb-8ee6-94a56d572f69.png)

**Comment by Melvin-Abraham** [comment]
@kheshav-coder The following error occurs since the Assistant is not initialized. Unfortunately, it does not tell anything about what is causing the error in the first place. I will push a commit soon for improved error logging in the console which would give better insights regarding the cause of errors...

**Comment by kheshav-coder** [comment]
@Melvin-Abraham ok dude sure, thank you !

**Comment by Melvin-Abraham** [comment]
@kheshav-coder Can you clone this repo and run the assistant locally via `npm start` and send the error log if you get the error? Do make sure to use the same key file and tokens file...

**Comment by kheshav-coder** [comment]
dude, I think there were some dependency issues...... I tried reinstalling and it works perfectly fine.... thank you for your help !!!👍
