### ISSUE TITLE
[🐛 Bug]: Authentication Failure

### ISSUE THREAD

**Issue by gani2267** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#692]
### What went wrong?

 I am using this in kali linux when I give location of my Outh json file it got selectect but still when google assistant relaunches it saThe Key file provided is not valid. Make sure the file is of the form "client_secret_<your_id>.apps.googleusercontent.com.json"
although I am giving correct outh json file.

### Steps to reproduce the bug

![Screenshot from 2022-04-06 09-24-59](https://user-images.githubusercontent.com/84265879/161985134-71c8d093-0e18-446c-b5c9-57c146ba43e8.png)

### App Version

v1.0.0

### OS Version

kali Linux 2021.4

### :information_source: Platform Info
Running on **Linux x64 5.14.0-kali4-amd64**
**Distribution Type:** Debian
**Windowing System:** X11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by gani2267** [comment]
I got ans of this in #671

**Comment by justaboringuy** [comment]
i got the same issue and i cant figure out why
