### ISSUE TITLE
[🐛 Bug]: Can't find  the "Get Started" button on windows 11

### ISSUE THREAD

**Issue by Gyanzo-p3pper-derm** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#702]
### What went wrong?

![Screenshot 2022-04-24 032833](https://user-images.githubusercontent.com/94280376/164955162-445ed15a-2038-4172-9200-352539c1513b.png)

### What did you expect to happen?

suppose to see  "Get Started"

### Steps to reproduce the bug

Help

### App Version

v1.0.0

### OS Version

windows 11

### Relevant Assets

![Screenshot 2022-04-24 033531](https://user-images.githubusercontent.com/94280376/164955362-d6874b8b-f605-42c0-85e4-cd5fc3706eff.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by sumeshir26** [comment]
Can you show the full logs?

**Comment by Gyanzo-p3pper-derm** [comment]
![Screenshot 2022-04-24 035810](https://user-images.githubusercontent.com/94280376/164955930-5b9f5b00-060d-4d31-be4c-578d98fb042a.png)


full logs here

**Comment by Gyanzo-p3pper-derm** [comment]
Please what seem to be the problem?
![Screenshot 2022-04-24 035810](https://user-images.githubusercontent.com/94280376/164975995-78373ba8-e5ea-432e-8271-68ccde1d122e.png)

**Comment by sumeshir26** [comment]
I'm not the creater of this app, @Melvin-Abraham is, I just help around everyone here. Ive never seen anything like this before so only he can help you

**Comment by Gyanzo-p3pper-derm** [comment]
so why hasn't he respond

**Comment by Gyanzo-p3pper-derm** [comment]
@Melvin-Abraham  please review this error and fix it

**Comment by Gyanzo-p3pper-derm** [comment]
I actually figured it out to be about my "Temp" folder that I screw up....
It is now working and thanks for the to you guys, you really showed some love

![image](https://user-images.githubusercontent.com/94280376/165195397-7d7099fe-884b-4a6b-8026-017db5743277.png)
