### ISSUE TITLE
[🐛 Bug]: 

### ISSUE THREAD

**Issue by Nokappa0** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#706]
### What went wrong?

When attempting to generate a token, after clicking continue twice, it fails to load the localhost page: ERR_CONNECTION_REFUSED. 

### What did you expect to happen?

Generate a token to paste into the assistant

### Steps to reproduce the bug

see error

### App Version

v1.0.0

### OS Version

windows 11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by sumeshir26** [comment]
Try copying the code from yhe adtress bar

**Comment by im-coder-lg** [comment]
Also it's not supposed to open localhost, where's that line of code? I'd like to change it and test it out.

**Comment by Nokappa0** [comment]
> No @sumeshir26 wait. It's not sessionStorage. The connection failed, can you try [this](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/671#issuecomment-1102144699) and report back?

**Comment by Nokappa0** [comment]
> Try copying the code from yhe adtress bar

Yea this worked, thanks for pointing it out
