### ISSUE TITLE
[🐛 Bug]: Cant Authorize - Cant get Token

### ISSUE THREAD

**Issue by Muscha85** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#729]
### What went wrong?

Hello, unfortunately I can't authorize the application - getting the token ends in an error and I can't enter the code in step A new browser window is being opened. Login / Select a Google account, accept the permissions and paste the authentication code below.

I will choose my google account to log in, google has not verified this application, continue. Subsequently, the application asks for access to my Google account - I will continue and it will appear

This site is not available. Web localhost has refused to connect.
Try:

Check the connection
Check proxy server and firewall
ERR_CONNECTION_REFUSED

Where am I wrong and what needs to be modified to get the code?

### What did you expect to happen?

To get token for google assistant app to finish setup and run app

### Steps to reproduce the bug

1. try to get token
2. open browser with link from Google Assistant app
3. authorize everything 
4. get Messege from browser, but no code to fill in Google Assistant App to finish setup... Message from browser is: 

This site is not available. Web localhost has refused to connect.
Try:

Check the connection
Check proxy server and firewall
ERR_CONNECTION_REFUSED

### App Version

v1.0.0

### OS Version

Windows 10 Pro 21H2 19044.1645

### :information_source: Platform Info
Running on **Windows_NT x64 10.0.19044**

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by AlfRabie** [comment]
I have the same issue.

**Comment by abhinavg97** [comment]
@Melvin-Abraham same issue

**Comment by smittyplease** [comment]
same issue

**Comment by im-coder-lg** [comment]
Check #671. There is a guide in downloading the key file again properly as well as a login code error that results in you going to localhost.

**Comment by im-coder-lg** [comment]
That ought to fix this.
