### ISSUE TITLE
Inputing Token

### ISSUE THREAD

**Issue by Hans0131** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#73]
I can't input the token because if I open google assistant, it will send an error in less than a second, then it will close its self, then it redirects me to sign in and all that stuff ( I did that already ), then when I open it again, the same thing happens? Help please, thank you very much!

**Comment by dark-galaxy20** [comment]
> I can't input the token because if I open google assistant, it will send an error in less than a second, then it will close its self, then it redirects me to sign in and all that stuff ( I did that already ), then when I open it again, the same thing happens? Help please, thank you very much!

Same

**Comment by Melvin-Abraham** [comment]
@Hans0131 Can you check if your issue is similar to #39?
If yes, you can refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/39#issuecomment-734111970 to fix your issue for the time being.

**Comment by Hans0131** [comment]
Ok thanks!

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
