### ISSUE TITLE
shoes localhost refused to connect...

### ISSUE THREAD

**Issue by sarimwaniR** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#736]
### What went wrong?

![image](https://user-images.githubusercontent.com/101258901/175966191-5d582ace-7f47-4164-a254-35a431e3bc21.png)

### Steps to reproduce the bug

umm setup is not complete
when go to this website and hit my account with the approval one and hit continue it shows the error

### App Version

v1.0.0

### OS Version

win 11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I think I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ))
- [X] This issue only covers one particular bug or issue

**Comment by AlfRabie** [comment]
I have the same issue.

**Comment by tristancube** [comment]
I am also having this same issue

**Comment by abhinavg97** [comment]
@Melvin-Abraham

**Comment by Chekole1208** [comment]
huh. I think dev died.

**Comment by im-coder-lg** [comment]
> > huh. I think dev died. 
> 
> It's just the recoding of GAUDC which makes @Melvin-Abraham busy. The answer is at #671

**Comment by im-coder-lg** [comment]
> > > huh. I think dev died. 

It's just the recoding of GAUDC which makes @Melvin-Abraham busy. The answer is at #671

**Comment by Melvin-Abraham** [comment]
Keeping this issue in mind a new version was released ([`v1.1.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.1.0)) along with an updated guide. Refer [Configure Credentials Guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-credentials).

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
