### ISSUE TITLE
[🐛 Bug]:  LocalHost error loading page FIX HERE

### ISSUE THREAD

**Issue by Chekole1208** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#753]
### What went wrong?

After the Browser opens. You login into your Gmail account. Then click on Continue. Then the LocalHost error comes up. If you came this far and found this post you probably know what error I am talking about. 

### What did you expect to happen?

Supposedly. You will get a Code to copy back into the app.

### Steps to reproduce the bug

1. Click on Open Browser
2. Browser takes you to select your Gmail account
3. Browser asks you to click on Continue
4. Instead of giving you the Code, you get "localhost unable to connect" or something like that 
OK......
5. Go into the URL and copy from "http://localhost/?code=" (without the commas) and stop before the  "&scope=" part. 
6. Now go back into your app and paste it
7. Now you're good to go. App is gonna ask you to Relaunch. 

### App Version

v1.0.0

### OS Version

Windows

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by Melvin-Abraham** [comment]
Keeping this issue in mind a new version was released ([`v1.1.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.1.0)) along with an updated guide. Refer [Configure Credentials Guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-credentials).

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
