### ISSUE TITLE
[🐛 Bug]: localhost problem

### ISSUE THREAD

**Issue by SHAURYA-MAKWANA** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#754]
### What went wrong?

When I was authenticating i went to site and after I logged in with my account it said local host refused to connect

here is the screenshot

![image](https://user-images.githubusercontent.com/82109937/182823675-76b3ad80-20d9-4304-a6bc-29ccc84942ca.png)
 

### Steps to reproduce the bug

i dont know what to do

### App Version

v1.0.0

### OS Version

Windows 11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by lilnug143** [comment]
I'm currently having the same issue, very frustrating.

**Comment by im-coder-lg** [comment]
I think this is a bug that was mentioned and given a workaround in #671.

**Comment by cubigiabinh** [comment]
You can try enter the token from the URL:
![image](https://user-images.githubusercontent.com/61140598/183355766-be05bbb6-c6c6-4d67-a2ed-597ff86edd93.png)
only copy the part I underlined.
i don't know if this work for you but it works for me

**Comment by Imauny** [comment]
I also thought of doing the same thing too bruh! And it worked my friend. This may be the straight work around for the problem.

**Comment by im-coder-lg** [comment]
It's the very same. Perhaps I'll try making a gist on common issues, keep it public here, and if anyone needs it, I'll link it here.

**Comment by im-coder-lg** [comment]
Also, you don't need to hide the success code - it's the same all around, but it differs due to the client secret JSON file.

**Comment by silicone-fig** [comment]
> You can try enter the token from the URL: ![image](https://user-images.githubusercontent.com/61140598/183355766-be05bbb6-c6c6-4d67-a2ed-597ff86edd93.png) only copy the part I underlined. i don't know if this work for you but it works for me ![image](https://user-images.githubusercontent.com/61140598/183355988-b46487bb-e714-4533-95fd-985313ca474b.png) copy this part

This worked for me! Thanks so much!

**Comment by SHAURYA-MAKWANA** [comment]
> 

thx this worked

**Comment by Melvin-Abraham** [comment]
Keeping this issue in mind a new version was released ([`v1.1.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.1.0)) along with an updated guide. Refer [Configure Credentials Guide](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-credentials).

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
