### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by malik3453** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#76]
Unexpected Exception Occured
An unexpected error occurred.
Error: Tried calling start() before the ready event!

when i entered the token and relaunch this pops up

**Comment by Melvin-Abraham** [comment]
@malik3453 Seems like a duplicate of issue #39.
You can refer https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/39#issuecomment-734111970 to fix your issue for the time being.

**Comment by Melvin-Abraham** [comment]
_Closing as duplicate_
