### ISSUE TITLE
[🐛 Bug]: Authentication Failure

### ISSUE THREAD

**Issue by voidlesity** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#762]
### What went wrong?

when i input the OAuth 2.0 key into the field its says:"The Key file provided is not valid. Make sure the file is of the form "client_secret_<your_id>.apps.googleusercontent.com.json"" even though i have the right key

![image](https://user-images.githubusercontent.com/104164715/185753391-a56eb264-65d0-4754-8bd2-19d97980fe8a.png)

### What did you expect to happen?

I of course i could follow the tutorial along and everything would be fine

### Steps to reproduce the bug

1. get the oauth key
2. put it into the google assistant
3. relaunch

### App Version

v1.0.0

### OS Version

Windows 10

### Relevant Assets

![image](https://user-images.githubusercontent.com/104164715/185753441-964b93d1-4290-493f-8528-b5d3c89c4ed0.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by im-coder-lg** [comment]
Solution should be in #671.
