### ISSUE TITLE
[💡 Feature Request]: Personal Results

### ISSUE THREAD

**Issue by voidlesity** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#764]
### What's the Problem?

i would like to use my google assistant with Personal Results on pc cause i cant use a specific action that needs Personal Results.

### What's your solution or idea?

implement a way to enable or disable Personal Results.

### Alternatives Considered

As much as I know Personal Results is enabled via google home but the Google assistant on pc is not recognised as a device like my phone.

### App Version

Built from source

### OS Version

Windows 10

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by briankelly** [comment]
I discovered that you can enable this in the official Google Home app _after_ you've attempted to query a personal result using this app.

Check out your notification history in the Google Home iOS or Android app and approve it there:
![IMG_A180C5722DC8-1](https://user-images.githubusercontent.com/306395/187099773-5ce3c042-1f5a-48c6-93f4-3cc11ec09c9a.jpeg)

There wasn't a device name listed until I added it in the Google Home iOS app:
![IMG_03771ED28823-1](https://user-images.githubusercontent.com/306395/187099816-da8a7b7f-f72e-44dc-8914-8f49d0a8b98e.jpeg)

tada 🎉 
<img width="962" alt="image" src="https://user-images.githubusercontent.com/306395/187099881-a3261118-06aa-4412-b8f7-7eed44468705.png">

**Comment by voidlesity** [comment]
yea i still have a problem tho i cant save the device so it doesnt recognise i get as far to the second screenshot
also some text is missing one was for the devices adress and the last one for unlinking but i cant save it

**Comment by ftk789** [comment]
Solved in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/863#issuecomment-1474980944
