### ISSUE TITLE
[🐛 Bug]: Authorization error

### ISSUE THREAD

**Issue by razandtim** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#774]
### What went wrong?

Every time when I turn on my PC it shows this.. and I don't where is this from.. pretty sure from Google Assistant. What should I do?

![image](https://user-images.githubusercontent.com/74573568/189533066-11646379-458b-4322-9128-eb07f5cd2248.png)

### What did you expect to happen?

Nothing idk

### Steps to reproduce the bug

1. Turn on PC
2. See error

### App Version

v1.0.0

### OS Version

Windows 11 Pro 10.0.22622 

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by Melvin-Abraham** [comment]
Hi @razandtim, try disabling system startup option from `Settings > Application > Launch at System Startup` and restart the system to check if the issue still persists

**Comment by razandtim** [comment]
Well.. i uninstalled it.. and it's not from that..
Weird.. i really don't know where this comes from. I don't see it even in Task Manager.

Can you help me up? :))

**Comment by Melvin-Abraham** [comment]
Thanks for the confirmation. It seems like there's some other application installed in your system which is causing the issue. So, closing this issue as unrelated.
