### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by flawlesscode254** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#776]
This desktop client had been flagged recently for spreading malware

**Comment by sumeshir26** [comment]
Where?

**Comment by flawlesscode254** [comment]
It was on thehackernews

**Comment by im-coder-lg** [comment]
That can't be. Can you share a link of the article, please?

@Melvin-Abraham can you check if the dependencies are up-to-date? If there is a change in versions, run npm install locally to add it to the lockfile.

**Comment by Melvin-Abraham** [comment]
Hi @flawlesscode254, Can you send a link to the article here?
