### ISSUE TITLE
[🐛 Bug]: Failed to get Tokens

### ISSUE THREAD

**Issue by Lucasloh123456** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#778]
### What went wrong?

I couldn't access Google assistant. This is what I saw:
![image](https://user-images.githubusercontent.com/78289731/190372907-47660918-e7b6-4d34-85b2-4a5c6f28c7d4.png)

I've checked #212 and #737, but none of them work.
Could you help me?

### What did you expect to happen?

I opened the browser window to sign in, and it lead me to the localhost error. Then, I followed the guide in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/777, but it lead me to that after I entered the code. I was expecting to see a request to restart the app.

### Steps to reproduce the bug

1. Follow instructions to get authentication code
2. Paste authentication code into app
3. Wait for it to load

### App Version

v1.0.0

### OS Version

Windows 11

### Relevant Assets

![image](https://user-images.githubusercontent.com/78289731/190372907-47660918-e7b6-4d34-85b2-4a5c6f28c7d4.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [x] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by Perfii** [comment]
@Lucasloh123456 is it possible to share a solution for this? I am stuck here for months.

**Comment by Lucasloh123456** [comment]
I realised that I missed a few steps, that's why I got this error. You could have missed steps 4 to 6 in the part 'Configure Credentials', where you have to reset the client secret. I also missed that part and I got the error, but it works after I tried again.

**Comment by im-coder-lg** [comment]
> do not use guides that are not from the creator ( @Melvin-Abraham ). They might not be correct. Use the guide in this git instead.

You can use guides from contributors here; most contributors(please include me) know how the app works, the common errors and fixes, so you can trust their guides. 

We also check if it works before pushing the guides publicly btw. Don't worry, if you have concerns over guides(if you think one is confusing or maliciously weird), open a discussion and we'll look at it.

**Comment by im-coder-lg** [comment]
These issues seem like common ones, so if everyone is okay with it, we could make a "known issues" issue and pin it, add it to the issue template and push it here. I am waiting for @Melvin-Abraham's approval, so that I can do this with a green light.

**Comment by Lucasloh123456** [comment]
OK, sure. Thanks.

**Comment by Melvin-Abraham** [comment]
I am planning to create a new repo so that others could also contribute in improving the wiki for this (including FAQs)

**Comment by imclaux** [comment]
Recently installed 1.0.0 and everything worked, after the update to 1.1.0 I now have this error too. 
Tried what the guys in the other topics/issues said to try and it doesn't work. I get failed to get tokens after pasting the code.
