### ISSUE TITLE
[🐛 Bug]: Error When Signing IN

### ISSUE THREAD

**Issue by Challyamua** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#792]
### What went wrong?

I was on my way to get the auth key when I clicked "continue" to allow it to access my account and it gives me the following error;

"Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared."

Please help!

### What did you expect to happen?

I was expecting it to continue to let me through and give me a key as I saw in the video.

### Steps to reproduce the bug

1. Get to the auth key section
2. Continue logging in
3. Click continue when asked
4. There you go

### App Version

v1.0.0

### OS Version

Windows 10 Home 21H2 19004.2006

### Relevant Assets

![image](https://user-images.githubusercontent.com/116378389/197249733-01cf6212-b548-43a1-a63c-d27b059aaa84.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by sumeshir26** [comment]
Copy the token from the adress bar.

**Comment by Challyamua** [comment]
> Copy the token from the adress bar.

Can you elaborate on that?

**Comment by sumeshir26** [comment]
On the adress bar, where the url of the website is displayed copy the text between `?code=` and the next `?` and paste it back into the app.
Hope this helps.

**Comment by sumeshir26** [comment]
Actuallay only copy the text till the next `&`and  **not** till the `?`.
_Also see my above comment_

**Comment by Challyamua** [comment]
Thank you so much it worked! Have a great day!

**Comment by sumeshir26** [comment]
My pleasure! :)
