### ISSUE TITLE
[🐛 Bug]: Error of loading localhost

### ISSUE THREAD

**Issue by Lemon4ik6484** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#795]
### What went wrong?

Page after signing in by google account "localhost" doesn't loading

### Steps to reproduce the bug

Idk how to fix that

### App Version

v1.0.0

### OS Version

Windows 11 x64 Pro

### Relevant Assets

Help me

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by sumeshir26** [comment]
Please copy the code from the adress bar.
And actuallay check the FAQs before creating the issue, because these issues get annoying really soon.

**Comment by Melvin-Abraham** [comment]
This issue has been fixed in [`v1.1.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.1.0)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
