### ISSUE TITLE
[🐛 Bug]: This site can't be reached

### ISSUE THREAD

**Issue by branco2552** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#796]
### What went wrong?

When I try to get the Token, right after confirming the authorization to use the account. I get thrown on the localhost site.

![Screenshot from 2022-10-27 16-35-33](https://user-images.githubusercontent.com/70178453/198383675-3c79095a-37e5-403a-a60e-b2008ae01bfe.png)

### What did you expect to happen?

I expected to get the token to insiet

![Uploading Screenshot from 2022-10-27 16-45-39.png…]()

### Steps to reproduce the bug

1- Browse the json file;
2- Save;
3- Relaunch the Assistant app;
4- Will open a browser and ask you to sign in by Google account;
5- Sign in;
6- Google will ask you to confirm if you want the app to have access to your account;
7- You confirm it;
8- Google will ask for you to verify if you want to use an unknown app to access your Assistent 
9- You confirm it;
10- Then this issue will come out;

### App Version

v1.0.0

### OS Version

Ubuntu 22.04.1 LTS x86_64

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by Melvin-Abraham** [comment]
This issue has been fixed in [`v1.1.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.1.0)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
