### ISSUE TITLE
Javascript error in the main process

### ISSUE THREAD

**Issue by Capelier-Mathieu** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#80]
**Describe the bug**
I have a JavaScript Error related to a timer (see screenshot)

**Expected behavior**
Don't know why this happen, maybe because of startup option but not 100% sure

**Screenshots**
![error page](https://user-images.githubusercontent.com/72555720/107228031-7507b500-6a1c-11eb-92f7-b6b84f883c85.png)

**Desktop:**
 - OS: Windows 10 Professionnel Insider Preview 2004 (version 21301.1010)
![screenshot](https://user-images.githubusercontent.com/72555720/107228650-2e668a80-6a1d-11eb-97d7-3251ff2c5788.png)
 - Version [e.g. 1.0.0-rc.2]

**Additional context**
I have no context, I can't open the app, even if I close it from the icon in taskbar and try to reopen it.
Also, there is a second window opened above:
![image](https://user-images.githubusercontent.com/72555720/107229607-530f3200-6a1e-11eb-9491-d30dd1b1f345.png)

**Comment by Melvin-Abraham** [comment]
@Capelier-Mathieu Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the `setPosition()` function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via `git clone`) and build it yourself (see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)) since it has been fixed within the source but not released yet.

You can learn more about this bug [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/35#issuecomment-726725640). You can close this issue if it helps :)

**Comment by Capelier-Mathieu** [comment]
Thank you very much for your answer! After cloning the repo, I tried to build it but I'm on Windows so it didn't work and I don't know if it's possible or not. I read the [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build) but it seems to have Linux commands only. If you know how I could do it I'll be very grateful.

**Comment by Melvin-Abraham** [comment]
The commands work across all the platforms. You must have either `npm` or `yarn` installed on your machine. If you already did and got a build error instead, you might need to install **MS Visual Studio C++ Runtime** for building native modules...

To install Windows Build Tools, run the following command in Powershell as Administrator:

```
npm install --global windows-build-tools
```

OR, if you are using Yarn

```
yarn global add windows-build-tools
```

**Comment by yossijo** [comment]
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/150#issuecomment-781609739

**Comment by maximumchar** [comment]
> @Capelier-Mathieu Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the `setPosition()` function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via `git clone`) and build it yourself (see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)) since it has been fixed within the source but not released yet.
> 
> You can learn more about this bug [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/35#issuecomment-726725640). You can close this issue if it helps :)

hey i am not a programmer i know nothing about programming so can you tell me how to do it?? like what should i clone? and i have read the how to build so i will try it.

**Comment by Melvin-Abraham** [comment]
> > @Capelier-Mathieu Seems like this issue is similar to #35. This is a bug which occurs due to passing a floating-point number to the `setPosition()` function, which is calculated based on your screen size. Thus, the only way to get around it for the time-being is to clone this repo (via `git clone`) and build it yourself (see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#how-to-build)) since it has been fixed within the source but not released yet.
> > You can learn more about this bug [here](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/35#issuecomment-726725640). You can close this issue if it helps :)
> 
> hey i am not a programmer i know nothing about programming so can you tell me how to do it?? like what should i clone? and i have read the how to build so i will try it.

@maximumchar You can refer to the [Contributing Guidelines](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/CONTRIBUTING.md) for help regarding how to contribute or clone/build the repo.
