### ISSUE TITLE
Not able to get any response form redirect host  'https://localhost:5754/auth/handler'  [🐛 Bug]: 

### ISSUE THREAD

**Issue by Jagadishwar49** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#816]
### What went wrong?

not able to finish setup token is not genrated

"
https://localhost:5754/auth/handler?code=4/0AfgeXvt-19uNEuv0qfsyiAmp0bA5phc-KonJ-3NakUstRrgh3VLxX5jBgVhAyOxjGYRHLg&scope=https://www.googleapis.com/auth/assistant-sdk-prototype
"

getting 

This site can’t provide a secure connectionlocalhost sent an invalid response.
[Try running Windows Network Diagnostics](javascript:diagnoseErrors()).
ERR_SSL_PROTOCOL_ERROR

### What did you expect to happen?

get token

### Steps to reproduce the bug

Setting authentication in the app
Run and launch the Google Assistant Unofficial Desktop Client app

Click on the "Settings" button in the top-left corner of the application

Under the "Authentication" section, set the "Key File Path" to the path where you have kept the "OAuth 2.0 Credentials" and leave the "Saved Tokens Path" empty. Now click on "Save" button

Now, you will be presented with the "Get Token!" screen. An authentication page will be opened in your default browser

....

...

Now grant permission to the project by clicking on "Continue"

after this im getting 

### App Version

v1.1.0

### OS Version

windows 10 pro

### Relevant Assets

![Screenshot (75)](https://user-images.githubusercontent.com/73735680/201712031-2163e2da-a854-4306-a8f3-a0010501a2d2.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by User2020** [comment]
Anyone else with this issue:  you can get around it by changing the address in the address bar from https to http and press enter to reload the page.  Worked for me.

**Comment by EgidioCaprino** [comment]
> Anyone else with this issue: you can get around it by changing the address in the address bar from https to http and press enter to reload the page. Worked for me.

That didn't work for me

**Comment by LazyDevv** [comment]
Worked for me

**Comment by PeteyX** [comment]
Worked for me

**Comment by slodkipiesio** [comment]
> Anyone else with this issue: you can get around it by changing the address in the address bar from https to http and press enter to reload the page. Worked for me.

worked for me too

**Comment by devanteweary** [comment]
Changing it to HTTP also worked for me.
