### ISSUE TITLE
[🐛 Bug]: Access blocked: This app’s request is invalid

### ISSUE THREAD

**Issue by NickAgrest** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#818]
### What went wrong?

I followed the wiki Exactly. But I run into a problem, it is an Access block error. I was repeating the process of creating this project multiple times but all of the time it bugs out.
If I try leaving the default url i get a different error so I don't know how to fix it.

I got it to work for a second but localhost did not want to load. I tried the https:// to http:// but it did not work.

The error code is 400.

I tried switching browsers but it did not work.
I tried Chromium(Edge, Google Chrome, Brave) and non-Chromium (Firefox) but it still give the same error code.

![Screenshot 2022-11-14 213804](https://user-images.githubusercontent.com/109287412/201760960-14804c1a-f3a8-4394-b0b2-b912198fef00.png)

Picture B is if I leave the default url in

![Screenshot 2022-11-14 213911](https://user-images.githubusercontent.com/109287412/201761160-96b69e8b-9b5a-4f3b-82e5-ea56d673fa11.png)

### What did you expect to happen?

I was following the wiki and it bug out

### Steps to reproduce the bug

I do all steps normally

The error begins at this point:
1. https://console.cloud.google.com/apis/credentials
2. I change "Authorized redirect URIs" to "https://localhost:5754/auth/handler"
3. I reset the secret and download it.
4. I open google assistant and change "Key File Path"
5. It loads the URL but it gives me "Access blocked: This app’s request is invalid".

### App Version

v1.1.0

### OS Version

Windows 11 Pro Version 22H2 (OS Build 22621.819)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by Melvin-Abraham** [comment]
@NickAgrest Seems like you didn't re-download your OAuth credentials after updating your redirect URI. I would recommend you go through [Wiki: Configure Credentials](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-credentials) **_(especially step 7)_**
