### ISSUE TITLE
[💡 Feature Request]: Take advantage of Intel's Wake on Voice tech

### ISSUE THREAD

**Issue by androidacy-user** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#819]
### What's the Problem?

Intel has native tech to enable low-power listening for a wake word; however this app seems to just blanket listen for the wake word, consuming unnecessary battery.

### What's your solution or idea?

https://www.intel.com/content/www/us/en/architecture-and-technology/smart-sound-technology.html#:~:text=With%20Intel%C2%AE%20Wake%20on,devices%20at%20the%20same%20time this describes Intel's tech to enable scenarios like this in a hardware supported and battery efficient way.

### Alternatives Considered

Current impl

### App Version

1.1.0

### OS Version

Windows 11 Build 22H2

### Additional context

Device I'm using is a Galaxy Book Pro, from Samsung.

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by sumeshir26** [comment]
This can be done on Intel PCs only, but what abkout AMD or Qualcom chips?

**Comment by im-coder-lg** [comment]
It says: 

> Intel® Smart Sound Technology (Intel® SST) is an integrated audio DSP (Digital Signal Processor) built to handle audio, voice, and speech interactions. It allows the latest Intel® Core™ and Intel® Atom™ processor-based PCs to respond to your voice command quickly and offer high fidelity audio without impacting system performance and battery life.

`Latest Intel® Core™ and Intel® Atom™ processor-based PCs` means only latest. Many of us(including me) probably(exclude me) use 5-10 year old PCs. For us, we could just install Linux and do devwork. And Linux ain't gonna support this quickly. Plus, it would be a burden to check the chipset of a computer to check for Intel software compatibility - Linux world drivers are either proprietary or community made. So, I don't think so :(

If Intel introduced this before and Apple still used Intel Macs, we could implement this with a fallback to Bumblebee for resiliency.

**Comment by im-coder-lg** [comment]
No worries! I just wanted to help.

Also, Intel makes things like this when there is power to their chipsets. It is all a strategy to make people move to costlier and redundant Windows-powered PCs.

Reson Isaid "redundant" for Windows is that S-zero level sleep that empties ionic juice.

**Comment by Melvin-Abraham** [comment]
Hey @androidacy-user, thanks for the suggestion. It would have been a great feature to add but unfortunately it is not possible to be implemented for now due to following reasons:

- It seems that the "Wake-on-Voice" technology is primarily intended to be used with Cortana, there's little to no references online referring to anything otherwise
- This technology is proprietary and does not seem to have any API documentation for extending it's functionality to any 3rd party application

**Comment by im-coder-lg** [comment]
P.S.

Universal truth fellas, Cortana sucks. Speaking from experience and a deep hatred for the effin' S-zero sleep used in computers today. Can't they leave us customers with juice like Macs?
