### ISSUE TITLE
language

### ISSUE THREAD

**Issue by umbrella-k** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#82]
I am Japanese.
Even if the language setting is Japanese, the display language does not change. 
Does this mean it hasn't been translated?

**Comment by Melvin-Abraham** [comment]
@umbrella-k It works without any issues for me. Can you check if you **saved the settings** after making the changes? If you did, can you check if you got any errors in the DevTools (`Ctrl/Cmd + Shift + I`)?

![image](https://user-images.githubusercontent.com/26056183/107355647-c637a780-6af5-11eb-9bf1-2051c6457088.png)

**Comment by umbrella-k** [comment]
Verified.  However, the settings screen has not been translated.  Is this a specification?

**Comment by Melvin-Abraham** [comment]
Currently, the language setting would only affect the conversation language. Application level language support is currently not built into the application but you can contribute if you are interested :)
