### ISSUE TITLE
I am not able to get the key. I followed all the steps and after all I got a message on the browser that localhost refused to connect. Please help me.

### ISSUE THREAD

**Issue by Somansh-A-30** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#820]

**Comment by sumeshir26** [comment]
Copy the code from the adress bar between `?code=` and the next `?`

**Comment by q2051839** [comment]
Change HTTPS before localhost to HTTP

**Comment by El-mou33** [comment]
Same issue here

**Comment by El-mou33** [comment]
> Change HTTPS before localhost to HTTP

It isn't a solution, If I change to http it say: Access blocked: The request from this application is invalid

**Comment by Somansh-A-30** [comment]
> 

I am not able to understand this

**Comment by sumeshir26** [comment]
> > 
> 
> I am not able to understand this

@Somansh-A-30 Try to change the begining of the website adress to `http://` from `https://`



> > Change HTTPS before localhost to HTTP
> 
> It isn't a solution, If I change to http it say: Access blocked: The request from this application is invalid

@El-mou33 Try to copy the code from the adress bar between `&code=` to `&`

**Comment by TheRobstercraw** [comment]
Copy the code and do what?

**Comment by sumeshir26** [comment]
> Copy the code and do what?

@TheRobstercraw  Copy the code and paste it in the app.

**Comment by El-mou33** [comment]
Solved for me! Thankyou

**Comment by TheRobstercraw** [comment]
> > Copy the code and do what?
> 
> @TheRobstercraw Copy the code and paste it in the app.

Yeah, I found the video in another post and that actually explained what exactly you need to copy and paste. Saying copy the code just makes you think, What code? Where? If people were more specific it would be great. Thanks.

**Comment by Somansh-A-30** [comment]
> > > 
> > 
> > 
> > I am not able to understand this
> 
> @Somansh-A-30 Try to change the begining of the website adress to `http://` from `https://`
> 
> > > Change HTTPS before localhost to HTTP
> > 
> > 
> > It isn't a solution, If I change to http it say: Access blocked: The request from this application is invalid
> 
> @El-mou33 Try to copy the code from the adress bar between `&code=` to `&`

Resolved for me. Thanks brother.

**Comment by Melvin-Abraham** [comment]
@im-coder-lg Sure. That would be great. You can make a PR for the same. Although these issues are covered in the FAQ page.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
