### ISSUE TITLE
Yeah but isn't DEB used mainly for Debian-based distros or is Arch Linux based on Debian without APT?

### ISSUE THREAD

**Issue by Nathaniel97299** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#832]
Yeah but isn't DEB used mainly for Debian-based distros or is Arch Linux based on Debian without APT?

_Originally posted by @im-coder-lg in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/97#issuecomment-1009598774_

**Comment by im-coder-lg** [comment]
Um... Why does this tag me?

**Comment by im-coder-lg** [comment]
> No, Arch is not based on Debian. `.deb` is a packaging format that Debian's package manager APT understands and Arch's package manager called Pacman uses `.tar.zst`.
> DEB is not used for any official Arch repo packages, and not always even for the AUR.

By @DestroyerXyz in https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/97#issuecomment-1009600681
