### ISSUE TITLE
Dynamic Link Demo

### ISSUE THREAD

**Issue by Nathaniel97299** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#833]
Polygon, Mastercard, and Neobank hi team up to launch NFT debit card
🔗 via NBW, the news app for working professionals. 
 👉 Download:          
  https://nextbigwhat.onelink.me/d8LA/ugz9aiu0

**Comment by im-coder-lg** [comment]
Bot spam. Absolute BS. @Melvin-Abraham I think it's time to remove this.
