### ISSUE TITLE
Error getting tokens

### ISSUE THREAD

**Issue by Trak-X** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#84]
**Describe the bug**
Cannot finish setup process as the Assistant does not fetch the tokes from Google

**To Reproduce**
Approve in the setup process to auto generate file and then login in the browser with the email address added under Test users
Wait 10 seconds as per the count down timer
Cry as it does not work
Repeat :)

**Expected behavior**
Should store the token/s received and ask the user to restart the Assistant

**Screenshots**
![image](https://user-images.githubusercontent.com/2991291/107703725-c0dc8780-6cc4-11eb-8bfb-38327642545a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19042.789
 - Version 1.0.0-rc.2

**Additional context**
The webpage does open in the browser, I get the option to allow all permissions and get the code that i need to fill in the app. Further than than, nothing happens.

**Comment by Trak-X** [comment]
A weird things .. as far as i see, is that now the Assistant does actually work, and i get results when asking for Weather for example.

![image](https://user-images.githubusercontent.com/2991291/107704188-86bfb580-6cc5-11eb-8f4d-b87471f54089.png)

![image](https://user-images.githubusercontent.com/2991291/107704152-78719980-6cc5-11eb-95cf-f26718550426.png)

**Comment by Trak-X** [comment]
With every reopen of the app, i am getting asked to Get Token: 

![image](https://user-images.githubusercontent.com/2991291/107704801-82e06300-6cc6-11eb-876c-247c958f96fa.png)

and if i try to run a command without doing so: 

![image](https://user-images.githubusercontent.com/2991291/107704854-91c71580-6cc6-11eb-9bca-e0cffbced1ea.png)

**Comment by Melvin-Abraham** [comment]
@Trak-X Seems like the file "tokes.json" was deleted later on causing the "Get Token!" screen to come up.

Now coming to the `Error: Tried calling start() before ready event!`, you will need to temporarily disable **Settings** > **Conversation** > **Enable microphone on application startup**.

If you get `Failed to get tokens` screen, you can try it the next day due to rate limiting.

**Comment by Trak-X** [comment]
@Melvin-Abraham not really, The "Get Token!" screen came up while doing the setup initially, being the first time to actually test this, so rate limit should not have been a reason. Will try again now. 

As for the second one, "Enable microphone on application startup" was already disabled, so i cannot change it.

**Comment by Melvin-Abraham** [comment]
@ShaneSmiskol has got a point. The issue could also happen due to access permission.

@Trak-X Can you check if you too are in the same boat. If not, I would recommend re-setting the key file path and clear the tokens and fetch again.

> As for the second one, "Enable microphone on application startup" was already disabled, so i cannot change it.

This issue can also come up when assistant is triggered when the saved tokens file is not found/accessible. Thus, you will have to create new tokens using "Get Token!" screen (make sure that the "Saved Tokens Path" can be accessed without permission issues).

**Comment by Trak-X** [comment]
Sure. Will give it a try.

**Comment by csansoon** [comment]
I am having the same issue.
> I had this problem too until I moved the key file from the install path of the Google Assistant client (which was in Program Files since I chose "install for all") to a non-administrative folder.
I tried moving the file to a non-admin folder but the issue is still there. Everytime I open the Assistant it shows me a screen to "Get token!" and opens a link in my browser to get the token for the app, although I can still use the Assistant and it answers me right.

**Comment by csansoon** [comment]
Okay I solved it for me!
I think my problem was with administrative access. I changed the location of the **Key File Path** as well as the **Saved Tokens Path** to my Documents folder, so the app now has access to it! Now it's all working fine.

![image](https://user-images.githubusercontent.com/57395395/107848388-65f57e00-6df3-11eb-80c8-5cc2dcd3153c.png)

**Comment by Trak-X** [comment]
Yes, i can report the same thing. I moved both Key File and Tokens to a new folder under Documents and that solved the issue. I am no longer being asked to login every time and everything works.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
