### ISSUE TITLE
[🐛 Bug]: Invalid Tokens!

### ISSUE THREAD

**Issue by LoaiEsam37** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#847]
### What went wrong?

after i had put the token and the app said that it`s vaild i refreshed the app and then the output was :-
**Invalid Tokens!
The Token file provided is not valid. Please check the path under 'Saved Token Path' in settings.**
_Error: No access or refresh token is set_

### What did you expect to happen?

I expected that it will work.

### Steps to reproduce the bug

1 - put the token
2 - refresh the app
3 - error

### App Version

Built from source

### OS Version

Linux ubuntu 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Relevant Assets

![Screenshot from 2023-01-10 11-12-17](https://user-images.githubusercontent.com/114489561/211509706-60bfa784-3787-4939-bf4f-e07270a5ad81.png)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by LoaiEsam37** [comment]
i have tried the steps you provided [here](https://raw.githubusercontent.com/wiki/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client.md#configure-credentials)
but this happened when i changed the URL to 

* http://localhost:5754/?code={my Token}&scope=https://www.googleapis.com/auth/assistant-sdk-prototype

### I get this :-
![Screenshot from 2023-01-10 11-39-28](https://user-images.githubusercontent.com/114489561/211515893-2390d6f2-1025-4661-9aea-5f050a05eeae.png)

**Comment by LoaiEsam37** [comment]
@Melvin-Abraham

**Comment by sumeshir26** [comment]
@LoaiEsam37 Is the path for your tokens correct?

**Comment by LoaiEsam37** [comment]
> @LoaiEsam37 Is the path for your tokens correct?

![Screenshot from 2023-01-10 18-29-40](https://user-images.githubusercontent.com/114489561/211607797-0333e8d3-3234-4e69-ac70-330e82eff5be.png)

 ```bash
loai@ubuntu:~/Downloads$ pwd
/home/loai/Downloads
loai@ubuntu:~/Downloads$ ls
 client_secret_299488991935-bjj9c3272f1v48rdkt3b46tl0gg5bmmm.apps.googleusercontent.com.json
 tokens.json
```

## Yes

@sumeshir26

**Comment by LoaiEsam37** [comment]
## Do you have any idea to solve this problem ?
### please reply fast

**Comment by ghost** [comment]
it didnt work

<img width="1343" height="448" alt="Image" src="https://github.com/user-attachments/assets/dad7975b-5583-4ade-b8d0-088ec3d7ede9" />

<img width="1331" height="452" alt="Image" src="https://github.com/user-attachments/assets/fda851cc-7006-43df-b469-cfc8880e1f68" />
