### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by dimnls** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#85]
Seems like a very nicely built app, congrats!

I am following the [guide ](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client) and registered fine with Google Cloud. However, when I open the Desktop client and click the settings gear on the top left, nothing happens. This is on Windows 10 20H2 and I tried to run as admin and restart too.

**Comment by Melvin-Abraham** [comment]
@dimnls Possible duplicate of #45. Seems like you are in the welcome screen. If you are, you will have to click through the **"Get Started"** and **"Proceed"** buttons before you can access settings.

![Welcome Screen](https://user-images.githubusercontent.com/26056183/107728586-7e429b80-6d14-11eb-98d5-f0ff63891702.png)

**Comment by dimnls** [comment]
I feel very, _very_  stupid now... Thanks, it works perfectly 👌

**Comment by dewster** [comment]
I not see “Get Started” button and wheel nőt working 🙄

**Comment by Melvin-Abraham** [comment]
@dewster Can you open a new issue with description and screenshot(s)?
