### ISSUE TITLE
Followed setup yet oauth not allowed

### ISSUE THREAD

**Issue by MANICX100** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#86]
Error 403: restricted_client
This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console https://console.developers.google.com/apis/credentials/consent?project=${your_project_number}
Request Details
access_type=offline
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=727406104553-qdl7cbo1smvgf02h3orduk8vtmc65be1.apps.googleusercontent.com
scope=https://www.googleapis.com/auth/assistant-sdk-prototype

**Comment by maj113** [comment]
same issue here 
`Error 403: restricted_client
This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console https://console.developers.google.com/apis/credentials/consent?project=${your_project_number}
Request Details
access_type=offline
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=190476857525-mhb5oj1j7jnph9tm5t7jgqr06ce8602s.apps.googleusercontent.com
scope=https://www.googleapis.com/auth/assistant-sdk-prototype`

**Comment by Melvin-Abraham** [comment]
@MANICX100 @maj113 Duplicate of #78.

You seem to have skipped configuring the consent screen.
You can get help with setting up consent screen using [this link](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-consent-screen).

**Comment by MANICX100** [comment]
![console cloud google com_apis_credentials_consent_project=pc-assistant-2845e](https://user-images.githubusercontent.com/5303241/107747898-1f7b2300-6d10-11eb-8e6c-245caa89b736.png)

I had followed the setup here is a screenshot of my consent screen. I have added my email of the used google account as the sole test user.

I have also tried publishing nothing works.

Kind regards :)

**Comment by Melvin-Abraham** [comment]
@MANICX100 Make sure you are using the same Google account to authenticate whose Gmail address was specified under **"Test Users"**.

**Comment by MANICX100** [comment]
I am :)

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by MANICX100** [comment]
@Melvin-Abraham @maj113 
finally fixed this - the important step is to after selecting device type e/g/ light don't skip capabilities, press save leaving the list empty, pressing skip doesn't setup oauth.
