### ISSUE TITLE
[💡 Feature Request]: The ability to provide a directory for shortcuts for programs to be opened When saying " open (app) "

### ISSUE THREAD

**Issue by ftk789** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#879]
### What's the Problem?

It's not a problem, It's a feature suggestion.

### What's your solution or idea?

The ability to provide shortcuts for programs to be opened When saying " open (app) ", Where it executes shortcuts according to the name { And for devs provide the ability to get launch parameters to pass to the shortcuts ], Something like this: 

User: Open Chrome [ Shortcut named Chrome ]
Assistant: Opening Chrome

Devs: Open Chrome how to dance
Assistant Opening Chrome [ Executes chrome and passes " how to dance " to the launch parameter].

### Alternatives Considered

Nothing yet.

### App Version

Built from source

### OS Version

Windows 10

### Additional context

Thanks for an amazing Open-Source Trustworthy project.

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one particular feature request

**Comment by sumeshir26** [comment]
@ftk789 Hi! It has not been implemented due to the technical complexity of the features. This has been requested already.

**Comment by ftk789** [comment]
> 

Thank you for your reply, Would it be really complex? I mean In Javascript "FS" or CP (Child process) should be useful and should help with some cases, I wish I knew how to implement it and send it back for a review to be accepted or so...  Or possibly a .bat files

**Comment by ftk789** [comment]
And also I want to ask, Is it considered?

**Comment by sumeshir26** [comment]
> > 
> 
> Thank you for your reply, Would it be really complex? I mean In Javascript "FS" or CP (Child process) should be useful and should help with some cases, I wish I knew how to implement it and send it back for a review to be accepted or so... Or possibly a .bat files

@ftk789 Yes, as the responses are actually given by the Google Assistant, not the app. The app just simply acts as a display for that output.



> And also I want to ask, Is it considered?

Yes, it has been already considered.

**Comment by ftk789** [comment]
> > > 
> > 
> > 
> > Thank you for your reply, Would it be really complex? I mean In Javascript "FS" or CP (Child process) should be useful and should help with some cases, I wish I knew how to implement it and send it back for a review to be accepted or so... Or possibly a .bat files
> 
> @ftk789 Yes, as the responses are actually given by the Google Assistant, not the app. The app just simply acts as a display for that output.
> 
> > And also I want to ask, Is it considered?
> 
> Yes, it has been already considered.

Thank you very much for your reply, I understand how the app works and how NodeJS interacts with the system using the given text prompt from Google Assistant's SDK Etc... , I just expected it to be easy since you can obtain the text spoken and apply functions to it according go the console logging, But hope it's in the works before I start working on such a thing. Thank you again for your relpy

**Comment by sumeshir26** [comment]
> > > > 
> > > 
> > > 
> > > Thank you for your reply, Would it be really complex? I mean In Javascript "FS" or CP (Child process) should be useful and should help with some cases, I wish I knew how to implement it and send it back for a review to be accepted or so... Or possibly a .bat files
> > 
> > 
> > @ftk789 Yes, as the responses are actually given by the Google Assistant, not the app. The app just simply acts as a display for that output.
> > > And also I want to ask, Is it considered?
> > 
> > 
> > Yes, it has been already considered.
> 
> Thank you very much for your reply, I understand how the app works and how NodeJS interacts with the system using the given text prompt from Google Assistant's SDK Etc... , I just expected it to be easy since you can obtain the text spoken and apply functions to it according go the console logging, But hope it's in the works before I start working on such a thing. Thank you again for your relpy

No, work has not been started yet

**Comment by ftk789** [comment]
At least it's considered.

**Comment by ftk789** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Thank you for your reply, Would it be really complex? I mean In Javascript "FS" or CP (Child process) should be useful and should help with some cases, I wish I knew how to implement it and send it back for a review to be accepted or so... Or possibly a .bat files
> > > 
> > > 
> > > @ftk789 Yes, as the responses are actually given by the Google Assistant, not the app. The app just simply acts as a display for that output.
> > > > And also I want to ask, Is it considered?
> > > 
> > > 
> > > Yes, it has been already considered.
> > 
> > 
> > Thank you very much for your reply, I understand how the app works and how NodeJS interacts with the system using the given text prompt from Google Assistant's SDK Etc... , I just expected it to be easy since you can obtain the text spoken and apply functions to it according go the console logging, But hope it's in the works before I start working on such a thing. Thank you again for your relpy
> 
> No, work has not been started yet


At least it's considered.
