### ISSUE TITLE
[🐛 Bug]: Can't use smart devices 

### ISSUE THREAD

**Issue by CarlosUlisesOchoa** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#899]
### What went wrong?

Yesterday (4 May) it was working as usual, I use this app since 2 months ago without any issue. But today I realized that Google updated something and now I am unable to use my smart devices from this app.

![image](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/assets/26280134/8346e344-be56-47ec-8e6b-c9034b51590f)

### Steps to reproduce the bug

Just ask the assistant to turn device on/off

### App Version

Built from source

### OS Version

Windows 11

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

### PD
PD: Yes, I've renewed the token and the issue persists.

PD2: I am aware that this problem was caused by Google, as I launched the app on my smartphone and noticed significant changes in the Google Home UI. So, it seems to be an issue originating from Google. I hope you can address this when you have the time.

## Thank you

**Comment by sumeshir26** [comment]
@CarlosUlisesOchoa This has been happening with a lot of users recently, no fix yet sadly...

**Comment by CarlosUlisesOchoa** [comment]
> @CarlosUlisesOchoa This has been happening with a lot of users recently, no fix yet sadly...

Thank you for your reply. I am not sure what the issue was, but currently, it is working just like before.
