### ISSUE TITLE
Error by starting this app 

### ISSUE THREAD

**Issue by HamgamPardazesh** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#9]
Win 10 

![image](https://user-images.githubusercontent.com/38905298/88879097-a8cc7b80-d23e-11ea-89d2-1aabe7487b93.png)

[Content]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 114.5
    at App.app.on (C:\Users\Username\AppData\Local\Programs\Google Assistant\resources\app.asar\app.js:145:20)
    at App.emit (events.js:187:15)

[OK]

**Comment by Melvin-Abraham** [comment]
Please provide **more information**, including the version of Assistant you are using. Did you _build it manually_ or are you using the _binary from releases_?

**Comment by HamgamPardazesh** [comment]
I use version 1.0.0 rc
and built it by windows installer

win 10- last update - hp system  4530s core i5


feel free to contact me for more information

**Comment by Melvin-Abraham** [comment]
@HamgamPardazesh Sorry for the delay. I can't reproduce the issue you are having. Can you try reinstalling?

**Comment by Melvin-Abraham** [comment]
Closing as a stale issue
