### ISSUE TITLE
Design doesn't completely match.

### ISSUE THREAD

**Issue by QkeleQ10** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#90]
The colours and fonts are different than the colours on Android. Light theme background is a tad too dark and response text is Product Sans (bold) instead of Roboto.

Perhaps you could try using an eyedropper on the screenshot below:
![image](https://user-images.githubusercontent.com/55982900/107757270-9e2e8b00-6d25-11eb-91ef-7f182a45e1fe.png)

**Comment by QkeleQ10** [comment]
@Melvin-Abraham Can I help you with anything regarding the design? xP

**Comment by Melvin-Abraham** [comment]
> The colours and fonts are different than the colours on Android. Light theme background is a tad too dark and response text is Product Sans (bold) instead of Roboto.

@QkeleQ10 The design of assistant is not derived from the Android version. The current design language (colors, fonts, etc.) are specifically selected to work with different _desktops_.

> Can I help you with anything regarding the design? xP

Thank you for asking :) but I am currently not sure if we should change the design elements considering it works nicely on desktop.

**Comment by QkeleQ10** [comment]
@Melvin-Abraham :

I personally find myself having issues reading the text comfortably in low-light levels, on both my desktop and laptop 😬

But I totally understand you'd like to keep the design like it is right now.

**Comment by Melvin-Abraham** [comment]
@QkeleQ10 Are you using light theme?

**Comment by QkeleQ10** [comment]
> @QkeleQ10 Are you using light theme?

I'm using both themes, but the light theme seems the most off and hard to see sometimes.

**Comment by Melvin-Abraham** [comment]
@QkeleQ10 Your concern seems to be reasonable. In light theme, the text could be a bit less legible, the reason being usage of `invert` filter. This would affect any fonts and is not specific to a particular one. However, this would be worked upon once all the necessary enhancements and bug fixes are addressed.
