### ISSUE TITLE
[🐛 Bug]: Somethingwentt wrong error after pressing accept on unverified warning

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#911]
### What went wrong?

Pressing continue after the warning presents me with a generic Something went wrong fatal error message, then boots me to my Google account page. This is the URI it redirects me to: https://accounts.google.com/info/unknownerror

Also, I get errors in their Cloud API about my personal gmail account not being supported.

### What did you expect to happen?

One extra warning, then bobs your uncle

### Steps to reproduce the bug

This appears to happen for no reason at all. I followed all steps correctly and this still happens.

### App Version

v1.1.0

### OS Version

Linux Mint 21.2 Cinnamon

### Relevant Assets

![Screenshot from 2023-08-26 01-40-12](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/assets/61162037/3a3dedcc-fc75-4caa-8102-4b0d66dab985)

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%F0%9F%90%9B+bug%22) and didn't find any duplicate issue
- [X] I have checked the [Frequently Asked Questions (FAQs)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)) and can confirm that there's no fixes or workarounds for this issue
- [X] This issue only covers one particular bug or issue

**Comment by TheSystemGuy1337** [comment]
Digging in the console reveals this: POST https://accounts.google.com/_/signin/oauth/warning/continue?hl=en&_reqid=12839&rt=j  400

Google seems to be tossing HTTP 400 errors at me for no reason. Clicking next calls https://myaccount.google.com/?pli=1

I even bring an old instance of this port back from the dead, and it didn't work too. Is Google catching on to this ports existence and is doing this as an effort to stop us from using it?

**Comment by darkskyliner34** [comment]
@TheSystemGuy1337 brother try the part where you configure credentials point 2:
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client

**Comment by TheSystemGuy1337** [comment]
1. Already read the fucking manual, line for line, 100% verbatim.

Message ID:
<Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/911/1707477253
@github.com>

2. At the adding users part, I receive this fatal error upon adding myself:
Ineligible accounts not added
The following email addresses are either not associated with a Google
Account or the account is not eligible for designation as a test user

3. On the resetting client secret option, I don't get the option to reset
it. All of my extensions are off.

**Comment by darkskyliner34** [comment]
@TheSystemGuy1337 if you let me i can try to help, do you have teamviewer installed?
do you work on windows?

**Comment by TheSystemGuy1337** [comment]
Nice try, hacker.

**Comment by darkskyliner34** [comment]
> Nice try, hacker.

That got me for trying to help lol
