### ISSUE TITLE
[Suggestion] Allow using the "escape" key to close the assistant window

### ISSUE THREAD

**Issue by JediRhymeTrix** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#92]

**Comment by TheNexter** [comment]
Very good idea, or space bar when anything is enter
![image](https://user-images.githubusercontent.com/17613028/107766149-56166500-6d33-11eb-9e7b-0b10e4ded222.png)

**Comment by esau-morais** [comment]
There's actually an option on the settings called "Window Float Behavior" and you can just set "Close on blur"

**Comment by Psykozis** [comment]
maybe minimize when we click out of the form too

**Comment by Melvin-Abraham** [comment]
_Closing as resolved in #157_
