### ISSUE TITLE
windows shortcut, for taskbar or desktop

### ISSUE THREAD

**Issue by TheNexter** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#94]
I don't find how to do a shortcut, if i try to launch with the .exe it's say me that :
![image](https://user-images.githubusercontent.com/17613028/107767477-426bfe00-6d35-11eb-9ad5-b29640c15ede.png)

**Comment by Melvin-Abraham** [comment]
@TheNexter You can launch Assistant via any of the following:

- Open the tray icon (**Show hidden icons** in taskbar) then right-click on "Google Assistant".
- Or launch using **"Windows Key + Shift + A"** (see [Default Keyboard Shortcut](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#default-keyboard-shortcut))

**Comment by TheNexter** [comment]
Guy, it's not for that 😥

I wan't to put on my nexus dock, yes it's windows 😅

I need a shortcut for that 😅

![image](https://user-images.githubusercontent.com/17613028/107798949-182e3680-6d5d-11eb-91eb-81e9fb9b2d50.png)

**Comment by mkody** [comment]
I'd like to support that request since opening the window from the taskbar is easier than double-clicking a small icon when you use a touch screen.

So instead of throwing an error, the Assistant's window should open.
