### ISSUE TITLE
Improvement of Japanese translation

### ISSUE THREAD

**Issue by Robot-Inventor** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#96]
The current Japanese translation is as follows.

```javascript
  "ja-JP": {
    "langName": "日本語（日本）",
    "welcomeMessage": "こんにちは！ 手伝いましょうか？",
    "inputPlaceholder": "何でも聞いてください...",
    "listeningMessage": "聞いている...",
    "initSuggestions": [
      { "label": "天気", "query": "今日の天気は？" },
      { "label": "コインを投げる", "query": "コインを投げる" },
      { "label": "あなたは何ができますか？", "query": "あなたは何ができますか？" }
    ]
  },
```

However, I think the following is more natural Japanese.

```diff
  "ja-JP": {
    "langName": "日本語（日本）",
    "welcomeMessage": "こんにちは！ 手伝いましょうか？",
    "inputPlaceholder": "何でも聞いてください...",
-   "listeningMessage": "聞いている...",
+   "listeningMessage": "聞いています...",
    "initSuggestions": [
      { "label": "天気", "query": "今日の天気は？" },
-     { "label": "コインを投げる", "query": "コインを投げる" },
+     { "label": "コインを投げて", "query": "コインを投げて" },
-     { "label": "あなたは何ができますか？", "query": "あなたは何ができますか？" }
+     { "label": "何ができる？", "query": "何ができる？" }
    ]
  },
```

**Comment by Melvin-Abraham** [comment]
@Robot-Inventor You are welcome to open a PR with following changes. 😊

**Comment by Robot-Inventor** [comment]
Thank you. I have created a pull request!

**Comment by Melvin-Abraham** [comment]
@Robot-Inventor Thank you for the contribution. Your PR has been merged! 😊

**Comment by Melvin-Abraham** [comment]
@Robot-Inventor **"何ができる？"** translates to _"What can I do?"_ instead of _"What can you do?"_ as per Google Translate. Can you check that?

**Comment by Robot-Inventor** [comment]
If the subject is clear, the subject is omitted in Japanese. In this case, it's a question, so I think it's clear that the subject is "you." There is no problem with Google Translate because it is not good at translating according to the situation and it just does not interpret the subject correctly.

In addition, my family and I are Japanese, so I asked my family, and they correctly interpreted it as meaning "What can you do?"

**Comment by Melvin-Abraham** [comment]
@Robot-Inventor Thank you for the clarification. _Closing this issue as resolved..._
