### ISSUE TITLE
AUR(Arch User Repository)

### ISSUE THREAD

**Issue by DestroyerXyz** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#97]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add release builds to the [AUR](https://aur.archlinux.org)

**Comment by Melvin-Abraham** [comment]
@DestroyerXyz Thank you for the suggestion 👋. The next release will be added to AUR once the `.deb` package is released alongside.

**Comment by ERLindeman** [comment]
I've noticed that v1.0.0 has been released, but it is still not available from the AUR. It would be a great help to me—and I'm sure to many others as well—if you could remedy this and follow through on this promise. I'd be willing to do whatever I can to help in this endeavor.

**Comment by yochananmarqos** [comment]
I have PKGBUILDs as [`g-assist`](https://github.com/yochananmarqos/pkgbuilds/tree/master/g-assist) and [`g-assist-git`](https://github.com/yochananmarqos/pkgbuilds/tree/master/g-assist-git). If someone wants to add them to the AUR, feel free. I don't use it, so I never bothered adding them.

**Comment by DestroyerXyz** [comment]
@Melvin-Abraham Any updates on this, and also do you plan on any releases before 2.0?
@yochananmarqos Can you create a PKGBUILD for g-assist-bin also? I can upload it to the AUR.

**Comment by yochananmarqos** [comment]
@DestroyerXyz Here you go: [`g-assist-bin`](https://github.com/yochananmarqos/pkgbuilds/tree/master/g-assist-bin)

**Comment by DestroyerXyz** [comment]
Done! https://aur.archlinux.org/packages/google-assistant-unofficial-desktop-client-bin/

**Comment by im-coder-lg** [comment]
Woah, so does that mean a DEB is a key to making an AUR binary?

**Comment by yochananmarqos** [comment]
@im-coder-lg I'm not sure what you're asking. Any binary upstream source can be used including a DEB or RPM.

**Comment by DestroyerXyz** [comment]
It basically has a Linux elf binary inside. DEB is just a packaging format for files and metadata like macos APP. So the PKGBUILD is a script that manually unpacks the DEB and installs the files in the correct locations.

**Comment by im-coder-lg** [comment]
Yeah but isn't DEB used mainly for Debian-based distros or is Arch based on Debian without APT?

**Comment by DestroyerXyz** [comment]
No, Arch is not based on Debian. `.deb` is a packaging format that Debian's package manager APT understands and Arch's package manager called Pacman uses `.tar.zst`.
DEB is not used for any official Arch repo packages, and not always even for the AUR.

**Comment by Melvin-Abraham** [comment]
> do you plan on any releases before 2.0

I do plan to release at least one minor version later
